### PR TITLE
Derivative

### PR DESCRIPTION
**Pull request by tthsqe12**
Adds
 - differentiation
 - integration
 - set_str function so you can do `fmpz_mpoly_set_str_pretty(f, "(x+y)^2", vars, ctx)`

We are going to need these functions eventually.

### CODE REVIEW

**Comment by fredrik-johansson** [comment]
For consistency, we use the names foo_poly_derivative() and foo_poly_integral() in the other polynomial modules.

**Comment by wbhart** [comment]
These are really cool!

**Comment by fredrik-johansson** [comment]
The set_str_pretty function is especially nice for running simple test cases.

However, I suggest changing the loop with fmpz_mul_ui to search for the end of the digit sequence and do a single call to fmpz_set_str... before someone inevitably tries to use it with 10000-digit coefficients.

**Comment by tthsqe12** [comment]
I will investigate parsing integers all at once.
However, this function is not meant to be efficient on large inputs. The current architecture of the module implies that parsing the sum of n arbitrary monomials is going to take n^2 time. Reducing this will require a more sophisticated parser.

**Comment by wbhart** [comment]
I don't think there is any motivation to getting a linear time parser for polynomial expressions at this stage. It can be done, but it's a fair amount of work, and there are too many other priorities. It makes sense to parse integers all at once though.

**Comment by tthsqe12** [comment]
This patch should be good now.

**Comment by tthsqe12** [comment]
This patch should be good now.

**Pull request merged**
