### PR TITLE
Renamed strassen_mul.c to mul_strassen.c

### PR DESCRIPTION
**Pull request by aaditya-thakkar**
Thanks for pointing out @wbhart and @fredrik-johansson , I have renamed the file strassen_mul.c to mul_strassen.c

### CODE REVIEW

**Comment by wbhart** [comment]
The test file similarly needs renaming as does the strassen_mul in the first printf in the test function.

**Comment by wbhart** [comment]
Perfect, thank you. I'll merge this as soon as the CI finishes.

**Comment by argriffing** [comment]
When I was building flint I noticed the tester was chilling in `t-mul_strassen` for longer than in most tests. I know that flint has a global setting to scale the number of test iterations, but is there some tool to help calibrate the number of iterations so that timings are not unnecessarily disproportionate among tests?

**Comment by fredrik-johansson** [comment]
There's no such tool (but it would be nice to have a way to see the amount of time spent on each test).

I don't think there's a good reason to test Strassen multiplication for an extreme amount of time. This just needs to be patched.

**Pull request merged**
