### PR TITLE
Ultraspherical (Gegenbauer) polynomials

### PR DESCRIPTION
**Pull request by rwst**
There may be inefficiencies in the coefficient computation due to my inexperience with flint. Also, in the test code I had to reinitialize poly variables because of spurious results, which was not necessary before. This may or may not point to a problem in the Gegenbauer or the fmpq_poly code, I have no idea.

### CODE REVIEW

**Comment by fredrik-johansson** [comment]
You should declare a as const.

In n == 1, you don't need to canonicalise; a is assumed canonical on input. A simpler way to implement this case is to check if the denominator of a is even, and then divide by denominator by 2; otherwise multiply the numerator by 2.

You need to normalise the output with _fmpq_poly_normalise; the leading coefficient could be 0.

When n >= 2, are you sure that the output is canonicalised (smallest denominator). You might need to canonicalise it explicitly to be sure. You shouldn't be calling fmpq_poly_canonicalise anywhere in the test code.

Testing a = 1/d seems like a good approach, but you might want to try some other random values too.

> Also, in the test code I had to reinitialize poly variables because of spurious results, which was not necessary before.

This is a bug that needs to be fixed, but I don't see what's causing it. Possibly the lack of normalisation.

**Comment by fredrik-johansson** [comment]
The algorithm looks all right.

It's not obvious to me that the divisions really are exact, as they certainly would be if you did the multiplications before the divisions.

Instead of the extra fmpz_mul_2exp, you can fmpz_mul_ui by 4*(kk+1). It might also be slightly faster to do a multiplication and a single divexact instead of the two divexacts.

**Comment by rwst** [comment]
(From mobile) Thanks. I think the bug is simply that I forgot to zero the zeroes. Will see tomorrow.

**Comment by rwst** [comment]
I didn't understand some of your optimisation comments. If necessary, could you please clarify?

**Comment by fredrik-johansson** [comment]
In the n == 1 case, you could do

        fmpz_zero(coeffs);
        if (fmpz_is_even(fmpq_denref(a)))
        {
            fmpz_tdiv_q_exp(den, fmpq_denref(a), 1);
            fmpz_set(coeffs + 1, fmpq_numref(a));
        }
        else
        {
            fmpz_set(den, fmpq_denref(a));
            fmpz_mul_2exp(coeffs + 1, fmpq_numref(a), 1);
        }

For the divisions, instead of

        fmpz_divexact(p, p, de);
        fmpz_divexact2_uiui(p, p, n-2*kk-1, n-2*kk);

you could do

        fmpz_mul2_uiui(tmp, de, n-2*kk-1, n-2*kk);
        fmpz_divexact(p, p, tmp);

This is potentially slightly faster when the denominators are small. Maybe not worth bothering about though.

By the way, you removed _fmpq_poly_set_length(poly, n + 1); which means the length is no longer set anywhere...

**Comment by rwst** [comment]
> By the way, you removed _fmpq_poly_set_length(poly, n + 1); which means the length is no longer set anywhere...
So the documentation on normalise is misleading? "Sets the length of \code{poly} so that the top coefficient is non-zero. If all coefficients are zero, the length is set to zero."

**Comment by fredrik-johansson** [comment]
Yes, but you need to set the tentative length first so that normalise starts looking from the correct place!

**Comment by rwst** [comment]
This should be it.

**Pull request merged**
