### PR TITLE
Fix a few more typos

### PR DESCRIPTION
**Pull request by fingolfin**

### CODE REVIEW

**Comment by wbhart** [comment]
I assume this means you've had good news and have some time on your hands in between not sleeping?

**Comment by fingolfin** [comment]
The time spent on this and the previous one was maybe half an hour in total (writing a Julia script to parse a bunch of files into a list of words, then running a spellchecker over that manually and grabbing hits that look like actual typos, not just identifiers or names, then fixing the spelling anywhere they appear). Indeed did that while not really being able to do much else (taking care of the kid makes it hard to properly focus :/).

**Comment by wbhart** [comment]
Well done on the other thing. And cool, I wondered how you were doing this.

I actually found and corrected some typos in the fmpz_mpoly dir today. They have probably also been cut'n'pasted everywhere.

**Comment by fingolfin** [comment]
Yeah, so I only looked at a few toplevel files (README etc.) and a bunch of files in `doc`. Something like this:
```
 ./text_to_words.jl README doc/source/*.rst NEWS > words
```
where `text_to_words.jl` is this "brilliant" piece of code:
```julia
#!/usr/bin/env julia
words = Set{String}()
re = r"\b[a-zA-Z]+\b"

function scanfile(file)
    lines = open(readlines, file)
    for l in lines
        for w in eachmatch(re, l)
            push!(words, w.match)
        end
    end
end

for file in ARGS
    scanfile(file)
end

for w in sort(collect(words))
    println(w)
end
```

And then I just used the system spellchecker manually to go through the list, which was the part which took most time (but it's fairly quick anyway). Automating this part would have taken far more time (as one would have to find a way to exclude identifiers and names), but it could be in theory interesting if one wanted to do such automated spell checks regularly. But I don't think it's worth the effort. Hence the manual solution.

**Comment by wbhart** [comment]
I think it's a pretty reasonable approach to be fair. It'd take more time to deal with false positives/negatives if it were more automated. So I'd certainly do it the same way.

I'd hate to think what lint or some of the other automated bug finding tools would say about a code base the size of Flint.

**Pull request merged**
