### PR TITLE
Fibonacci polynomials implemented

### PR DESCRIPTION
**Pull request by shivin9**
2 files arith/fibonacci_polynomials.c and it's test file in arith/test have been added. The docs have also been updated accordingly.

### CODE REVIEW

**Comment by wbhart** [comment]
Thanks. This looks quite good. There are a few minor things that need changing.

* You need to add a prototype for the function to arith.h (it needs to have the FLINT_DLL macro in front of it too, for Windows support; just see some of the other prototypes to see what I mean)

* You don't need to include profiler.h in the test code. Actually you can remore stdlib and stdio as well (I realise we use them everywhere, but this is just left over from when we used to use malloc and printf in test files; we no longer do)

* Can you remove the blank line before all the else statements. This is not wrong, just a stylistic difference. We want to keep things as consistent as possible.

* Another stylistic difference: could you check that you are using 3 spaces everywhere for indentation (and not tabs).

**Comment by wbhart** [comment]
Also

* you don't need to include fmpz_mat.h in the test code.

**Comment by wbhart** [comment]
Also

* I think there is a closing $$ missing in the documentation you added.

**Comment by fredrik-johansson** [comment]
* The current plan is to deprecate the arith module and put functions of this kind in the modules for the respective types. See fmpz_poly/chebyshev_t.c.

* You can easily make n = 0 and n = 1 work in the underscore method. No need to special case this in the non-underscore method.

* I think your code does an unnecessary division for the top coefficient. You can just set it to 1 and break out of the main loop one step earlier.

* Indentation should be 4 spaces.

**Comment by shivin9** [comment]
Dear sir,
Thanks for pointing out these errors! I will keep try to keep them in mind. 
I hope I haven't missed anything now!
Thanks

**Comment by wbhart** [comment]
Another .swp file has been committed by accident.

I agree with Fredrik, you should move the function to fmpz_poly, so I guess it will be fmpz_poly_fibonacci instead of arith_fibonacci_polynomial.

**Comment by shivin9** [comment]
Hi,
I'm trying to put the n = 0 and n = 1 cases in the underscore function only the equality checking function in the t-fibonacci_polynomial.c is not able to recognize that the polynomial initialized using 
fmpz_poly_set_ui(Pn, UWORD(0)); and the polynomial whose coefficients are 0 is the same.

and even if I fix that I'll still have to pass a flag to the underscore function to tell the difference between n = 0 and n = 1 case as the degree of both the polynomials is 1.

The extra division for calculating the leading coefficient has been removed and it has been moved to the fmpz module.

Thanks

**Comment by fredrik-johansson** [comment]
When n = 0, the length of the polynomial is 0, which means that you just don't have to write any coefficients at all. So you can do something like this:

    void _fmpz_poly_fibonacci(fmpz * poly, ulong n)
    {
        if (n == 0) return;

        fmpz_one(poly + n - 1);  /* write top coefficient */

        /* write all remaining coefficients */
    }

    void fmpz_poly_fibonacci(fmpz_poly_t poly, ulong n)
    {
        fmpz_poly_fit_length(poly, n);
        _fmpz_poly_fibonacci(poly->coeffs, n);
        _fmpz_poly_set_length(poly, n);
    }

**Comment by wbhart** [comment]
It's getting better. But you still have all the .swp files committed. You need to git rm them (make copies of them first if you need them for something, since git will likely delete them).

Also, based on the other arithmetic polynomial functions in fmpz_poly, I think the name of the function should be fmpz_poly_fibonacci, not fmpz_poly_fibonacci_polynomial.

**Comment by shivin9** [comment]
I'm so sorry, I thought adding .swp to .gitignore might help... I'll stop using vim altogether.

**Comment by wbhart** [comment]
If you don't add the files to source control, and check what you are committing, you shouldn't have a problem.

**Comment by wbhart** [comment]
This looks good to me. There is only one other thing that I see:

* You call fmpz_one(coeffs + n - 1); in both the even and odd cases. You can pull this out of the if statement altogether and just have that line of code once.

Otherwise I am happy.

**Comment by wbhart** [comment]
Fredrik is also happy, so it's ready to merge once you fix that last issue I mentioned.

One other thing, do you know how to squash commits. Some of the commits, such as removing .swp files aren't really useful, since the .swp files weren't there in Flint to start with. You could squash some of the commits so that the commits look more like you would expect in the Git commit history.

This should be safe as no one will have merged from you just yet.

**Comment by wbhart** [comment]
Oh, a few other things we just noticed:

* you should document both the underscore and non-underscore versions of the function. Our developer documentation currently documents all functions in Flint, not just the ones the user is intended to use.

* The test code should be changed to just print fibonacci instead of fibonacci_polynomial

* The name of the test file should be t-fibonacci.c.

**Comment by shivin9** [comment]
let me start afresh.
I'll issue a new Pull Request.

**Pull request closed without merging**
