### PR TITLE
Patterson-Stockmeyer Algorithm

### PR DESCRIPTION
**Pull request by ashish1294**

### CODE REVIEW

**Comment by fredrik-johansson** [comment]
There are some spelling errors: "scaler" should be "scalar", "Patterson" should be "Paterson"

You could use n_sqrt instead of sqrt (you don't need math.h).

There is a memory leak: temp is not freed.

You can avoid a matrix multiplication when creating temp[1].

Otherwise this code looks ok to me.

Did you think about whether this algorithm is optimal for very short polys?

**Comment by ashish1294** [comment]
I have fixed the errors you pointed out !

I didn't think about the situation where polynomials are very short. Horner's might be better for very small polynomials, but to confirm I will have to compare the performance of both the algorithms

**Comment by wbhart** [comment]
Thanks for this Ashish.

However, so far the code still seems to have only the Paterson-Stockmeyer implementation and Horner is still not there.

Now that you have a decent crossover function, perhaps you could implement a wrapper function nmod_poly_evaluate_mat which calls either nmod_poly_evaluate_mat_paterson_stockmeyer or nmod_poly_evaluate_mat_horner, depending on the crossover.

Once you've done this and the tests pass, I think we can merge this code.

**Comment by ashish1294** [comment]
That is exactly what I have done.
Horner and Paterson-Stockmeyer both are there along with a wrapper function
that selects the best algorithm using the crossover function.

I have also improved the documentation.
All tests are also passing.

See : https://github.com/wbhart/flint2/pull/143/files

Regards,
Ashish

**Comment by wbhart** [comment]
Oh, I see. I was misled by the fact that you've put the implementations in the same file.

In flint we use different files for each algorithm.

Also, as I said, the nmod_poly_evaluate_mat function can probably be a static inline (FLINT_INLINE) in  nmod_poly.h. It doesn't need a separate file.

Then there should be separate test files for each implementation. nmod_poly/test/t-evaluate_mat_horner.c etc.

(You don't need a separate test for the inline version.)

**Comment by ashish1294** [comment]
Both the algorithm uses a common subroutine and this is why I placed them in the same file.

The test files for both algorithms will all so be same.

**Comment by wbhart** [comment]
Sorry Ashish, I hadn't noticed you had replied.

I still think the two implementations should be separated into two different files. You can call the common subroutine from the other file by placing it's prototype in nmod_poly.h. Of course you can put a note in one of the files about where to find the implementation of the common function.

There's also slightly less overhead in a static inline function. Surely it won't make much difference here, but it certainly doesn't do any harm. The nmod_poly_evaluate_mat function is a good candidate for being a static inline function in nmod_poly.h.

Also, the test code doesn't properly test both implementations. It only tests one implementation in one range and the other implementation in the other range.

There should be separate tests functions, one for one implementation, one for the other.

This is important because if there is a bug that doesn't show up because of the current tuning cutoffs, it will show up if the cutoffs are changed. 

You might not change the cutoffs, and you might not even implement the bug in the function, but someone else might. They could quite easily be misled by the test code into thinking that they modifications worked, and they might not even be being run by the test code.

Sorry to be insistent on these things, but it is how most of the rest of flint is implemented.

**Comment by ashish1294** [comment]
Hi, I have made separate files for each algorithm and have written testing functions for both.

**Comment by wbhart** [comment]
Thanks Ashish!

I see a few things that remain to be done:

* the filename t-evaluate_mat_honer.c is misspelled

* The paterson_stockmeyer and horner functions should be separately documented.

* I think the nmod_mat_scalar_mul_add function looks generally useful. It should be moved into a separate file and documentation and test code added (the other minor function you added doesn't look so generally useful, so no need to do anything with that)

I don't see any other issues. The code looks good.

**Comment by ashish1294** [comment]
Hi, I have updated the code.

**Comment by wbhart** [comment]
Hi Ashish,

thanks for this. Sorry it took so long, but I've now merged your code. Thank you very much for your contribution!

**Comment by wbhart** [comment]
Actually, there are still a few things missing.

* You don't seem to have declared nmod_mat_scalar_mul_add in nmod_mat.h. This leads to a compiler warning.

* nmod_poly_evaluate_mat does not seem to be documented in nmod_poly.h, you seem to have only documented the individual algorithms but not nmod_poly_evaluate_mat itself

Could you initiate another pull request with these two fixes. Thanks.

**Pull request merged**
