### PR TITLE
Thread limit cleanup try 3

### PR DESCRIPTION
**Pull request by tthsqe12**

### CODE REVIEW

**Comment by tthsqe12** [comment]
@wbhart I am completely at a lost as to why your
t-compose_mod_brent_kung_precomp_preinv_threaded.c
works and my stuff does not.

**Comment by wbhart** [comment]
Can you try making each of your bivar_divides_check functions static in the test code. I think the problem is not the flint_request_threads or flint_give_back_threads, but the functions they are called from.

**Comment by wbhart** [comment]
Don't worry, apparently it's not that.

**Comment by tthsqe12** [comment]
What is even worse is that I can't reproduce this on my native msys+mingw installation. Configure was
./configure --disable-static --enable-assert --reentrant --with-gmp=/c/msys64/mingw64 --with-mpfr=/c/msys64/mingw64 --prefix=/c/msys64/mingw64
Other than make install not copying the dll to the bin dir, everything was fine

**Comment by tthsqe12** [comment]
What other config options should I try?

**Comment by wbhart** [comment]
I think I've fixed it. flint.h was not included in thread_support.h and thread_support.h was not included in thread_support.c. I made those changes in trunk and the build here seems to be going through.

Basically the dllimport magic was just not making it through to your two functions flint_request_threads and flint_give_back_threads, so even though you had FLINT_DLL in front of them, it was empty.

**Comment by wbhart** [comment]
If you like, you can close this PR and open another based on your branch, so that all my extra commits here go away. The necessary commits have been made in trunk.

**Comment by tthsqe12** [comment]
Ok. Still wondering why I cant reproduce it.

**Comment by wbhart** [comment]
Random compiler nonsense. Probably compiler version.

**Comment by tthsqe12** [comment]
So everything is good now?

**Comment by wbhart** [comment]
Sure, but do you want to reopen the PR so my unneeded commits go away.

**Comment by tthsqe12** [comment]
Of course. Im in the middle of another bug atm.

**Pull request closed without merging**
