### PR TITLE
Better cfrac

### PR DESCRIPTION
**Pull request by tthsqe12**
Feel free to say this is a pile of useless rubbish. The main mess in is the top of https://github.com/tthsqe12/flint2/blob/60f432ad670990e92451de32057a944287498a8c/fmpq/get_cfrac_helpers.c where I had to import a bunch of gmp implementation macros. The fields of an mpz seem to be accessed directly elsewhere in flint, so I can expand them out if this is better. There are also three types that I needed at the bottom of fmpq.h. These are internal types, which, as I understand, should have underscores.

### CODE REVIEW

**Comment by wbhart** [comment]
The usual way to handle the GMP macros would be to put them in gmpcompat.h and maybe call them FLINT_BLAH_BLAH_BLAH instead of BLAH_BLAH_BLAH. The last step is only usually necessary if they could conflict with something in gmp.h, which is unlikely unless they look like things that might eventually become part of the public interface.

**Comment by tthsqe12** [comment]
just to give some context, the main contribution is _fmpq_hgcd, which is useful for computing at least
    (1) continued fractions
    (2) rational approximations
    (3) rational reconstructions
    (4) dedekind sums
I have used it for (1), added (2), put a todo on (3), and left (4) for another time. It was @fredrik-johansson who added the very slow euclidean versions of (1), (3), and (4).

**Comment by wbhart** [comment]
I'm ok with merging this now. Just let me know when you are ready.

**Comment by tthsqe12** [comment]
Alright. Only point 3 is left and it can be done when someone complains about reconstruction.

**Pull request merged**
