### PR TITLE
add nmod and fmpz_mod to fq_default

### PR DESCRIPTION
**Pull request by tthsqe12**

### CODE REVIEW

**Comment by wbhart** [comment]
Is it worth opening a ticket for the missing functions?

```
nmod_mat_is_one
nmod_poly_is_unit
nmod_poly_scalar_addmul_nmod
nmod_poly_scalar_submul_nmod

nmod_mat_set_fmpz_mod_mat

nmod_poly_hamming_weight
```

**Comment by tthsqe12** [comment]
Ill just do them here.

**Comment by tthsqe12** [comment]
This is probably as much as I want to do in this PR

**Comment by tthsqe12** [comment]
Alright, I will do fmpz_mod in this PR too.

**Comment by tthsqe12** [comment]
@wbhart I think I have everything copied and pasted with the appropriate search and replace now for the fmpz_mod_mat module.

**Comment by wbhart** [comment]
Cool, I will take a look after lunch.

**Comment by wbhart** [comment]
Oh wow, this is a seriously fantastic Christmas present for Flint users! Thanks for doing all that.

The only things I could find were:

1) In some of Fredrik's copyright notices there's no space between the years. Probably not your fault, but better to not duplicate.

2) I didn't realise we had a TEST macro. It seems to be named in an oddly unspecific way. I can just imagine someone eventually complains it conflicts with someone else's TEST macro, not that I can think of a way that can happen just yet (give the Linux people a little more time to work on that one). FLINT_TEST would be better.

3) I don't personally use e as a variable name, due to potential to confuse it with the Euler constant e.

I would like to wait for 1 to be fixed. I don't care much about the others. If you think it's worth doing anything go ahead. I will merge without anything being done there. I'm just writing something since there isn't much else to write. The code looks great!

**Comment by tthsqe12** [comment]
Huh? There is nothing new here except that the fq_mat_templates have been copied to the fmpz_mod_mat so that fmpz_mod can participate in the union. This is *no new functionality* whatsoever.
1. I can try to put the spaces in
2. I added the TEST macro because I got tired of the previous way things were done. I can change it to FLINT_TEST.
3. I don't think this is relevant because the C standard doesn't provide a standard definition of "e".

**Comment by wbhart** [comment]
That's not what GitHub is showing me. It shows commit 8425171f4e contains a whole load of fmpz_mod_mat functionality that wasn't there before. Am I misinterpreting that somehow?

How do you "copy" templates from fq_mat to fmpz_mod_mat? I'd have done this ages ago if this was easy.

**Comment by wbhart** [comment]
Great! And this is now ready to merge from your perspective?

**Comment by tthsqe12** [comment]
Let's wait for the green lights.

**Comment by tthsqe12** [comment]
At some point in the future we have to decide if we are going make a breaking change by requiring a ctx object to each fmpz_mod_mat operation (like all of the finite fields, unlike nmod). I kept it the way it currently is with the ctx object stored in each mat for now.

**Comment by wbhart** [comment]
If that could actually improve anything, then I'd be ok with it. fmpz_mod_mat is a very recent module that is not very complete (until now). I think it is reasonable to make some changes to it, though it would mean rewriting some Nemo code.

**Comment by tthsqe12** [comment]
ok merge me please

**Pull request merged**
