### PR TITLE
Power sums for fmpq_poly

### PR DESCRIPTION
**Pull request by videlec**
Here is an implementation of power sums for fmpq_poly. Dealing with the denominator was quite tricky (my version is perhaps suboptimal).

I also fixed a small typo in fmpz_poly.h where there was an occurrence of "Newton series" in some comment.

### CODE REVIEW

**Comment by wbhart** [comment]
Thanks for this and sorry for the delay in responding.

In _fmpq_poly_power_sums you call fmpq_poly_fit_length on an array of fmpz's. This shouldn't happen in Flint. The array of fmpz's should be set to the correct length before calling the underscore function. The basic contract of the non-underscore functions is to handle aliasing, memory management and any special cases not handled by underscore functions, and of course to select between algorithms.

I would probably space the code out a little more by say putting some blank lines before for loops, just to make it look a little less crowded.

Line 130 of power_sums.c looks odd with just n on its own. I guess indent did that. I would move length down from the previous line as with the other cases where the line overflows. Hopefully indent is ok with that. It's not at all important of course.

The function fmpq_poly_power_sums_to_poly should have an aliasing test, since the input and output could be aliased. It's sufficient to check that it returns the same answer as the same function without aliasing, over a reasonable set of inputs for this function.

We also usually have separate test files for each function tested, unless there is a function pair where one is tested against the other. I wouldn't go to the trouble of changing this now, but it's worth sticking to this where possible.

That's all I can see for now. This looks like well-written code and worth merging.

**Comment by fredrik-johansson** [comment]
One small thing I would change is to call _fmpz_poly_power_sums_naive from _fmpq_poly_power_sums when the input is a monic integer polynomial, and not in fmpq_poly_power_sums.

By the way, are you planning to add methods for the composed sum/product/quotient?

**Comment by videlec** [comment]
@wbhart @fredrik-johansson I implemented your suggestions in the last commit.

About composed sum/product/quotient it is indeed my goal (see the related Sage ticket  http://trac.sagemath.org/ticket/18356 that contains a Sage implementation). As remarked during the implementation of fmpz_power_sums, the implementation would better be multimodular. I will hence continue with nmod_poly_power_sums. The only non-trivial task would be to found good bounds on the coefficients of the composed sum/product/quotient. Do you have any idea or know any reference?

**Comment by wbhart** [comment]
Thanks! Everything looks ready to merge. I will do so once the continuous integration tests have passed in 20 minutes or so.

**Pull request merged**
