### PR TITLE
Update fmpz mpoly mul

### PR DESCRIPTION
**Pull request by tthsqe12**

### CODE REVIEW

**Comment by wbhart** [comment]
Is this PR ready to go? Or are you still adding to it?

**Comment by fredrik-johansson** [comment]
Is "ffmpz" instead of "fmpz" a typo?

**Comment by tthsqe12** [comment]
@wbhart Let me check that the paths taken are least sensible in some cases. BTW, I think we are going to need another version of mul that takes a parameter to limit the number of threads. As it currently stands, any internal use of mul is probably going to grab all of the remaining threads.
@fredrik-johansson It is indeed not a typo, `ffmpz` stands for a flat array of fmpz's (`fmpz*`). In the beginning, there was only `{get|set}_monomial` and we threw on exponent overflow. Then multi-precision exponents came, and these got split into `{get|set}_monomial_{ui|fmpz}` where the fmpz version took a `fmpz*`. Then, as it was realized that julia cannot work with `fmpz*` and I got tired of writing conversions between `fmp**` and `fmpz**` in every function, the `{get|set}_monomial_{ui|ffmpz|pfmpz}` split was born where `pfmpz` means `fmpz**`. Now that the requirements of the interface are more or less set, I can probably clean things up and speed things up.

**Comment by wbhart** [comment]
By the way, nmod_mpoly_ctx_nvars is missing.

**Comment by wbhart** [comment]
Also:
 * nmod_mpoly_inlines.c is missing
 * nmod_mpoly_is_gen seems to return false for x in Z/23Z[x, y]

**Comment by wbhart** [comment]
Also:

* nmod_mpoly_ctx_ord is missing

**Comment by tthsqe12** [comment]
@wbhart could you merge this soon?

**Comment by wbhart** [comment]
Yes, I didn't realise it was ready to go.

**Pull request merged**
