### PR TITLE
Implemented Minimal Polynomial for a Matrix over Integers

### PR DESCRIPTION
**Pull request by tanmaysahay94**
I have used the abstractions provided in the existing Flint library to implement the algorithm provided in the following link: http://mathworld.wolfram.com/MatrixMinimalPolynomial.html

Testing files are yet to be added.

### CODE REVIEW

**Comment by wbhart** [comment]
Thanks Tanmay. As well as test code you also need documentation in fmpz_mat/doc/fmpz_mat.txt and a prototype in fmpz_mat.h.

**Comment by tanmaysahay94** [comment]
Bill, I've added the documentation and the prototype. Sorry for the delay. My apologies.

**Comment by wbhart** [comment]
Thanks Tanmay.

**Comment by wbhart** [comment]
I think we've decided that this function needs a more efficient algorithm.

The usual algorithm is based on something called "spinning". It is
essentially making use of the Jordan canonical form and "spinning" a random
vector around in it. This is much more efficient and doesn't have the huge
memory overhead of this function.

It would be great to have this function in flint, but we want to hold off
putting in something highly suboptimal for now.

**Pull request closed without merging**
