### PR TITLE
add modular gcd for fmpz_mpoly

### PR DESCRIPTION
**Pull request by tthsqe12**
This is not quite ready to merge yet. I would just like a 32-bit opinion.

### CODE REVIEW

**Comment by tthsqe12** [comment]
This last commit took longer than expected to test properly. There will be more one commit for fmpq so that the coefficients/exponents of fmpz_mpoly's can be iterated over as well.

**Comment by tthsqe12** [comment]
This is now good. The functions on my wish list for inclusion into the rest of flint are in mpoly/MISSING_FXNS.c

**Comment by wbhart** [comment]
Any chance you could move the wishlist into the todo.txt file at the top
level of flint, or make tickets on GitHub (or both)?

**Comment by tthsqe12** [comment]
I put a note in the todo about the extra functions. I will probably add to this list in the future.

**Pull request merged**
