### PR TITLE
add term_content

### PR DESCRIPTION
**Pull request by tthsqe12**
I would like to underscore the fact that we have term_content now.

### CODE REVIEW

**Comment by wbhart** [comment]
This would already allow me to make a version of gcd that special cases poly X monomial gcd. Or do you want me to wait until you sort that issue out in Flint itself?

**Comment by tthsqe12** [comment]
Would you ever have a need for bypassing flint? You can add it for fun now, but there will be no need in gcd once fmpz_mpoly_gcd is worked out. I will also do checks to see if one input is an easy multiple of the other, ect.

**Comment by wbhart** [comment]
Oh, I only just got the underscore joke a minute ago.

**Comment by wbhart** [comment]
I think you are missing TMP_END in term_content.c.

**Comment by tthsqe12** [comment]
should be good now

**Pull request merged**
