### PR TITLE
add fmpq_mpoly_pow_si

### PR DESCRIPTION
**Pull request by tthsqe12**
https://github.com/wbhart/flint2/issues/466 Now the following functions are defined:
 - `fmpq_mpoly_pow_si`
 - `fmpq_mpoly_is_gen`
 - `fmp{q|z}_mpoly_pushback_fmp{q|z}_{fmpz_ui}`
 - `fmp{q|z}_mpoly_combine_like_terms`

Also, the fixme on fmpz_pow_ui has been fixed.

@wbhart @thofma Please have a look at the documentation in fmpq_mpoly/docs and let me know if it looks reasonable for interfacing with a real cas. https://github.com/tthsqe12/flint2/blob/8222286ab00fc6a44dcf49f8c09973f7a5986a0b/fmpq_mpoly/doc/fmpq_mpoly.txt

### CODE REVIEW

**Comment by thofma** [comment]
Looks reasonable to me. Thanks @tthsqe12 

Only one question: What are "like terms" and "adjacent like terms"?

**Comment by tthsqe12** [comment]
@thofma I will soon add the `pushback_term_{si|ui}_{fmpz|ui}` to fmpz_mpoly. For now, observe that the output of the problem at the end of this comment is
`              f: 3*x^3+4*x^3+5*x^4+6*x^3+2*x^2+3*x^2-5*x^2+0*x+7`
`after combine f: 7*x^3+5*x^4+6*x^3+7`

`              f: 3*x^3+4*x^3+5*x^4+6*x^3+2*x^2+3*x^2-5*x^2+0*x+7`
`   after sort f: 5*x^4+4*x^3+3*x^3+6*x^3+2*x^2+3*x^2-5*x^2+0*x+7`
`after combine f: 5*x^4+13*x^3+7`


@wbhart My brain still has not become used to the names `fmpz_mpoly_{get|set}_term_{fmpz|ui|si}_{fmpz|ui}`. These names simply do not correspond to what the functions do. They are not getting/setting terms, they are simple getting and setting a coefficient. I propose the following names changes for the new slew of bookkeeping functions.

1) `fmpz_mpoly_{get|set}_coeff_{fmpz|ui|si}_{fmpz|ui}(poly1, c, e)`: Given an array of exponents `e`, get or set the coefficient `c` of the corresponding to `e`. This function should assume and maintain `poly1` in canonical form.
1.5) `fmpz_mpoly_{get|set}_coeff_{fmpz|ui|si}_monomial(poly1, c, poly2)`: Given that poly2 is a monomial, get or set the coefficient corresponding to this monomial in `poly1`. This function should assume and maintain `poly1` in canonical form and throw if `poly2` is not a monomial. It also should not care about the coefficient of the monomial in `poly2`.
3) `fmpz_mpoly_{get|set}_termcoeff_{fmpz|ui|si}(poly1, c, n)`: Get or set the coefficient of the nth term. This function should throw if `n >= length(poly1)`.
4) `fmpz_mpoly_{get|set}_termexp_{fmpz|ui|si}(poly1, e, n)`: Get or set the exponent vector of the nth term. This function should throw if `n >= length(poly1)`.
4.5) `fmpz_mpoly_termexp_fits_{ui|si}(poly1, n)`: Return whether the nth exponent vector fits. This function should throw if `n >= length(poly1)`.
5) `fmpz_mpoly_pushterm_{fmpz|ui|si}_{fmpz|ui}(poly1, c, e)`: Given an array of exponents and a coefficient, push that term onto the end of `poly1`.
5) `fmpz_mpoly_pushpoly(poly1, poly2)`: Push the terms of `poly2` onto the back of `poly1`. In terms of the values of the polynomials, this has the effect of `poly1+=poly2`.


```#include <stdio.h>
#include <stdlib.h>
#include "fmpz_mpoly.h"

int
main(void)
{
    fmpz_mpoly_ctx_t ctx;
    fmpz_mpoly_t f;
    const char * vars[] = {"x"};
    ulong exp[1];

    fmpz_mpoly_ctx_init(ctx, 1, ORD_DEGLEX);
    fmpz_mpoly_init(f, ctx);

    fmpz_mpoly_zero(f, ctx);
    exp[0] = 3; fmpz_mpoly_pushback_term_si_ui(f, 3, exp, ctx);
    exp[0] = 3; fmpz_mpoly_pushback_term_si_ui(f, 4, exp, ctx);
    exp[0] = 4; fmpz_mpoly_pushback_term_si_ui(f, 5, exp, ctx);
    exp[0] = 3; fmpz_mpoly_pushback_term_si_ui(f, 6, exp, ctx);
    exp[0] = 2; fmpz_mpoly_pushback_term_si_ui(f, 2, exp, ctx);
    exp[0] = 2; fmpz_mpoly_pushback_term_si_ui(f, 3, exp, ctx);
    exp[0] = 2; fmpz_mpoly_pushback_term_si_ui(f, -5, exp, ctx);
    exp[0] = 1; fmpz_mpoly_pushback_term_si_ui(f, 0, exp, ctx);
    exp[0] = 0; fmpz_mpoly_pushback_term_si_ui(f, 7, exp, ctx);
printf("              f: "); fmpz_mpoly_print_pretty(f, vars, ctx); printf("\n");
    fmpz_mpoly_combine_like_terms(f, ctx);
printf("after combine f: "); fmpz_mpoly_print_pretty(f, vars, ctx); printf("\n\n");

    fmpz_mpoly_zero(f, ctx);
    exp[0] = 3; fmpz_mpoly_pushback_term_si_ui(f, 3, exp, ctx);
    exp[0] = 3; fmpz_mpoly_pushback_term_si_ui(f, 4, exp, ctx);
    exp[0] = 4; fmpz_mpoly_pushback_term_si_ui(f, 5, exp, ctx);
    exp[0] = 3; fmpz_mpoly_pushback_term_si_ui(f, 6, exp, ctx);
    exp[0] = 2; fmpz_mpoly_pushback_term_si_ui(f, 2, exp, ctx);
    exp[0] = 2; fmpz_mpoly_pushback_term_si_ui(f, 3, exp, ctx);
    exp[0] = 2; fmpz_mpoly_pushback_term_si_ui(f, -5, exp, ctx);
    exp[0] = 1; fmpz_mpoly_pushback_term_si_ui(f, 0, exp, ctx);
    exp[0] = 0; fmpz_mpoly_pushback_term_si_ui(f, 7, exp, ctx);
printf("              f: "); fmpz_mpoly_print_pretty(f, vars, ctx); printf("\n");
    fmpz_mpoly_sort(f, ctx);
printf("   after sort f: "); fmpz_mpoly_print_pretty(f, vars, ctx); printf("\n");
    fmpz_mpoly_combine_like_terms(f, ctx);
printf("after combine f: "); fmpz_mpoly_print_pretty(f, vars, ctx); printf("\n");


    fmpz_mpoly_clear(f, ctx);
    fmpz_mpoly_ctx_clear(ctx);

    return 0;
}

**Comment by thofma** [comment]
Thanks for the explanation. So adjacent terms are terms with the same monomial/power product?

**Comment by thofma** [comment]
While you are at it, could you add the inlines.c file in fmpq_mpoly/? Otherwise the "inlined" functions are not callable using the shared library.

**Comment by thofma** [comment]
OK, here my final query: Can we have a `is_constant` function? I know there is `is_fmpq`, but I want something which is not allocating.

**Comment by tthsqe12** [comment]
Alright, then `is_fmpq` will simply be a predicate, and `get_fmpq` will actually get it.

**Comment by tthsqe12** [comment]
@thofma This commit 5b07c6d should have everything in the agreed upon form. Let me know if you encounter any problems.
@wbhart Unfortunately the other PR #463 has been sitting there for so long now that there are likely to be conflicts. I would give this PR priority (after @thofma tries it), and I will try to work out the conflicts with the other.

**Comment by thofma** [comment]
Thanks! Somehow the `is_monomial` function went missing.

**Comment by tthsqe12** [comment]
@wbhart This is ready for merge, subject to your approval.

**Comment by tthsqe12** [comment]
@wbhart Could we get this PR merged?

**Comment by thofma** [comment]
That would be nice.

**Pull request merged**
