### PR TITLE
Interface update

### PR DESCRIPTION
**Pull request by tthsqe12**
It turns out the header files had become quite messy.
Now the docs and header files are in sync in the boring range "Memory management" - "Random generation". I have checked all of these functions and corrected some minor issues.
I will add the more interesting range "Basic arithemtic" - "GCD" asap.

### CODE REVIEW

**Comment by wbhart** [comment]
Can I merge this, or do you need to put the arithmetic stuff in the same PR?

**Comment by tthsqe12** [comment]
Don't need to merge yet. I will add the arithmetic functions right now so that the interface is finally complete. Then I will speed them up in a later pr.

**Comment by fredrik-johansson** [comment]
Normally we have pow_ui methods for polynomials; there's not really a reason to have pow_si that just raises for negative exponents.

**Comment by tthsqe12** [comment]
Now, if someone accidentally passes -1 in for the power, it will sit there computing the power to the maximum ulong.

**Comment by fredrik-johansson** [comment]
That's the punishment they deserve!

**Comment by wbhart** [comment]
We did that mainly for interface with Nemo, where integer literals will be Int, hence si. We could add the ui ones, but I find the si ones useful too.

**Comment by wbhart** [comment]
On the other hand, I guess the ui ones would do just as well.,

**Comment by tthsqe12** [comment]
The "change powers to ui" passed travis-cl. If this last one does as well, it is good to go by me.
You now have all of the functions, and the implementation of `fmpz_mpoly_mul` is pure brilliance!

**Comment by tthsqe12** [comment]
there is a warning
`test/t-kronecker_product.c:25:16: warning: ISO C90 forbids mixing declarations and code [-Wdeclaration-after-statement]
    fmpz_mat_t A, B, C;`

**Comment by wbhart** [comment]
That's fantastic! Hopefully we find time this week to make the final changes to Nemo and get this all working there.

**Pull request merged**
