### PR TITLE
Speed up `fmpz_mul_si`

### PR DESCRIPTION
**Pull request by albinahlback**
By running `fmpz/profile/p-mul_si.c`, I got
```
fmpz_mul_si_new min time is 8.770 cycles, max time is 9.621 cycles
fmpz_mul_si_old min time is 13.057 cycles, max time is 15.946 cycles
```
which is a nice speedup.

Let me know if the inlining is not a good idea or whatever, or if perhaps the test results are misleading.

Edit: This was on a Haswell 4770k. Let me know if you get something that does not represent this result.

### CODE REVIEW

**Comment by albinahlback** [comment]
I think very similar speed ups can be made for the other `fmpz` multiplications.

**Review by tthsqe12 — APPROVED** [review]

**Comment by wbhart** [comment]
Can this be done without moving the check for x == 0? This is a sufficiently important case that it should be optimised for.

**Comment by tthsqe12** [comment]
For what its worth, I like this pr *exactly* the way it is.

**Comment by wbhart** [comment]
@tthsqe12 Can you say why it would be good to slow down one of the most important functions in the case it is going to be used the most?

**Comment by albinahlback** [comment]
> Can this be done without moving the check for x == 0? This is a sufficiently important case that it should be optimised for.

Yeah sure, but it makes it faster for when the `fmpz` is an `mpz`. Otherwise this is actually faster.

**Comment by wbhart** [comment]
Ok.

**Pull request merged**
