### PR TITLE
More sqrt

### PR DESCRIPTION
**Pull request by tthsqe12**
@wbhart I would like to ensure that you are happy with my changes before I copy+paste this elsewhere. By the way, your p-sqrt should run about 20% faster now.

### CODE REVIEW

**Comment by wbhart** [comment]
Looks ok. Have you run the random test cases to a high number of iterations to ensure the test code isn't going to randomly bog down?

I think you are right about the exponent overflow checking, at least when random inputs are concerned.

**Comment by tthsqe12** [comment]
yeah, I think I tried 100,000 random inputs

**Comment by wbhart** [comment]
p-sqrt is faster because of the _fmpz_mpoly_submul2_uiuiui_fmpz? Or because of something else?

**Comment by tthsqe12** [comment]
no - on powers 16 through 20, it is all multiprecision, and the fmpz_mul + fmpz_mul_2exp + fmpz_add combo was slow.

**Comment by wbhart** [comment]
Ah ok.

**Comment by wbhart** [comment]
I'm happy with everything then.

**Comment by tthsqe12** [comment]
@wbhart one quick question
for the double here https://github.com/wbhart/flint2/blob/trunk/fmpz_mpoly/sqrt_heap.c#L528
and undo here https://github.com/wbhart/flint2/blob/trunk/fmpz_mpoly/sqrt_heap.c#L835

is this only used for the division here https://github.com/wbhart/flint2/blob/trunk/fmpz_mpoly/sqrt_heap.c#L782
i.e. q_coeff[0] is not read in this loop https://github.com/wbhart/flint2/blob/trunk/fmpz_mpoly/sqrt_heap.c#L657 ?

**Comment by wbhart** [comment]
Yeah I think so. There are only two places where things are put in the heap. One is where j < i in which case q_i, q_{j+1} is put on the heap, i.e. neither is q_0, and the other is q_{i + 1}, q_1, i.e. neither is q_0.

**Comment by tthsqe12** [comment]
@wbhart I am happy with this assuming it passes. I made substantial changes to the small case in fmpz_mpoly_sqrt_heap, so you might want to retry the p-sqrt on your box.

**Comment by wbhart** [comment]
Great, thanks!

**Pull request merged**
