### PR TITLE
Gcd overhaul part2

### PR DESCRIPTION
**Pull request by tthsqe12**
This is not ready just yet. Since it is complicated, I wanted to run it by the CI.

### CODE REVIEW

**Comment by tthsqe12** [comment]
@wbhart The code here is ready to go. However, you will see that there are some functions in fmpz_mpoly/gcd_brown_threaded.c that do not belong there:
(1) The fmpz_crt_... family - This is parallel to the nmod_crt_... family and I would like to keep the interfaces/names parallel too. This is a little problem because there already are fmpz_CRT, fmpz_CRT_ui, and fmpz_multi_CRT_ui and none of these have the correct functionality. So, what about changing my functions to fmpz_multi_crt_... and nmod_poly_multi_crt_...?
(2) The fmpq_get_d was missing and I added a version that works for my purposes.
(3) The fmpq_farey_neighbors functions may or may not be useful in the fmpq module.

**Comment by tthsqe12** [comment]
I'm going to move the fmpq functions out.

**Comment by wbhart** [comment]
Ok, let me know when you have done that and I'll take a look at the PR.

By the way, there is not really any need to open a PR until you are ready for me to have a look at it. It's not time consuming for me to look at PR's now, as almost all of your code is perfect.

**Comment by tthsqe12** [comment]
This is good now, assuming it passes. The only thing you might not like is that fmpq_farey_neighbors supports no aliasing. I could fix this if this is not acceptable.

**Comment by tthsqe12** [comment]
I'm going to change farey_neighbors to make it more useful.

**Comment by tthsqe12** [comment]
I am done with this now.

**Comment by wbhart** [comment]
This looks ok, but I notice you have code for handling aliasing that looks like it is for handling aliasing of the numerator and denominator. Is that correct?

If so, this is not needed. I guess it is not documented, but the numerator and denominator of an fmpq are not allowed to alias one another. You should be able to make this assumption in all fmpq functions. Or am I missing something here?

**Comment by tthsqe12** [comment]
No, I just make a local copy of the inputs because it is the simplest solution to any aliasing problems. I currently use it with the denominator of the input and Q aliased. I can imagine one might also use it with an output fraction aliased with the input fraction. The current code also doesn't blow up if the two outputs are aliased (they will just both end up as the right).

**Pull request merged**
