### PR TITLE
Fibonacci Polynomials

### PR DESCRIPTION
**Pull request by shivin9**
I think this should encompass all the points which were suggested in the previous pull request.

### CODE REVIEW

**Comment by wbhart** [comment]
Pretty close. There is only this:

* each function should be individually documented. Just putting the prototype for the underscore function in the docs is not enough. It has a different interface to the underscore function and different parameter names.

**Comment by shivin9** [comment]
done...

**Comment by wbhart** [comment]
Thank you for this contribution. Everything passes here and there are no further comments, so I will merge this now.

**Comment by shivin9** [comment]
thanks for your guidance!

**Pull request merged**
