### PR TITLE
Composition with linear functions using taylor shift

### PR DESCRIPTION
**Pull request by shivin9**
Aliasing issues fixed.

### CODE REVIEW

**Comment by wbhart** [comment]
Congrats on fixing the aliasing issues. However the pull request now only contains one commit (the latest). You surely intended to add this to your other commits.

**Comment by shivin9** [comment]
I think this is it. It has all the changes I wanted...
Do the profiling and the testing code need changes corresponding to this change?

**Comment by wbhart** [comment]
So were you able to confirm that this is faster than what we already had?

Also, did you compare with something direct, using the Horner's method or the other O(n^2) method we discussed? Which was faster and what was the comparison?

**Comment by shivin9** [comment]
There are significant but constant time reductions b/w the cases when the original compose() function is called the case where taylor_series() function is called.

**Comment by shivin9** [comment]
linear compose
compose function

The first plot shows the time taken by the current implementation vs the time taken by the taylor_shift function for composing random polynomials of which the 2nd one can be a constant or linear.

The second plot shows the time taken by the compose function with and without the taylor_shift implementation for composing linear polynomials on random polynomials.
Note that both the graphs overlap for most of the time and the newer implementation is faster only in the cases where poly2 is a linear polynomial.

**Comment by fredrik-johansson** [comment]
This should be done in the underscore method.

In fact, I just implemented special-casing of `a*x^n + c` in Arb. You can compare here and perhaps do it similarly for fmpz_poly: https://github.com/fredrik-johansson/arb/blob/master/arb_poly/compose.c

**Comment by shivin9** [comment]
Hi Fredrik,
I had planned to do that only but the problem is that the fmpz_poly_taylor_shift function takes in polynomials and not coefficients. Since I didn't want to change the interface of the underscore function I did it his way. 
Other way could be to send coefficients and make polynomials in the underscore function to be passed to the taylor_shift but I dont know how to initialize a polynomial with a predefined coeffs array.

**Comment by fredrik-johansson** [comment]
You should call _fmpz_poly_taylor_shift from the underscore function, not fmpz_poly_taylor_shift.

**Comment by shivin9** [comment]
I have moved the len==2 case inside the underscore function.

**Comment by wbhart** [comment]
I'm not sure how this is passing the test suite. There used to be a len1 == 1 case, but this has now become len1 == 2. All it does is set the constant coefficient of the output to that of the constant coefficient of poly1.

My guess is the test code is not testing the case where len1 == 2 and len2 > 0 where there is no aliasing for some reason. Perhaps you could see why the test code isn't finding this issue and then fix the test code and then the issue.

**Comment by shivin9** [comment]
Yeah It had got accidentally changed. Actually the ordering of if-else conditions was wrong. It was checking len1<=4 before len1==2(which was accidentally changed) and was thus never executing.
I have fixed this now.

**Comment by fredrik-johansson** [comment]
You don't need to allocate any of that temporary space. _fmpz_poly_taylor_shift works in-place and the inputs cannot be aliased in _fmpz_poly_compose.

**Comment by wbhart** [comment]
Since the non-underscore function takes care of aliasing, I don't think the underscore function needs to. Therefore neither c0 or c1 seem necessary to me.

**Comment by fredrik-johansson** [comment]
I would also optimize the last loop for c1 = +/- 1 (no need for temp in this case).

**Comment by shivin9** [comment]
Actually did thought of that but then assumed that it would've been taken cared of in the fmpz_mul function... But nevertheless we can save the redundant function calls to fmpz_mul if c1 = +/- 1.

**Comment by wbhart** [comment]
Saving the use of temp in that case might be worth more than the function
call overhead, since it saves memory allocation which is expensive. The
fmpz_init/clear combination won't cost much since a GMP integer is never
allocated, but as soon as you use temp, it might allocate one. Anyway it's
almost certainly worth making this optimisation.

It would be interesting to see the timings comparison with what was
originally there after you make all those changes.

**Comment by shivin9** [comment]
I have re-placed temp inside the else branch so that it is allocated only if c = +/- 1
I'll upload the graphs in a while...

**Comment by wbhart** [comment]
There is a function fmpz_is_pm1 to check if it is +/- 1.

**Comment by shivin9** [comment]
@wbhart 
Is there any issue still remaining?

**Comment by wbhart** [comment]
I was just waiting for the graphs you said you were going to upload.

**Comment by wbhart** [comment]
Also in one of the branches of the inner if statement you clear temp without ever initialising it (you don't need to do either in that branch). Also, why not move the return outside the if statement.

**Comment by fredrik-johansson** [comment]
It doesn't seem to be correct when the leading coefficient is -1. Make sure that this case is tested.

**Comment by shivin9** [comment]
Hi Bill,
I will make the required changes... I have implemented the other algorithm also and it seems that the Taylor coefficient method is performing better. I will upload the graphs shortly.

**Comment by wbhart** [comment]
We should look at the other implementation too, so we can optimise it.
Perhaps it is more efficient when fully optimised.

Bill.

**Comment by shivin9** [comment]
taylorvsnew
The other implementation vs the taylor coefficient implementation.
The code goes as following:
else if(len2 == 2)
{
        slong i;
        /*temp will store the powers of the polynomial (x+c)^k*/
        fmpz * temp = _fmpz_vec_init(len1 + 1);
        fmpz * term = _fmpz_vec_init(len1 + 1);
        fmpz * temp1 = _fmpz_vec_init(len1 + 1);
        fmpz_one(temp);
        for (i = 0; i < len1; i++)
        {
            /*summation of term polynomials is the result*/
            _fmpz_vec_scalar_mul_fmpz(term, temp, len1 + 1, poly1 + i);
            _fmpz_poly_add(res, res, len1, term, len1);
            /*temp stores the powers of (ax-b)*/
            /*fast multiplication with (ax-b) using left shift and addition*/
            _fmpz_poly_shift_left(temp1, temp, len1, 1);
            _fmpz_vec_scalar_mul_fmpz(temp1, temp1, len1, poly2 + 1);
            _fmpz_vec_scalar_mul_fmpz(temp, temp, len1, poly2);
            _fmpz_poly_add(temp, temp1, len1, temp, len1);
        }
        _fmpz_vec_clear(temp, len1);
        _fmpz_vec_clear(temp1, len1);
        _fmpz_vec_clear(term, len1);
        return;
}

**Comment by fredrik-johansson** [comment]
It's not quite clear what the plot is showing. Could you show how timings vary depending on len1, assuming that poly2 is fixed?

I have a hard time believing that the code above is faster, as performs 5 * len1 additions or multiplications whereas _fmpz_poly_taylor_shift_horner performs 0.5 * len1 fused addmuls.

**Comment by wbhart** [comment]
You should be able to write this code with two scalar_addmuls and get rid
of at least one of the temporary vectors you allocate.

Also, on the last iteration it appears there is some wasted computation.
You can probably rearrange it so that it doesn't do any unnecessary
computation at the end.

**Comment by shivin9** [comment]
Hi Fredrik,
The code which I posted is not faster(sorry for confusion because of the graph) than the compose function using  _fmpz_poly_taylor_shift_horner.
Can you please tell how can I create a random polynomial of a fixed length. fmpz_poly_randtest creates polynomials whose length is variable.

Thanks
Shivin

**Comment by fredrik-johansson** [comment]
Good question: there is currently no function to do so conveniently. One way is to try creating random polynomials in a loop until the length is the intended value. Or you can set each coefficient to a randomly generated fmpz.

**Comment by shivin9** [comment]
test1

Hi Fredrik,

Here is the updated graphs. Surprisingly the new approach(calculating (x-c)^k for all k performs the worst). I am yet to make the final optimizations and corrections for taylor coefficient implementation and the new compose method. I will commit it by tomorrow.

Thanks
Shivin

**Comment by shivin9** [comment]
opt_new_implementaion

Hi Bill,
This is the new implementation with the changes you suggested. It has brought down the time considerably as instead of computing (ax+b)^k (by multiplying (ax+b)^k-1 with (ax+b)) in each step, I have computed the result as res_i = (res_i + poly1_(len1-i))*(ax+b). Multiplication with linear polynomial g(x) is again done as (f(x)<<1)*a + f(x)*b. The code is as follows:

```
else if (len2 == 2)
    {
        slong i;
        fmpz * temp1 = _fmpz_vec_init(len1+1);
        for (i = len1 - 1; i > 0; i--)
        {
            /* res_i = (res_i + c_(len1-i))*(poly2) */
            _fmpz_poly_shift_left(temp1, res, len1, 1);
            _fmpz_vec_scalar_mul_fmpz(temp1, temp1, len1, poly2 + 1);
            _fmpz_vec_scalar_mul_fmpz(res, res, len1, poly2);
            _fmpz_poly_add(res, temp1, len1, res, len1);
            _fmpz_vec_scalar_mul_fmpz(temp1, poly2, len2, poly1 + i);
            _fmpz_poly_add(res, res, len1, temp1, len2);     
        }

        _fmpz_poly_add(res, res, len1, poly1, 1);
        _fmpz_vec_clear(temp1, len1);     
        return;    
    }
```

**Comment by wbhart** [comment]
This looks better. But is it not possible to use scalar_addmul instead of
scalar_mul then add?

Bill.

**Comment by shivin9** [comment]
I don't think it is possible as scalar_addmul can be used only if we want to do res = res + c*temp.
In this approach we want to do res = (res + c_i)*temp. Here res has to be multiplied with temp also.
scalar_addmul can be used but then I would to use an extra variable to store the value of res and add it later after multiplying with temp.

Shivin

**Comment by wbhart** [comment]
I was talking about the last two lines of the loop, which looks like res =
res + poly2*poly1[i].

**Comment by shivin9** [comment]
final
There is minor change but not much... In fact performance for large poly1's seems to have deteriorated.

Shivin

**Comment by wbhart** [comment]
OK, so it looks like we just switch to the taylor shift implementation that you have in the pull request and not bother with the new implementation, since that is not faster. Thanks for testing that for us.

The only thing remaining now is the comment of Fredrik regarding polynomials with leading coefficient -1. Can you modify the test code to make sure it tests this and then check that your code still passes. Then assuming it has not slowed down too much, we will merge it.

**Comment by shivin9** [comment]
wait I'll remove the binaries which have been accidentally committed.

**Comment by shivin9** [comment]
All the tests are passing and I have made the corrections.
When the leading coefficient of poly2 is -1, it just flips the signs of res and if it is 1 the function just returns. I all other cases, the coefficients are adjusted accordingly.

Shivin

**Comment by wbhart** [comment]
OK I see the corrections. So there are four remaining things I can see:

* there is an "if" that is missing a space before it
* there is a "+=" that should have a space before and after it
* there is a comment referring to "c1" even though there is no such variable
* the test code should have a new test added which does lots of tests for the case you have optimised, i.e. where the inner polynomial has length 2

**Comment by shivin9** [comment]
@wbhart  is something still missing?

**Comment by wbhart** [comment]
This looks good now. I will merge it.

Note that you always have to make a comment on the PR when you make a change, otherwise I don't know that you are done. I only get email notifications when an actually comment has been added to the conversation, not when the PR itself changes.

**Comment by shivin9** [comment]
Thanks Bill and Fredrik for guiding me through this merge. I learned quite a lot while implementing this method.

**Pull request merged**
