### PR TITLE
Changes to CMake files to allow MPIR replacement and require C11/C++11 standard

### PR DESCRIPTION
**Pull request by mahrud**
These changes are limited to CMakeLists.txt and the CMake directory. I'm not sure if they were considered and rejected or not, but I thought I'd submit the PR as a suggestion just in case.

cc: @isuruf, @deinst.

### CODE REVIEW

**Comment by isuruf** [comment]
I don't think we want to directly support mpir. the `configure` build also relies on the fact that `mpir` is built with `gmp` compatibility. Is MPIR not found if built with gmp compatibility mode?

**Comment by mahrud** [comment]
Fair enough. The main reason I made it explicit was that I needed to add a required version.

**Comment by wbhart** [comment]
Flint currently requires compilation with -ansi on the C side and is a C90 project. Requiring C11 may give people the impression that we would accept patches that make use of C11 features, which we don't.

I have no opinion about the C++ side, since it only affects the NTL interface and the C++ wrapper (the latter doesn't really make much use of newer C++ features as far as I know). Either way I don't think that will matter much.

**Comment by wbhart** [comment]
In any case, I don't think we can specify a C++ standard, since they change it (apparently incompatibly from a binary standpoint) every few years. So we just pick a number that works, until it doesn't.

**Comment by mahrud** [comment]
Thank you for the explanation. I'll close the PR. Feel free to incorporate the `Find*.cmake` modules later on if needed.

**Pull request closed without merging**
