### PR TITLE
implement shifted Legendre polynomials \tilde{P_n}(x)

### PR DESCRIPTION
**Pull request by rwst**

### CODE REVIEW

**Comment by wbhart** [comment]
The documentation for the underscore function is wrong. You say poly instead of coeffs. Also you should say what values of n are supported.

Perhaps you could check the other polynomial functions you've implemented so far to see if the same comments apply.

**Comment by rwst** [comment]
I'm not sure what you mean with "say what values of n are supported". That ```n``` is ```ulong``` is the best way to tell ```n>0```, and I cannot find an upper limit given to any of the other functions.

**Comment by wbhart** [comment]
n = 0 is a valid ulong, so you should say "for n > 0" or something like
this.

You can also do

FLINT_ASSERT(n > 0);

as the first line of the (internal) function (after any variable
declarations) if you like. The asserts are only turned on when the user
requests them, so this won't slow anything down for a standard build. These
are not used widely yet, but we are starting to roll them out across Flint.

Bill.

**Comment by rwst** [comment]
That was a typo, ```n==0``` is a valid input, so ulong is fine.

**Comment by wbhart** [comment]
I still think that if you don't specify n >= 0 then the reader of the
documentation may just wonder whether you forgot to denote the range or
whether it works for all ulongs. I realise not all the documentation is so
careful in Flint, but we are moving towards better documentation. I've done
a lot of work rewriting documentation for some of the ulong_extras module,
for example, in my flint-3.0 branch.

You are right in not giving an upper limit, since this depends on how much
memory the machine has. I guess there's a hard upper limit of 2^44 or
something like that, with modern architectures. But this does depend on the
architecture, so is not a useful number to have.

Bill.

**Pull request merged**
