### PR TITLE
Fix mpfr directory and bump mpir version to 2.7.2. for appveyor

### PR DESCRIPTION
**Pull request by thofma**
Lets see if this makes appveyor happy.

### CODE REVIEW

**Comment by isuruf** [comment]
I also tried this, but appveyor has a new sed version now and the new sed doesn't like `mpir-2.7.2`'s syntax. So, I tried upgrading to `mpir-3.0.0`, but that failed, https://github.com/wbhart/flint2/issues/338

**Comment by isuruf** [comment]
Looks like the new sed just gives out warnings now.

**Comment by thofma** [comment]
Yeah, I now remember that I fixed the sed thing for mpir 3.0.0. Hmm. I guess we cannot pin an old sed version?

**Comment by isuruf** [comment]
Looks like the sed version is okay. There's a bug in 32 bit `fmpz_mpoly` code that is fixed in `fmpz_mpoly` branch

**Comment by wbhart** [comment]
The only thing holding up the merging is the lack of docs and tests for the mpoly directory. Someone volunteered to do it, but I think they forgot. I might have to do it.

**Comment by wbhart** [comment]
On the other hand, there were no tests for fmpz_mpoly in trunk, so I'm surprised it was failing.

**Comment by isuruf** [comment]
It's the library itself that fails to compile, not the tests. [This line](https://github.com/wbhart/flint2/blob/trunk/fmpz_mpoly/set_monomial.c#L407) is the culprit.

**Comment by wbhart** [comment]
Ah, I see, thanks. I probably have some time today, if my laptop battery
holds out. I might be able to knock out some test and docs. There's also a
handful of code comments in the fmpz_mpoly directory which need updating.

**Comment by wbhart** [comment]
This won't get done today. I've started on it, but had many interruptions
and only just got the main functions in mpoly documented. Daniel is going
to write test code over the next few days, so that this is done before our
meeting next week.

**Comment by thofma** [comment]
The changes here are independent of the fmpz_mpoly branch.

**Pull request merged**
