### PR TITLE
don't do a temp allocation for each variable in mpoly_get_str_pretty

### PR DESCRIPTION
**Pull request by fredrik-johansson**
Fixes crash when printing a polynomial in 10^6 variables.

### CODE REVIEW

**Comment by tthsqe12** [comment]
The fprint_pretty functions probably have the same problem.
However, I have to admit that I don't see why the fprint_pretty functions can just call the get_string functions and then dump the string. @wbhart

**Comment by fredrik-johansson** [comment]
> The fprint_pretty functions probably have the same problem. However, I have to admit that I don't see why the fprint_pretty functions can't just call the get_string functions and then dump the string.

Ah, I thought that's what they already did!

I suppose if you have some truly enormous polynomial that you want to dump to a file, you might want to avoid making an extra copy of the whole string in memory. I can patch the fprint_pretty methods either way (same fix, or replace with get_str wrappers). Do you have a preference?

**Comment by tthsqe12** [comment]
I would just replace the printf functions by wrappers around get_str_pretty unless @wbhart objects.

**Comment by wbhart** [comment]
Aren't most of them already wrappers around the fprint functions? You certainly don't want to convert to a string in memory before writing to a file.

**Comment by tthsqe12** [comment]
> You certainly don't want to convert to a string in memory before writing to a file.
Why?

**Comment by wbhart** [comment]
Well, I was just thinking that perhaps the string representation doesn't fit in memory, or memory is tight and that's why you are writing it to disk in the first place.

**Pull request merged**
