### PR TITLE
Changes in n_is_prime_pocklington

### PR DESCRIPTION
**Pull request by kush789**

### CODE REVIEW

**Comment by wbhart** [comment]
Thanks, this looks correct now.

**Comment by fredrik-johansson** [comment]
Shouldn't the limit be different on a 32 bit machine? Or is this not relevant on 32 bit?

**Comment by wbhart** [comment]
Yes, I think you are right. Well spotted.

**Comment by kush789** [comment]
Hi, 

What do you suggest would be better, to use #if to check for FLINT64 and change the upper bound on limit accordingly, or to add 1 unconditionally while calculating the limit?

Simply adding 1 to the limit unconditionally when calculating the cube root would make sure that limit^3 is always grater than (n-1) for all 32 bit numbers at least (I checked whether (pow(x, 1.0/3) + 1)^3 > x) for x till 2^32 as you mentioned earlier). However it will not be true for bigger numbers (typecasting). Hence the check to increment limit should still be there. A 32 bit number would simply not enter that loop.

**Comment by wbhart** [comment]
No I think we had better not make any assumptions about pow on anyone's
machine.

I think the #if FLINT64 with different code for 32 and 64 bits is the best
way to go.

**Pull request merged**
