### PR TITLE
add nmod_poly_crt_t

### PR DESCRIPTION
**Pull request by tthsqe12**
@wbhart unfortunately I need this function and it seems to be missing from flint. The test code is good and it should do the same as the function in hecke.

### CODE REVIEW

**Comment by fredrik-johansson** [comment]
The interface looks rather convoluted.

**Comment by tthsqe12** [comment]
How could the interface be improved?

**Comment by tthsqe12** [comment]
How about now? (the underscore version is the one you will actually want to use)

**Comment by wbhart** [comment]
@tthsqe12 Could you add some comments to the fields of the structs to explain what they are for, and perhaps a note before the structs explaining the overall purpose of the structs (in particular what a prog is).

**Comment by tthsqe12** [comment]
done

**Comment by fredrik-johansson** [comment]
I guess my immediate concern is that the interface differs from fmpz_multi_CRT_ui, not that I particularly like that interface.

nmod_poly_crt_t has essentially the same purpose as fmpz_comb_t, right?

Why the separate nmod_poly_crt_init and nmod_poly_crt_compile functions?

It is not explained in the documentation under what conditions nmod_poly_crt_compile could be unsuccessful.

Is compiling a program not overkill here? What is the advantage over a simple recursive implementation?

**Comment by tthsqe12** [comment]
Init and compile are separate so that you can recompile the same object with different moduli if you want. Compilation will succeed iff (1) there is onlly one nonzero modulus, or (2) there are at least two moduli, all of degree > 0, and pairwise r.p., which I will put in the docs. Not compiling means that the run function will have to be more complicated. The compiler currently tries to balance the multiplications, and this needs to be stored in the object somehow.

**Comment by tthsqe12** [comment]
@fredrik-johansson I now see that the `fmpz_comb_init` is very convoluted too. At least the writer of that class and I both foresaw that you might not want the `nmod_poly_crt_run` (or `fmpz_multi_CRT_ui`) function to be allocating its own temporaries each time it is called. Hecke provides a non-solution to this problem by storing all temporaries in the class object itself. Maybe the `fmpz_comb_t` needs a rewriting - esp. the part about the list of moduli being required by the `fmpz_comb_t` throughout its life time.

**Comment by fredrik-johansson** [comment]
I think even the temporary preallocation is unnecessary. The way I would do it now is just with recursive divide-in-half calls down to length n = 20 or so where the code can switch over to an iterative basecase algorithm. The memory allocation overhead should be negligible if the basecase code uses stack space. Note that for fmpz CRTing I already implemented basecase code in fmpz_mat/mul_multi_mod (as a temp fix to speed up fmpz_mat_mul), but I did not get around to rewriting fmpz_multi_CRT_ui to combine this basecase code with divide-and-conquer.

**Comment by tthsqe12** [comment]
> The memory allocation overhead should be negligible if the basecase code uses stack space.
I do not expect the `coeffs` member of an `nmod_poly_t` to point to stack space.

We might be talking at slight cross-purposes here. The current compile function uses about `2 + log2(moduli_length)` number of temporaries. Each of this temporaries is an `nmod_poly_t` with an uncontrollable member `coeffs` allocated in the heap by the `nmod_poly` functions.

**Comment by fredrik-johansson** [comment]
Things don't look fundamentally different for nmod_polys; the necessary temporary space should basically be the sum of lengths of the moduli in each branch of the tree (so not at all uncontrollable).

**Comment by fredrik-johansson** [comment]
That is, if you do it with underscore nmod_poly methods.

**Comment by fredrik-johansson** [comment]
In fact nmod_poly_interpolate_nmod_vec_fast solves the same problem for the special case of linear factors, although it uses the bottom-up algorithm with extension to a power-of-two length (like fmpz_multi_CRT_ui) instead of the simpler (and probably more efficient) recursive algorithm with an iterative basecase.

**Comment by tthsqe12** [comment]
So you are proposing special code for combining moduli `m1,...,mn` when `deg(m1) + ... + deg(mn) < 20`, say. Is this code going to do anything fundamentally different than the `A = B + I*(C-B) mod M`? Are you going to add the assumption that the inputs have degrees strictly less than the corresponding moduli so that we really do have a bound on the problem size in this case?
Can we agree the the current interface (non underscore) is good and supports such future changes under the hood?

**Comment by fredrik-johansson** [comment]
The outputs are erroneously marked as const, and they should come before the const nmod_poly_crt_t P in the argument list. Also, I think the type should be "const nmod_poly_struct * inputs", not "nmod_poly_struct * const * inputs" (this is the convention elsewhere in the library).


I think the public interface I'd like to see is something like this:

    void nmod_poly_crt_init(nmod_poly_crt_t CRT)

    int nmod_poly_crt_precompute(nmod_poly_crt CRT, const nmod_poly_struct * moduli, slong len)

    void nmod_poly_crt_clear(nmod_poly_crt_t CRT)



    void nmod_poly_crt_precomp(nmod_poly_t output, const nmod_poly_crt_t CRT, const nmod_poly_struct * values)

        (Runs CRT given precomputed CRT object.)

    int nmod_poly_crt(nmod_poly_t output, const nmod_poly_struct * moduli, const nmod_poly_struct * values, slong len)

        (Simple wrapper that creates and throws away CRT object.)


...with any other functions taking preallocated memory marked with underscores with the understanding that they might be obsoleted in the future. Alternatively, have an nmod_poly_crt_temp_t type (in analogy with fmpz_comb_temp_t) for temporary space instead of the naked array of polynomials, in anticipation of future changes to the algorithm. However, I really do think that it's better design to avoid interfaces where the user provides temp space. In an optimised implementation, temporary allocations should be cheap (using stack space for short CRTs), and asking the user to provide temp space is a bit of a lazy workaround for unoptimised code.

We are not very consistent about words like precompute/precomp/build, so I'm not particular about that, but there is no precedent for compile/run (just a very minor thing).

**Comment by tthsqe12** [comment]
So then you do not want julia users to use this interface (or any other hll)?

**Comment by fredrik-johansson** [comment]
What part of the interface? Using temp space? Yes, I think it's an implementation detail that is better left out.

**Comment by tthsqe12** [comment]
By passing `moduli` and `values` as `nmod_poly_struct * ` you are asking the user to copy the moduli and values into a flat array of nmod_poly structs before calling the functions. I believe julia doesn't support this.

**Comment by fredrik-johansson** [comment]
`nmod_poly_struct *` is to `nmod_poly_t` as `fmpz *` is to `fmpz_t`. If a vector of ``nmod_poly`` objects in Julia is  stored differently, then yes, we would have to create a copy in Julia (which could be shallow) for the C call.

**Comment by tthsqe12** [comment]
Ok. The nmod_poly's that I want to pass to the crt also do not exist contiguously in memory, so you are asking to me make a shallow copy of the nmod_poly_struct's every time I call this too.

**Comment by tthsqe12** [comment]
The original marking of the outputs as `nmod_poly_struct * const *` was not an error because the function should _not_ move the struct that it is modifying. The inputs should have been marked `const nmod_poly_struct * const *` but this creates difficulties as C can't automatically cast to this from `nmod_poly_struct **`. This is one of the limitations C has compared with C++.

**Comment by wbhart** [comment]
Yes, unfortunately in Julia an nmod_poly_struct is really a pointer to such, as it is a heap allocated object. That means you need a double pointer on the C side. But the other option would be to make a simple C function for constructing an nmod_poly_struct * one poly at a time and then calling this from Julia.

I can see why Fredrik would like to keep the C interface nice and simple, as this is a pretty important set of functions.

**Comment by wbhart** [comment]
Whatever C functions you write for handling the shallow copy, you can put in the inlines.c file, as they have no use elsewhere. No need to document or test them then, except from Nemo of course.

**Comment by tthsqe12** [comment]
@wbhart why does the `fmpz_comb_init` require each of the source primes to have exactly `FLINT_BITS - 1` bits? Why can't they be arbitrary word-sized primes?

**Comment by wbhart** [comment]
I don't recall, but presumably this was just to maximise efficiency.

**Comment by fredrik-johansson** [comment]
I don't know why the documentation says that because the code actually makes no such assumptions (as far as I can tell).

**Comment by tthsqe12** [comment]
Ok. I will soon find out if the FLINT_BITS - 1 is an actual requirement.

**Pull request closed without merging**
