### PR TITLE
change fq_nmod typedef

### PR DESCRIPTION
**Pull request by tthsqe12**
This first commit is the smallest possible to get fq_nmod_t = nmod_polydr_t. There is now a nmod_ctx_t for these nmod_polydr_t's. If you don't like how I have changed nmod_poly/mul.c ect, then the nmod_poly_t will have to be changed to be able to reuse the code there.

### CODE REVIEW

**Comment by tthsqe12** [comment]
@wbhart 
If we have
```
typedef struct {
    nmod_t mod;
} nmod_ctx_struct;

typedef struct {
    mp_ptr coeffs;
    slong alloc;
    slong length;
} nmod_polydr_struct;

typedef struct {
    mp_ptr coeffs;
    slong alloc;
    slong length;
    nmod_t mod;
} nmod_poly_struct
```
are the following pointer casts guaranteed to work as we would like?
```
nmod_polydr_struct * nmod_poly_poly(nmod_poly_t a) {return (nmod_polydr_struct *)(&a->coeffs);}
nmod_ctx_struct * nmod_poly_ctx(nmod_poly_t a) {return (nmod_ctx_struct *)(&a->mod);}
```

**Comment by tthsqe12** [comment]
The evil pointer casts might pass, but I'm fairly sure it is undefined c. The only other solution is
 ```
typedef struct {
    nmod_polydr_t poly;
    nmod_ctx_t ctx;
} nmod_poly_struct
```
@wbhart is this acceptable for flint? Is there a reason flint doesn't have a tradition of nesting structures? I can remember wanting to get a constant ref to the numerator of a fmpq_poly and being unable to do so without copying members.

**Comment by tthsqe12** [comment]
@wbhart I would like to know I may continue with the replacing nmod_poly_struct by
```
typedef struct {
   nmod_polydr_t poly;
   nmod_ctx_t ctx;
} nmod_poly_struct
```
or
```
typedef struct {
   nmod_polydr_t poly;
   nmod_t mod;
} nmod_poly_struct
```

Either one would allow a large portion of the nmod_poly interface to be implemented in terms of nmod_polydr. This is only possible with current nmod_poly_t using undefined pointer casts.

**Comment by tthsqe12** [comment]
@wbhart is it ok to replace the members coeffs, length, and alloc of the current nmod_poly_struct by an nmod_polydr_t? This would entail putting ->poly in all of the uses of nmod_poly's, which I am prepared to do.

**Comment by fredrik-johansson** [comment]
Doing so will certainly break external code.

Why not just make it a separate type and duplicate the handful non-underscore methods that are strictly needed?

What is the meaning of "dr" by the way?

To be honest, I don't really see changing the nmod_poly type being worth the extra code and potential breakage. (I agree that removing the context data would be the cleaner design starting from scratch.) You could have a method that changes the modulus of an existing nmod_poly_struct in places where you want to use multiple moduli.

The space overhead of storing two redundant words in each nmod_poly_t is 1.67x for representing the zero polynomial without allocation and 1.5x for a constant polynomial with one malloced word, assuming that malloc has zero overhead. Not insignificant, but not critical either, and it pales compared to other data-packing optimizations we're not doing anyway.

**Comment by tthsqe12** [comment]
So I should not touch the nmod_poly_struct and I should simply duplicate the non-underscored functions? When I want to use multiple moduli, I will be using the nmod_polydr_t (nmod_poly's done right).

**Comment by tthsqe12** [comment]
@wbhart do you have any thoughts?

**Comment by wbhart** [comment]
I guess people probably do rely on the struct members not changing (possibly including us in Nemo). Fredrik is right.

It looks like there will have to be some duplication somewhere. It's not pretty, for sure. How many functions will you need?

**Pull request closed without merging**
