### PR TITLE
Use ftp.gnu.org link to download mpfr

### PR DESCRIPTION
**Pull request by isuruf**
This link is stable and the mpfr.org link is not

### CODE REVIEW

**Comment by wbhart** [comment]
So we switch it back to ftp.gnu.org.

We previously used that but it proved unreliable.

**Comment by wbhart** [comment]
Actually, the latest version is 4.0.1, not 4.0.0.

**Comment by isuruf** [comment]
> We previously used that but it proved unreliable.

Did not know that. Do you want to keep mpfr.org or switch back to gnu.org?

**Comment by wbhart** [comment]
We can switch again and see how it goes. It was a long while back that they had problems with their site all the time.

**Comment by dimpase** [comment]
Why not github? One can make releases and add "binary assets" to them, i.e. one can add a properly named tarball with everything needed for `./configure && make` there.

**Comment by wbhart** [comment]
I don't think they develop on GitHub, do they? And I'm not sure they would appreciate us "forking" their project (even though that would not be the intention, people are likely to make pull requests and make bug reports there).

**Comment by dimpase** [comment]
> I don't think they develop on GitHub
indeed, I wasn't thinking straight (spending days fighting a combo of mpfr+mpc+flint+ntl doesn't help :-))

By the way, the current mpfr is 4.0.2.

**Pull request closed without merging**
