### PR TITLE
Evaluation

### PR DESCRIPTION
**Pull request by tthsqe12**
The
`(X + c) < X is false`
warning was triggering for a condition of the form
`n == L && n + 1 < L`.

I changed it to
`max(n+1, L) < L`
and my compiler no longer warns. Even though this new condition is also provably always false, the compiler doesn't generate any warnings (it also is unaware that the condition is always false).

Let me know if your compiler is smarter!

### CODE REVIEW

**Comment by wbhart** [comment]
Is the evaluation branch ready to merge? Or are you just fixing the compiler warning here?

**Comment by tthsqe12** [comment]
I had accidentally tried to open the PR on the trunk branch. Yes - I just committed the workaround right before committing the evaluation.

**Comment by wbhart** [comment]
Regarding the code, profiler.h and assert.h shouldn't be #included. The former should only be included from profile functions (in profile subdirs) and instead of using assert, you should use FLINT_ASSERT.

Also, is there any value to calling assert in the test code, instead of printing fail and aborting?

It looks like the docs for fmpz_mpoly_evaluate_all_fmpz_straight are missing.

Are you planning a fmpz_mpoly_evaluate_all function which chooses the algorithm based on some cutoff?

I'm a little worried by the names straight and tree. I guess tree is ok, since this is not just Horner's. But straight is not very clear to me what it might be doing. 

I am also thinking the fmpz might be supposed to come after straight or tree to keep with our naming conventions, but I can't actually think of an example at the moment. Perhaps @fredrik-johansson has a preference here?

**Comment by wbhart** [comment]
Yes, I just checked and the fmpz should definitely come last in the name. Consider for example fmpz_poly_evaluate_horner_fmpz.

**Comment by tthsqe12** [comment]
I am just going to dump the eval_straight. This tree is faster in all random examples I tried.

**Comment by wbhart** [comment]
Yeah that's fair enough. It's committed if we ever need it back.

**Pull request merged**
