### PR TITLE
minpoly functions in fmpz_mod_poly

### PR DESCRIPTION
**Pull request by dsroche**
I remember a brief discussion sometime last year of someone wanting a Berlekam/Massey algorithm in FLINT. Since I also need this for a different purpose now, I decided to write it.

The problem is, given a linearly recurrent sequence of integers modulo p, find a minimal generator for the linear recurrence.

I called the functions "fmpz_mod_poly_minpoly..." because Berlekamp/Massey is just one algorithm for this problem. I also wrote two other implementations, one with a Euclidean algorithm and one using half-gcd. As expected, the Euclidean algorithm was never fastest so it's not included in this pull request.

Test file and docs included. I also did some profiling to determine the crossover point at least on my machine, which has a fairly common Intel 64-bit processor. This is incorporated into the generic fmpz_mod_poly_minpoly functions.

### CODE REVIEW

**Comment by wbhart** [comment]
Thanks very much for this. It seems to be passing for me and it is certainly needed. I will try to review it before merging it, which might take me a few days, but it shouldn't take long.

**Comment by wbhart** [comment]
Sorry it took me so long to look at this. It looks fine, but could I request one small change.

In the two implementations of minpoly (both bm and hgcd), could you put spaces before and after +, -, = and < throughout. This is a convention we use in Flint.

**Comment by dsroche** [comment]
Thanks Bill. I fixed the operator spacing (finally!) and also pulled to keep up to date with the current trunk.

**Comment by wbhart** [comment]
Thanks Daniel! I'll merge this as soon as Travis CI finishes with testing.

**Pull request merged**
