### PR TITLE
Ecm fix

### PR DESCRIPTION
**Pull request by fieker**

### CODE REVIEW

**Comment by fieker** [comment]
On Thu, Apr 12, 2018 at 02:19:55AM -0700, wbhart wrote:
> Hmm. This has introduced test failures elsewhere. 
> 
All my tests were fine with a clean build. Looking at travis, there is a
setup problem:



    1086.1
        Compiler: gcc Xcode: xcode6.4 C
            no environment variables set 


Which is independent

**Comment by wbhart** [comment]
Yeah the failures are on Appveyor, and they fail because of this fix unfortunately (in gcd tests). I'm not at all sure what could possibly be the problem. This fix shouldn't be breaking anything. I don't recall relying on the broken behaviour of the function. But anything is possible.

**Comment by wbhart** [comment]
Oh wait, I'm sorry. I actually misread the output. The bug is just coincidentally in Daniel's prs_gcd function, not in the fmpz_poly_gcd (which would use this function). I'll let Daniel know he's broken trunk.

**Comment by wbhart** [comment]
We think we know why it's failing. The function mpn_rshift cannot accept a shift of 0. This is due to the actual processor hardware.

Thus we still need to test for b1 = 0 and b2 = 0 and do a copy instead of an mpn_rshift in that case. The function you want is flint_mpn_copyi in that case. It takes one less argument, i.e. no shift value.

mpn_gcd is a very low level assembly function, hence the complicated interface, which is actually documented.

**Pull request merged**
