### PR TITLE
Xxfix3

### PR DESCRIPTION
**Pull request by tthsqe12**
I would not recommend multiplying a fmpz_poly by a double and having the compiler figure out which function to call. The other thing was that the test code for solving was actually wrong.

### CODE REVIEW

**Comment by tthsqe12** [comment]
BTW, I'm sitting on gcc7 and still can't compile t-fmpzxx

**Comment by wbhart** [comment]
This works for me. Thanks. I'm not worried about compilers that hang or crash. That's pretty common with this C++ code. So long as there's not C++ issues.

**Comment by tthsqe12** [comment]
I didn't get to add one final safety measure. Can you add 0.5 like this (because fmpz_set_d truncates):
```
     ltupleref(r, s, d) = pseudo_divrem(g, f);
-    tassert(r*f + s == g*fmpzxx(pow(2, d)));
+    tassert(r*f + s == g*fmpzxx(pow(2, d) + 0.5));
     r = 0; r = 0; d = 0;
     ltupleref(r, s, d) = pseudo_divrem_basecase(g, f);
-    tassert(r*f + s == g*fmpzxx(pow(2, d)));
+    tassert(r*f + s == g*fmpzxx(pow(2, d) + 0.5));
     r = 0; r = 0; d = 0;
     ltupleref(r, s, d) = pseudo_divrem_divconquer(g, f);
-    tassert(r*f + s == g*fmpzxx(pow(2, d)));
+    tassert(r*f + s == g*fmpzxx(pow(2, d) + 0.5));
```

**Comment by wbhart** [comment]
Can you just make a PR. I'll add it to the final release, so long as tests pass for me.

**Comment by tthsqe12** [comment]
ok

**Pull request merged**
