### PR TITLE
fmpz_nextprime and fmpz_randprime

### PR DESCRIPTION
**Pull request by dsroche**
Two functions are added to fmpz.h: nextprime and randprime. They work as you might expect. I wrote tests and documentation for each.

### CODE REVIEW

**Comment by wbhart** [comment]
I had a quick look at this, and actually it all looks pretty good.

There is only one issue I would like to remove, namely the vanishingly rare possibility that it returns a prime with one more bit. I think we should check for this case and keep running until we get a prime of the right size.

Of course this means that it will be illegal to ask for a prime with less than 2 bits.

**Comment by wbhart** [comment]
Actually, I see two other issues:

1) the documentation doesn't say what the return value does or what the proved parameter is for.

2) I think it should actually restart if the primality test fails, and find a prime for which it doesn't fail (I realise this is meaningless for now, but it won't be for long since we have an APR-CL implementation which is nearly ready to merge). This means that the function won't actually return an int value of course.

**Comment by dsroche** [comment]
Hi Bill,

My understanding of your comment (2) is that, if `randprime` is called with `proven=1`, which in turn calls `is_prime`, and the latter returns -1 (no proof of compositeness or primality), then `randprime` should try picking a different prime number, repeatedly until it finds a prime that can be proven so.

I have concerns that this will further skew the distribution of random primes returned which may be important for some applications. For example, if there exists some actual prime `p` for which `fmpz_is_prime(p)` always returns -1, then that `p` will *never* be returned by `randprime`, which I view as a deficiency.

If APR-CL is implemented in Flint, wouldn't that mean that `is_prime` always returns 1 or 0? Then I would prefer to have `randprime` abort in case the prime prover fails with -1, rather than skew the distribution by searching for another prime.

(And whenever a fast prime prover comes in, the abort will never happen.)

Let me know if you disagree with this approach.

As to your other two suggestions (eliminating return values, and making the bit-length a guarantee), I agree and will make those changes.

Thanks,
Dan

**Comment by dsroche** [comment]
I made the updates as per my previous message. Note it looks like the Travis build won't pass because mpfr.org is down since yesterday.

**Comment by wbhart** [comment]
On 15 November 2015 at 21:05, Daniel S. Roche <notifications@github.com>
wrote:

> Hi Bill,
>
> My understanding of your comment (2) is that, if randprime is called with
> proven=1, which in turn calls is_prime, and the latter returns -1 (no
> proof of compositeness or primality), then randprime should try picking a
> different prime number, repeatedly until it finds a prime that can be
> proven so.
>
> I have concerns that this will further skew the distribution of random
> primes returned which may be important for some applications. For example,
> if there exists some actual prime p for which fmpz_is_prime(p) always
> returns -1, then that p will *never* be returned by randprime, which I
> view as a deficiency.
>

Sure, but the intention is that fmpz_is_prime will always succeed at
declaring p either composite or prime. I realise that is not the case
presently, but once we merge the APR-CL code it shouldn't be a problem any
more.

> If APR-CL is implemented in Flint, wouldn't that mean that is_prime
> always returns 1 or 0?
>
Yes.

> Then I would prefer to have randprime abort in case the prime prover
> fails with -1, rather than skew the distribution by searching for another
> prime.
>

-1 being "don't know". Yes, that would be fine.

Currently fmpz_is_prime is pretty useless, since it returns -1 quite a lot.
So it is better that people get a meaningful message rather than think this
just worked, for now.

> (And whenever a fast prime prover comes in, the abort will never happen.)
>
> Let me know if you disagree with this approach.
>
> As to your other two suggestions (eliminating return values, and making
> the bit-length a guarantee), I agree and will make those changes.
>

Thanks.

Bill.

**Comment by wbhart** [comment]
MPFR seems to be down a lot. We might have to switch to using a GNU ftp
server instead of the server mentioned on the MPFR page. It's too
unreliable.

Bill.

**Comment by wbhart** [comment]
This looks great now. I've merged it. I'll now change fmpz_randbits to return an integer with precisely the given number of bits.

**Comment by danaj** [comment]
Already merged, but a few comments.

For nextprime, we can do better (state of the art is 2-4x faster than mpz_nextprime) but that can be handled later.  For the proof, the recursion works but my preference would be a loop.  This case should be highly unlikely (though we're calling a GMP function we have no control over).  I'd like to see documentation mention what method we're using if proved isn't true.

For randprime, I think the documentation needs some discussion of how randomness is generated.  For large integers it looks like we're using GMP's default random generator, so we might want to clarify this is not recommended for crypto use.  I'm not a fan of the PRIMEINC algorithm, but other methods are either more complicated (e.g. Fouque and Tibouchi 2011) or wasteful and slow (the trivial method).  I think using F/T algorithm A1 would be a nice goal for someone.

**Comment by wbhart** [comment]
I agree with some of these comments Dana. I'm just going to open a ticket for them for now, since the right way to fix them is to merge the APR-CL implementation, which I don't have time for probably for a few months. But I want to make sure these are addressed before the next release.

**Pull request merged**
