### PR TITLE
Fix32bugs

### LINKED ISSUE #1024: Bug in nmod_mpoly_factor
Hans Schoenemann reports:

the following bug occurs on 32bit cpus, on 64bit flint works fine:
(found on flint 2.7.1 and 2.8.3, on x86 (flammo) and arm (momo32)):
- nmod_mpoly_factor returns 0
- using factory and gcd ifrom flint and univariate factorization from flint
  does not finish
- using factory and univariate factorization from flint,
  and gcd from factory workd fine
Maybe the problem is in the multivarite gcd over characteristic p.

### PR DESCRIPTION
**Pull request by tthsqe12**
fixes #1024

### CODE REVIEW

**Comment by tthsqe12** [comment]
Each of these four is a bug fix and should go into 2.8.4.

**Comment by wbhart** [comment]
@tthsqe12 Thanks. Do any of these bug fixes affect the 2.8 branch? The PR only applies to trunk. Apparently one of the functions you modified here does not exist on the 2.8 branch (the _try_dense_univar function). Do we need similar fixes on the 2.8 branch?

**Comment by tthsqe12** [comment]
Ah, 2.8 is ancient. Since that helper function was added after 2.8, I guess ec34d00 need not be applied, since it cannot be.

**Comment by wbhart** [comment]
Ok, then I will simply merge the others. It's a shame I squashed the commits in trunk. Now it's gonna be hard to do.

**Pull request merged**
