### PR TITLE
gcd via berlekamp massey

### PR DESCRIPTION
**Pull request by tthsqe12**
This is a good halfway point of the gcd overhaul, and there are two added univariate functions `{fmpz_|n}mod_poly_find_distinct_nonzero_roots`.

### CODE REVIEW

**Comment by tthsqe12** [comment]
@wbhart do you know why the penguin is failing? clang says undefined references to the fmpz_mod functions but they are clearly there.

**Comment by thofma** [comment]
Did you add `fmpz_mod` in `CMakeLists.txt`?

**Comment by tthsqe12** [comment]
no

**Comment by thofma** [comment]
Maybe we need this

**Comment by tthsqe12** [comment]
I have no idea how to track down this segfault. Obviously clang is miscompiling something because the code is perfect :). Seriously though, is it possible to run the checks with asserts on @wbhart ?

**Comment by tthsqe12** [comment]
@wbhart this has been ready to go.

**Comment by isuruf** [comment]
After this PR, there are some failures on MSVC.

```
The following tests FAILED:
	1685 - fmpz_mod-test-t-discrete_log_pohlig_hellman (Exit code 0xc0000409
)
	1686 - fmpz_mod-test-t-divides (Exit code 0xc0000409
)
	1687 - fmpz_mod-test-t-inv (Exit code 0xc0000409
)
	1688 - fmpz_mod-test-t-mul (Exit code 0xc0000409
)
	1690 - fmpz_mod-test-t-pow_fmpz (Exit code 0xc0000409
)
	1691 - fmpz_mod-test-t-pow_ui (Exit code 0xc0000409
)
Errors while running CTest
```

See https://ci.appveyor.com/project/isuruf/flint2/builds/24125241/job/jj3716jaahg3yhjt

https://github.com/wbhart/flint2/commit/18a7acb7444af109ea639d00f605a26048e134d7 doesn't have this issue

**Comment by tthsqe12** [comment]
@isuruf so it fails with `#define mp_bitcnt_t ulong` and passes without this define? Do you have a local msvc?

**Comment by isuruf** [comment]
> so it fails with #define mp_bitcnt_t ulong and passes without this define?

tests passes without this define and without this PR.

> Do you have a local msvc?

No, but I can test on appveyor

**Comment by tthsqe12** [comment]
well, if t-mul fails then everything else is going to fail.
Try making line 136 of fmpz_mod.h look like
```
FMPZ_MOD_INLINE void fmpz_mod_mul(fmpz_t a, const fmpz_t b, const fmpz_t c,
                                                     const fmpz_mod_ctx_t ctx)
{
    /*(ctx->mul_fxn)(a, b, c, ctx);*/
    _fmpz_mod_mulN(a, b, c, ctx);
}
```
This will call the default multiplier _fmpz_mod_mulN since it looks like msvc is breaking _fmpz_mod_mul2.
Does this PR pass with `#define mp_bitcnt_t ulong`?

**Comment by isuruf** [comment]
> Does this PR pass without #define mp_bitcnt_t ulong?

You mean with `#define mp_bitcnt_t ulong`? It doesn't Does this PR pass without #define mp_bitcnt_t ulong?

> Try making line 136 of fmpz_mod.h look like

Do you mind sending a PR to my fork or enable appveyor in yours?

**Comment by tthsqe12** [comment]
You said that 18a7acb doesn't have this issue, so I am wondering if the removal of `#define mp_bitcnt_t ulong` somehow fixed it. I will try something on your branch.

**Comment by isuruf** [comment]
I mean I tried trunk and trunk after reverting 18a7acb. Neither works. Trunk before this PR (i.e. 18a7acb) works.

**Comment by tthsqe12** [comment]
My apologies. I was confused as to the order that bill merged the two PRs.

**Pull request merged**
