### PR TITLE
Add Howell form for fmpz_mat(_mod) and Hermite form module largest elementary divisor

### PR DESCRIPTION
**Pull request by thofma**

### CODE REVIEW

**Comment by wbhart** [comment]
I'm a little bit lazy with this question: is this intended to be Howell form over Z/nZ? Or is it Howell form over Z with computations done modulo n (because you know something about the result)?

**Comment by thofma** [comment]
Sorry, the documentation is misleading. Here is what it does: If B denotes the input and A the output, then A modulo n is the Howell form of B modulo n.

It's similar to fmpz_mat_rref_mod. I just copied the sentence "All computations are done modulo p". But thinking about it, the documentation for fmpz_mat_rref_mod doesn't sound quite right either (or does it?)

I am away for the rest of the week. I will improve it as soon as I come back.

**Comment by thofma** [comment]
I reformulated the documentation. Hope it is now clearer.

**Comment by wbhart** [comment]
I finally got around to reviewing this. Sorry it took so long.

It looks ok, but there are a few issues:

* fmpz_mat_hnf_modular_eldiv initialises AmodD but doesn't clear it.

* _fmpz_unit does a lot of initialising and no clearing

* fmpz_mat_strong_echelon_form_mod seems to unconditionally return 0; was this intended? The return value is also not documented.

* fmpz_mat_mod_is_in_howell_form initialises g but never clears it; as g is not used until quite late in the function, the initialisation could be moved to later in the file to avoid having to clean it up except at the end of the file and one other return point.

* Is there any reason why fmpz_mat_mod_is_in_howell_form is not a function in the library? It doesn't need additional test code, as it is essentially tested by the same test code as the howell_form code.

* c is not cleaned up in main() in t-howell_form_mod.c.

* Documentation is missing for fmpz_mat_is_zero_row (test code is not needed).

**Comment by thofma** [comment]
Is it possible to include the previos message in my reply?

* Fixed the first three points. The return value is void.
* Fixed the problem with g in fmpz_mat_mod_is_in_howell_form.
* I wrote the _is_in_howell_form() function  just for testing purposes, similar to check_rref_form in nmod_mat/test/t-rref.c. If you want I can make it a library function.
* I fixed the c.
* I added documentation (also for nmod_mat_is_zero_row).

**Comment by wbhart** [comment]
It tells me there are conflicts. Have you merged from me lately?

Regarding the _is_in_howell_form, I don't mind. If you only wrote this for testing then it's fine. I'd only add it to the library if it is likely to be useful and is fairly fast. I leave it up to you.

**Comment by thofma** [comment]
Now it should work. I don't think _is_in_howell_form is fast or useful except for testing. So let's leave it out.

**Comment by wbhart** [comment]
Thanks.

**Pull request merged**
