### PR TITLE
.github/workflows/ci-sage.yml

### PR DESCRIPTION
**Pull request by mkoeppe**
Adds portability testing using the SageMath distribution

Example run: https://github.com/mkoeppe/flint2/runs/3037336754?check_suite_focus=true

### CODE REVIEW

**Comment by wbhart** [comment]
What is the total number of GitHub Actions time each PR/commit will take? We have only 2000 free minutes a month.

**Comment by alexjbest** [comment]
@wbhart as this is a public repo github actions is always free I believe, the 2000 minutes for "GitHub free" only applies to private repos.

**Comment by wbhart** [comment]
@alexjbest Ah thanks. That's great.

The other question then is how I can get the usual flint tests to run first. Some of these take more than 3 hours to run and I don't want to hold up our usual CI for that long.

**Comment by mkoeppe** [comment]
> What is the total number of GitHub Actions time each PR/commit will take?
Each job has a limit of 6 hours, giving an upper bound of 600 hours.
The shorter jobs are around 30 minutes.

Through GitHub edu you can probably upgrade to PRO for free, this would give access to a larger number of jobs that can be run in parallel.

**Comment by wbhart** [comment]
Are these pulling trunk or are they only pulling v2.8.0-beta at this point?

I did try to fix the Cygwin build error, but it still seems to be there.

**Comment by mkoeppe** [comment]
It's pulling the ref that it's on. To force a re-run here on the PR, you can edit the PR to set a new base or just push an empty commit to the branch to trigger a `pull_request synchronize` event

**Comment by wbhart** [comment]
I actually don't see how to edit the PR to base it on a different branch. Could you possibly reopen the PR on the flint-2.8 branch. That is where it will be the most useful for the time being.

I'm really not keen on adding over 80 long running CI jobs when we only had 3 previously. We mainly need this information around release times not every time a commit or PR is done.

**Comment by mkoeppe** [comment]
> I actually don't see how to edit the PR to base it on a different branch. Could you possibly reopen the PR on the flint-2.8 branch. That is where it will be the most useful for the time being.

I've changed the base.

> I'm really not keen on adding over 80 long running CI jobs when we only had 3 previously. We mainly need this information around release times not every time a commit or PR is done.

Sure, this is of course all configurable. I've removed the `pull_request` trigger now.

**Comment by wbhart** [comment]
Now Actions doesn't show anything happening. I'm not able to check whether the recent attempted Cygwin fix changed anything.

**Comment by mkoeppe** [comment]
After merging this PR you can trigger the workflow interactively in the GH Actions tab or by either pushing a tag.

**Pull request merged**
