### PR TITLE
Faster Hermite polynomials

### PR DESCRIPTION
**Pull request by math-gout**
I reduced the overhead in ```fmpz_poly_hermite_h``` and ```fmpz_poly_hermite_he``` for some improvement in performance.
I didn't add any profiling code as I don't know how that works ...

### CODE REVIEW

**Comment by fredrik-johansson** [comment]
Looks good.

There's no need to add profiling code for simple functions like this.

**Comment by wbhart** [comment]
That's correct, you don't need to add profiling code. However, did you do some timings by hand to see how much difference this makes?

**Comment by math-gout** [comment]
On my machine I get a performance boost between 1.2x and 1.7x depending on the value of n.
I tried all values of n from 0 to 1000 and all powers of 10 up to 10^6.

**Comment by wbhart** [comment]
That seems like a great improvement. Fantastic work!

**Pull request merged**
