### PR TITLE
Change order of inputs in divisor_sigma

### LINKED ISSUE #1015: Reverse order of inputs into `fmpz_divisor_sigma`
The function is often called divisor function and is often denoted by `\sigma_{x}(n)`. Therefore I think the order of the variables should be swapped.

### PR DESCRIPTION
**Pull request by albinahlback**
I believe I covered it all. Resolves #1015.

### CODE REVIEW

**Comment by albinahlback** [comment]
I forgot the documentation.

**Comment by tthsqe12** [comment]
Are we sure breaking this is a good idea? I agree it is better this way around, but once the interface is set.... one has to expect a certain amount of clumsiness and unpredictability for a c interface.

**Comment by wbhart** [comment]
We will publicise the change. The right time to object to changing the order would have been when Albin consulted us on it for our opinion, not after he has gone and done the work.

This is not a highly used function and everyone agrees it is round the wrong way. Let's get it right. It can cause as much confusion as it is.

**Comment by tthsqe12** [comment]
ok

**Comment by fredrik-johansson** [comment]
Sorry for not joining in sooner. It's not so clear cut that the current order is "wrong". For example, Sage's sigma() and Pari's sigma() and SymPy's divisor_sigma() all use the "wrong" order. But I don't have any strong objection to changing it.

**Comment by fredrik-johansson** [comment]
Also python-flint wraps the current divisor_sigma and will break with this change.

I don't know if there are any other users.

**Comment by albinahlback** [comment]
> We will publicise the change. The right time to object to changing the order would have been when Albin consulted us on it for our opinion, not after he has gone and done the work.
> 
> This is not a highly used function and everyone agrees it is round the wrong way. Let's get it right. It can cause as much confusion as it is.

There wasn't much time spent on this and I basically did it right away without hearing other people's opinion on it (like Fredrik's or Dan's). So with that being said, if this falls through it is OK, I would like to hear people's opinions.

**Comment by wbhart** [comment]
Ok, then I am happy to revisit the decision at Flint-Fridays. We should make a final decision before I merge it.

**Comment by albinahlback** [comment]
I will close this because of the relatively small motivation to change the order along with the silent breakage. I will keep the issue open though as I think it's worth to reconsider since it is rarely used.

**Pull request closed without merging**
