### PR TITLE
Shoup multiplication

### PR DESCRIPTION
**Pull request by VladimirGl**
Implemented Shoup multiplication algorithm.

### CODE REVIEW

**Comment by wbhart** [comment]
I've just started looking in detail at this.

One comment I have already is that I would not use < UWORD_MAX / 2 as the limit. The reason is that UWORD_MAX would be 2^64-1, so this isn't quite the right condition. I suppose you could use <= instead of <. But I would personally be inclined to use BIT_COUNT(blah) < FLINT_BITS.

**Comment by fredrik-johansson** [comment]
FLINT_BIT_COUNT would be slower.

Consider defining the maximum allowed modulus as a macro.

**Comment by fredrik-johansson** [comment]
I don't think the algorithm selection should be done in nmod_poly/scalar_mul_nmod.c.

_nmod_vec_scalar_mul_nmod itself should select the right algorithm.

**Comment by VladimirGl** [comment]
Some timings:
_nmod_vec_scalar_mul_nmod (without shoup) works ~6.6 sec for 1000000 random vectors with length < 100.
_nmod_vec_scalar_mul_nmod_shoup works ~5.8 sec.

nmod_mat_scalar_mul with shoup works ~11 sec for 1000000 random matrices with dimensions < 20.
without shoup it works ~15 sec.

I measured the time of tests. So it include time of initialization of structures.

**Comment by wbhart** [comment]
Getting there. In nmod_mat_scalar_mul you are still using ULONG_MAX / 2 instead of the new macro.

Also, could you please call the macro something like MUL_SHOUP_MAX_BITS or something like that and move it from flint.h into ulong_extras.h, say (you will need to #include ulong_extras.h in all the files that use the macro). I think this is just too specialised to be in flint.h.

**Pull request merged**
