### PR TITLE
Speed up `fmpz_fmma`

### PR DESCRIPTION
**Pull request by albinahlback**
This is a speed up on Haswell 4770k at least.

### CODE REVIEW

**Comment by wbhart** [comment]
Is it a speedup if one of the operands is zero?

Perhaps @fredrik-johansson can comment on whether this deoptimises a case that is important to him.

**Comment by fredrik-johansson** [comment]
Remark: if you change, fmma, then fmms should be changed to match.

fmpz_fmma was mainly introduced for n x 2 x m matrix multiplication, fmpz_fmms for small determinants / matrix inverses / solves.

So instead of profiling fmpz_fmma/fmpz_fmms themselves, I would benchmark the matrix operations with and without some zeros in the matrices.

**Comment by albinahlback** [comment]
```
fmpz_fmma with small numbers:
      min 1.011x speedup,    max 1.001x speedup
fmpz_fmma with one zero and small entries:
      min 1.018x speedup,    max 1.020x speedup
fmpz_fmma with one zero and big entries:
      min 0.985x speedup,    max 0.985x speedup
```

**Comment by wbhart** [comment]
Yes, that's true.

I think I will just merge this one, even without the benchmarks Fredrik requested. But it would of course still be nice to see if you have time.

**Pull request merged**
