### PR TITLE
Finite field square root

### PR DESCRIPTION
**Pull request by wbhart**
Adds square root for fq, fq_nmod and fq_zech.

### CODE REVIEW

**Comment by tthsqe12** [comment]
I don't like all of this throwing because the pseudo-exception mechanism in flint is useless. If calling sqrt on a non-square really is an illegal operation, then I am imagine the majority of uses will be is_square followed by sqrt. But then, the sqrt function is able to detect non-squares, so we have more confusing redundancy.
Also, does this is_square + possibly throwing sqrt interface generalize to other domains?
I would have sqrt return int 1 for success and 0 for failure unless there are very compelling efficiency reasons.
The existing fmpz_sqrt is not a good model. The existing fmpz_poly_sqrt has a great interface.

**Comment by wbhart** [comment]
I will change it to return 0/1 for failure/success.

**Comment by tthsqe12** [comment]
Ok. Will this sqrt-returning-a-int behaviour be a trend? I like consistency.

**Comment by wbhart** [comment]
Fine by me, so long as it is practical (it probably is).

**Comment by tthsqe12** [comment]
On a related note, do you know how to solve a*x^2+b*x+c=0 for x in characteristic 2?

**Comment by wbhart** [comment]
Having said that, there's an obvious problem for functions that already return an int value. And I really don't want to wind fake exception handling all the way through Flint. Take a look at libraries that do this (libtommath IIRC) to see why it's a very, very bad idea.

**Comment by wbhart** [comment]
Not off the top of my head.

**Comment by tthsqe12** [comment]
Sure. There is no hope for flint if the user tries to factor over Z/12Z. But, I think basic operations such as these should have non-throwing interfaces.

**Comment by thofma** [comment]
FWIW, I like the `0/1` convention.

**Comment by fingolfin** [comment]
@tthsqe12 which coefficient domains interest you? If it is fields in characteristic 2, take a look here https://www.staff.uni-mainz.de/pommeren/MathMisc/QuGlChar2.pdf

**Comment by tthsqe12** [comment]
Thanks, everything has been resolved.

**Comment by wbhart** [comment]
Note that in contradistinction to ulong_extras, fmpz_sqrtmod uses the 0/1 trick. I'm also not sure it is worth either changing this to match the nmod_sqrtmod convention or to change that to use the 0/1 trick (for performance reasons).

Again, have a think about this. These functions have been there for a very long time, so changing them needs a pretty overwhelming reason.

**Comment by tthsqe12** [comment]
So is the 0/1 thing a trick or a convention? :)
I am looking forward to your sqrt in R[x,y,z]. If you do R=Z, I can port it to other R.

**Comment by fredrik-johansson** [comment]
I think it is the GMP interface that is deficient here.

If you want to check if an integer is square, and only then compute the square root, you could 1) call mpn_perfect_square_p followed by mpn_sqrtrem without remainder, or 2) call mpn_sqrtrem with remainder. 1) is wasteful if the number is square; 2) is wasteful if the number is not square. We should just write an flint_mpn_sqrt that does the right thing in either case (combine fast detection of non-squares with efficient computation of exact square roots) and returns 0/1. Then use the 0/1 interface for fmpz_sqrt too.

**Comment by wbhart** [comment]
Right but that is not something we can do anything about. We no longer maintain a GMP fork, and we don't have resources here to contribute something better to GMP.

In any event, I am sure they thought their interface through very carefully. You could only prove your assertion by writing something better.

**Comment by wbhart** [comment]
@tthsqe12 As I said, returning 0/1 everywhere in the entire library is simply not feasible. It has it's place. So it's a dirty trick. :-)

**Comment by fredrik-johansson** [comment]
What I'm suggesting is basically an extension of mpn_perfect_square_p that does precisely that. I agree that mpn_sqrtrem can't be improved in the case of squares, but the idea here is to have a single function that is as fast as mpn_sqrtrem for squares and faster than mpn_sqrtrem (as fast as mpn_perfect_square_p) for non-squares.

**Comment by wbhart** [comment]
Yeah but we don't have the infrastructure to do that in Flint.

**Comment by fredrik-johansson** [comment]
I don't see the issue. mpn_perfect_square_p just does some mod p tests followed by a call to mpn_sqrtrem. We have far more complex things in mpn_extras. Granted, GMP runs a complex config-time program to generate the (tiny) table of p, but for our purposes we could just put in a static 32-bit table and a static 64-bit table. It's fine if it runs slightly slower than mpn_perfect_square_p; what matters is that it will beat simply calling mpn_sqrtrem which is what we do right now.

**Comment by fredrik-johansson** [comment]
I don't think we can actually change fmpz_sqrt though -- there is surely code out there that depends on this function computing the integer part of the square root of a non-square -- but we could have a separate fmpz_sqrt_if_the_number_is_a_perfect_square.

**Comment by wbhart** [comment]
fmpz_sqrt_exact

**Comment by wbhart** [comment]
@fredrik-johansson Yes, I suppose so. Perhaps you could open a ticket for this.

**Comment by wbhart** [comment]
@fredrik-johansson @tthsqe12 Any final concerns, otherwise I will merge this when green?

**Comment by tthsqe12** [comment]
It's all good. For mpoly you will just have one int-returning sqrt function, right?

**Comment by wbhart** [comment]
Any reason to not also have is_square? Not that I have any particular ideas on how to implement it in any way better than calling sqrt and checking the return value.

**Comment by tthsqe12** [comment]
If is_square can be done more efficiently than actually calculating a square root, then by all means is_square can exist. Also, if calculating a square root of a known square can be done more efficiently than verifying that the input is a square, then sqrt is a void function which return junk on non-square inputs. If the square root function can just as easily also detect non-square inputs, then sqrt should return an int. The only problem with this kind of interface is that it ties us to a particular implementation. Possibly:
- is_square returns int
- sqrt returns pair (int, the square root if success)
- sqrt_of_square returns the square root or junk

**Pull request merged**
