### PR TITLE
distinct degree factoring (nmod_poly) with degree limit

### PR DESCRIPTION
**Pull request by fieker**

### CODE REVIEW

**Comment by wbhart** [comment]
Thanks. It needs documentation and test code before it can be merged though. Also, we put spaces before and after <.

**Comment by fieker** [comment]
On Wed, Feb 08, 2017 at 12:05:59AM -0800, wbhart wrote:
> Thanks. It needs documentation and test code before it can be merged though. Also, we put spaces before and after <.

Possibly done - never sure about git

**Comment by wbhart** [comment]
The documentation should state whether it finds factors up to and including or excluding the bound. It should also state what happens if the bound is higher than the degree of the input polynomial or less than or equal to zero.

The test code should test that it actually does finds all factors up to the bound. It should also select random bounds, not just length/4.

The easiest way to do this would be to set the bound in advance and count the number of factors up to the bound and then check that it found the right number. Of course it will have to take multiplicity into account.

**Comment by fieker** [comment]
On Wed, Feb 08, 2017 at 02:04:16AM -0800, wbhart wrote:
> The documentation should state whether it finds factors up to and including or excluding the bound. It should also state what happens if the bound is higher than the degree of the input polynomial or less than or equal to zero.

Usually in flint, garbage input produces garbage output, ie. anything.
However, I will amend the documentation.
> 
> The test code should test that it actually does finds all factors up to the bound. It should also select random bounds, not just length/4.
> 
> The easiest way to do this would be to set the bound in advance and count the number of factors up to the bound and then check that it found the right number. Of course it will have to take multiplicity into account.
> 
The test code dose exactly what the normal function does. Given that this
is only asserting the factorisation matches I did not see the need to be
better.
I agree that it would be good to have more stringent tests.

And I will happily add more tests to Nemo/ Hecke once I figured out the
factorisation that I actually want: namely a complete factorisation up
the degree bound...

**Comment by wbhart** [comment]
The test code doesn't adequately test the function at all. It's not useful if it doesn't test the specified interface.

You should add your copyright to the files you've modified in non-trivial ways, as well.

**Comment by wbhart** [comment]
Yes, the original test function doesn't adequately test the function. It should be keeping track of the degrees or doing some counting at least. I don't know how the person who originally wrote it knew it was working. I'll open a ticket to fix the original test function.

Everything will need to be propagated to fmpz_mod_poly_factor too. I think the same interfaces exist there.

**Comment by wbhart** [comment]
I've now fixed the distinct_deg tests for both threaded and non-threaded versions in nmod_poly_factor and fmpz_mod_poly_factor to count the number of factors of each degree and make sure the total degree of the product of all factors of that degree is correct.

**Comment by fieker** [comment]
needs to be re-engineered

**Pull request closed without merging**
