### PR TITLE
mat_mul_vec for everyone.

### PR DESCRIPTION
**Pull request by tthsqe12**
This is a nice function that can be also used internally. The only problem is the use of raw pointers since flint lacks a vector type (I guess poly's don't count). I will continue with the other types unless this stuff is a bad idea.
@fieker

### CODE REVIEW

**Comment by wbhart** [comment]
It seems ok to me, so long as we can call it from Nemo.

**Comment by tthsqe12** [comment]
you just have to GC@preserve the poly, then you can use the .coeffs member ect.

Another possibility is to have functions that take, for example, `fmpz**` vector inputs and vector outputs. These could be used directly in Nemo for `*(::fmpz_mat, ::Vector{fmpz})`.

**Comment by wbhart** [comment]
I wouldn't be against that. I thought of doing the same thing myself more than once.

However, rather than fish around in the internals (.coeffs etc), I'd prefer a trivial interface function to return the pointer.

**Comment by tthsqe12** [comment]
> I wouldn't be against that. I thought of doing the same thing myself more than once.
Is this in reference to (1) the `.coeffs` member, or (2) another function taking `fmpz**` for `*(::fmpz_mat, ::Vector{fmpz})` ?

**Comment by wbhart** [comment]
It was in reference to 2. The second comment was about the .coeffs thing, not about 2.

In answer to your question, I don't think that is against the design of AA/Nemo. We don't have stuff like that at present, but I'm not personally against it. Of course others might have a different opinion, not sure.

**Comment by tthsqe12** [comment]
@thofma
With the pointer interface this is what I have in mind.

```julia
function Base.:*(a::fmpz_mat, b::Vector{fmpz})
    z = fmpz[fmpz() for i in 1:nrows(a)]
    ccall((:fmpz_mat_mul_fmpz_vec_ptr, Nemo.libflint), Nothing,
          (Ptr{Ref{fmpz}}, Ref{fmpz_mat}, Ptr{Ref{fmpz}}, Int),
          z, a, b, length(b))
    return z
end

julia> matrix(ZZ, [1 2; 3 4]) * [fmpz(5), fmpz(6)]
2-element Vector{fmpz}:
 17
 39


function Base.:*(a::Vector{fmpz}, b::fmpz_mat)
    z = fmpz[fmpz() for i in 1:ncols(b)]
    ccall((:fmpz_mat_fmpz_vec_mul_ptr, Nemo.libflint), Nothing,
          (Ptr{Ref{fmpz}}, Ptr{Ref{fmpz}}, Int, Ref{fmpz_mat}),
          z, a, length(a), b)
    return z
end

julia> [fmpz(5), fmpz(6)] * matrix(ZZ, [1 2; 3 4])
2-element Vector{fmpz}:
 23
 34
```
Then with the usual flint interface, this is possible.

```julia
function Base.:*(a::fmpz_mat, b::fmpz_poly)
    z = fmpz_poly()
    z.parent = b.parent
    ccall((:fmpz_poly_fit_length, Nemo.libflint), Nothing,
          (Ref{fmpz_poly}, Int),
          z, nrows(a))
    ccall((:_fmpz_poly_set_length, Nemo.libflint), Nothing,
          (Ref{fmpz_poly}, Int),
          z, nrows(a))
    ccall((:fmpz_mat_mul_fmpz_vec, Nemo.libflint), Nothing,
          (Ptr{Nothing}, Ref{fmpz_mat}, Ptr{Nothing}, Int),
          z.coeffs, a, b.coeffs, length(b))
    ccall((:_fmpz_poly_normalise, Nemo.libflint), Nothing,
          (Ref{fmpz_poly},),
          z)
    return z
end

julia> _, x = ZZ["x"];

julia> matrix(ZZ, [1 2; 3 4]) * (5+6*x)
39*x + 17

julia> matrix(ZZ, [1 2; 3 4]) * (4-3*x+x^2)
-2
```

**Comment by thofma** [comment]
I love it!

**Comment by wbhart** [comment]
The Flint changes are great. I'm not as sure I like supporting multiplication of a matrix by a polynomial in this way in Nemo. It's giving a few too many meanings to multiplication in my opinion. But I'm less worried about this ending up in Nemo than in Flint.

**Comment by tthsqe12** [comment]
This is just to demonstrate how it works. You can call the matrix-poly multiplication whatever, including `__mul_bad`

**Comment by tthsqe12** [comment]
I am done with this now. I left out fmpq_mat because we can just use some generic code in julia.

**Comment by wbhart** [comment]
Sure. Given that this is mainly intended for use by a HLL, that's fine.

**Comment by wbhart** [comment]
Looks good. It's a shame multiplication by a vector on the left will be slower than on the right. But I totally see why this is the case.

**Pull request merged**
