### PR TITLE
Improve ecm

### PR DESCRIPTION
**Pull request by wbhart**

### CODE REVIEW

**Comment by tthsqe12** [comment]
If the code for the n=2 case of flint_mpn_mulmod_preinvn were in a macro, possibly in mpn_extras.h, then it could be reused in the fmpz_mod module.

**Comment by wbhart** [comment]
I thought we decided it wasn't practical since it requires normalised numbers.

**Comment by tthsqe12** [comment]
I would have to time it, but I am confident that even with an additional left shift and right shift, the reduced number of multiplications would make it faster. Ill time it now.

**Comment by tthsqe12** [comment]
I was looking into this mulmod_preinvn function, and there might be a bug in the test code `mpn-extras/test/t-mulmod_preivn.c`. The modulus `d` is generated via a call to `mpz_rrandomb(d, st, size*FLINT_BITS)`, which, according to the documentation, could return `d` size less than `size`. Therefore, the call to `flint_mpn_preinvn(dinv, d->_mp_d, size)` is bad.

**Comment by wbhart** [comment]
The original test code was broken. I believe I have corrected it in the repo. The mpz_rrandomb function should give a random number of exactly the right number of bits, according to the GMP manual.

**Comment by tthsqe12** [comment]
Sorry, I was reading the wrong function in the gmp documentation. The test code for `mulmod_preinvn` has a different problem: it is not testing `norm > 0`.

By the way, I adapted your 2 limb mulmod_preinvn and compared it with the existing fmpz_mod_mul, and ... the best I could do with it was 15% slower than the existing. The existing one has 15.5 multiplications, while yours has 11.5 multiplications. The problem is not the shifts in your version, its the additions and subtractions.

**Comment by wbhart** [comment]
I think you have the old test code. The new test code should be using norm != 0. That was one of the bugs I fixed.

Yes, it's not surprising that my code is not faster. If I really cared a lot I would try to get another 15% from the arithmetic. But there are so many other things I could do that would make an even bigger difference. I'm not going to bother about it for the time being.

**Comment by tthsqe12** [comment]
Yes, the new test code looks better.
Why is it not surprising? Yours has fewer multiplications and additions, and even with a 128 bit modulus with norm hard coded to zero it is 15% slower. Maybe mine has greater ILP, but I am still suspicious.

**Comment by wbhart** [comment]
It's not surprising because I didn't work very hard on it. I used to spend a lot of time fighting for every 5%, but these days I just do what I have time for.

**Comment by tthsqe12** [comment]
Ok. I am saying I wrote a new _fmpz_mod_mul2 using your code as a base and improving things like that 5%. With that 5% it is still 15% slower.

**Comment by wbhart** [comment]
If you want to improve/change my code, go right ahead.

**Pull request closed without merging**
