### PR TITLE
representatives for finite field elements

### PR DESCRIPTION
**Pull request by tthsqe12**
This should have been included in the release and makes the finite fields a bit more useful from a user's perspective.

### CODE REVIEW

**Comment by wbhart** [comment]
I'm still concerned about the straight conversion between nmod_poly and fq_nmod_poly. I'm having some trouble remembering the details, but I recall when we were working on finite field embeddings we ran into some troubles with this sort of thing.

Roughly speaking the problem is as follows. The Conway polynomial for fields of degree 1 is essentially an identification with Z/pZ and a choice of multiplicative generator of the multiplicative group, i.e. a primitive root mod p.

For example, the field of characteristic 5 and degree 1 has Conway polynomial x+3. This means 2 is being chosen as generator of the multiplicative group.

Now ordinarily this doesn't cause a problem. But if you call the primitive root function in Flint it probably won't return the same primitive root. This is a problem when doing multiplicative things like taking norms in extensions of finite fields and so on. We sorted all this out in the extension code, but I'm wondering if we should make some attempt to match the primitive root in the Conway polynomial with the output of the Flint primitive root function.

Unfortunately at the present moment I can't think of a situation where this sort of thing would be a major issue, but I know we hit it without really initially understanding why when we worked on the embedding stuff.

Are you absolutely sure you just want a straight conversion from nmod_poly to fq_nmod_poly and back? From memory, the issue is precisely when you go from Z/pZ to F_p, do something in an extension that is multiplicative, then convert back to Z/pZ that you can end up with nonsense.

**Comment by wbhart** [comment]
So I found the commit where we sorted this issue out [1]. In fact the issue there was when there was no Conway polynomial. Unless ctx->prime_root was chosen to be the norm of the generator, one would end up with incorrect results in trace and norm.

It does certainly seem to be the case that the trace from an extension down to F_p will depend on what primitive root was chosen. As we are going to be using this code in dealing with operators, I'd be worried that for example the trace of the operator would be meaningless unless the user has some way to determine what primitive root was used.

I'm honestly not sure what the implications are for conversion from Z/pZ to F_p and back.

[1] https://github.com/wbhart/flint2/commit/9d57d6020712cb6d153985a0eb931009144c2b3c#diff-9fc569d946f9a01b83358107b50891a8

**Comment by wbhart** [comment]
Perhaps we just say that if you work in Z/pZ as a proxy for F_p then you lose the (choice of) multiplicative structure and that is your problem. But I'm nervous about where this code is to be deployed in Singular. Are we absolutely sure the multiplicative structure is not relevant there.

**Comment by tthsqe12** [comment]
Um, singular via factory works with Fq as Fp[t]/h(t) for some irreducible h. Flint also uses this representation in all three cases. We simply need an official way to convert representatives. I don't think any multiplicative structure is relevant because everything is tied to h(t). I did have a question on the internal representation of zero in fq_zech. What is going on here? The code did not make sense to me.

**Comment by tthsqe12** [comment]
The conversion is for fq elements, not fq_nmod_poly BTW. Probably a typo

**Comment by wbhart** [comment]
Ok, then could you add a note to the documentation that says information about the multiplicative group, particularly the generator used on the fq side is lost when converting to Z/pZ.

As for Zech representation it just stored the power of x, i.e. the representation is inherently multiplicative. The element 0 is obviously not a power of x and so needs a special representation. I assume that is going on. But if there is some specific piece of code you think I can help with, let me know. But I didn't write it, so am not sure if I will have any more clues than you will.

**Comment by wbhart** [comment]
And obviously if 0 is the result of some addition/subtraction operation, it needs to be handled separately.

**Comment by tthsqe12** [comment]
So the non zero elements are stored as x^0, ..., x^(q-2) in fq_zech. The zero element is stored as x^(q-1). I think this last commit fixes my initial bugs and is good.

**Comment by wbhart** [comment]
Yeah that sounds familiar. It just needs a value to use for zero. It's always handled separately I think, so doesn't matter much what it is.

**Pull request merged**
