### PR TITLE
Start fmpz divides threaded

### PR DESCRIPTION
**Pull request by tthsqe12**
There was one careless spot in divrem_array and another in combine_like_terms that needed to fixed in order for the new and improved test code to pass.

### CODE REVIEW

**Comment by tthsqe12** [comment]
@wbhart I will need to add some tuning and some thread pinning before this will be ready to go. I also would like to remind you that this code is 100% broken on ARM or any other weakly-ordered cpu. We need a CPU_IS_WEAKLY_ORDERED define to guard against the inclusion of this code.

**Comment by wbhart** [comment]
Sure, we can add a CPU detection feature in configure (we already have some tests there) which populates config.h with this flag. For now, you could just define it to be 1 (just add a line to configure at the point where config.h is being written out that just sets this flag to 1 in config.h) and then use the guards everywhere you think they should go.

It's also worth making a note in the documentation, perhaps even in the section on threading or the section on configuring Flint (or both).

Later on we can detect the CPU in configure and set the flag to an appropriate value.

**Comment by tthsqe12** [comment]
@wbhart this is probably ready to go. I did change the config file in commit https://github.com/wbhart/flint2/pull/538/commits/ab4fb3e1fb36cc58b1843c2e8c6a228ff1470a45

**Comment by tthsqe12** [comment]
it would be nice to have this merged

**Comment by wbhart** [comment]
Done. Thanks!

**Pull request merged**
