### PR TITLE
fix mpoly test code

### PR DESCRIPTION
**Pull request by tthsqe12**
This was my fault. I completely forgot about the mpoly test code. Should all checks pass now?

### CODE REVIEW

**Comment by wbhart** [comment]
Probably not. But at least it is not your fault any more. Thanks for fixing this!

**Comment by tthsqe12** [comment]
The build error in mpoly test code was definitely my fault. As for the other failures, ...

**Comment by wbhart** [comment]
Sure. The tests have been failing all the time. As it turned out, they were never actually run on Windows. Someone fixed that recently, but now we have actual failures.

**Comment by wbhart** [comment]
On Appveyor there are many failing fmpz_mpoly tests in the cl, 64 tests. This could be due to some missing FLINT_DLL declarations on some of the prototypes in header files.

**Comment by tthsqe12** [comment]
Is there a branch that passes this new testing framework?

**Comment by wbhart** [comment]
We don't need it all to pass (there are some known issues), we just need to check all the FLINT_DLL's are there. We shouldn't have so many fmpz_mpoly functions failing. Most of the rest of Flint is fine.

**Comment by wbhart** [comment]
I'm not able to see where the bug is. I've checked the fmpz, fmpz_mpoly and mpoly header files and don't see any missing FLINT_DLL's. The fmpz_mpoly tests that fail all seem to be division related. But this doesn't seem to depend on what data structure or algorithm. So one would guess the failure should be somewhere in the code for dividing monomials. Normally, it would be a long used instead of an slong somewhere. But I don't see it.

Maybe I should just merge it and we'll try to track this down later.

**Comment by wbhart** [comment]
In ulong_extras at the bottom, there is a static __inline__ instead of ULONG_EXTRAS_INLINE and on line 117 there is an extra FLINT_DLL that doesn't look like it belongs there. I don't know if this could be the problem.

I don't know what other files we use that could affect the division code. It actually seems unlikely to be related to exponents, as then other code would also fail, as all the exponent code is abstracted in mpoly, unless there is some exponent code only used by fmpz_mpoly.

**Comment by tthsqe12** [comment]
Ill try to track it down tomorrow.

**Comment by tthsqe12** [comment]
Unfortunately I cannot see which test failed. Can you post it here along with word size of the machine?

**Comment by tthsqe12** [comment]
It seems to be something very fundamental and related to anything requiring a division. Unfortunately now, 6 months after applying, my compiler farm application was just rejected.

**Comment by isuruf** [comment]
This needs to be merged into trunk as well.

**Pull request merged**
