### PR TITLE
Add fmpz_ndiv_qr for nearest Euclidean division

### PR DESCRIPTION
**Pull request by albinahlback**
Timings on Haswell 4770k:
```
fmpz_ndiv_qr:
  min time is 8.541 cycles
  max time is 8.928 cycles

fmpz_fdiv_qr:
  min time is 6.625 cycles
  max time is 6.905 cycles

fmpz_cdiv_qr:
  min time is 6.581 cycles
  max time is 7.072 cycles

fmpz_tdiv_qr:
  min time is 6.240 cycles
  max time is 7.036 cycles
```

### CODE REVIEW

**Comment by wbhart** [comment]
What happens when it is equally far from two integers. Does it round up, down or towards zero?

**Comment by albinahlback** [comment]
Since `tdiv` is used for the underlying algorithm, and the quotient and remainder only changes if the 'new' remainder is smaller, it should round towards zero for ties.

**Comment by wbhart** [comment]
Thanks. Could you add a test for that case. Otherwise I think this is fine and I'm happy to merge it.

**Comment by fredrik-johansson** [comment]
Rounding to even is more standard (but a bit more complicated to implement).

**Comment by albinahlback** [comment]
Sure!

**Pull request merged**
