### PR TITLE
Missing prototypes in fq_nmod.h

### PR DESCRIPTION
**Pull request by jpflori**

### CODE REVIEW

**Comment by wbhart** [comment]
These are already in fq_templates.h which is included by fq_nmod.h. Unless I am missing something.

**Comment by jpflori** [comment]
Argh, sorry...
I did not check that one.
Then I guess the prototypes should be removed from fq.h.

2015-12-03 13:12 GMT+01:00 wbhart <notifications@github.com>:

> These are already in fq_templates.h which is included by fq_nmod.h. Unless
> I am missing something.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wbhart/flint2/pull/201#issuecomment-161617134>.
>



-- 
Jean-Pierre Flori

**Comment by jpflori** [comment]
Actually most of the prototyes in fp[_nmod].h could be moved to
fq_templates.h.
(I was looking for fq_template.h which for sure does not exist...)

2015-12-03 13:15 GMT+01:00 Jean-Pierre Flori <jpflori@gmail.com>:

> Argh, sorry...
> I did not check that one.
> Then I guess the prototypes should be removed from fq.h.
>
> 2015-12-03 13:12 GMT+01:00 wbhart <notifications@github.com>:
>
>> These are already in fq_templates.h which is included by fq_nmod.h.
>> Unless I am missing something.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/wbhart/flint2/pull/201#issuecomment-161617134>.
>>
>
>
>
> --
> Jean-Pierre Flori
>



-- 
Jean-Pierre Flori

**Comment by wbhart** [comment]
Moved is maybe not the right word. Certainly any prototypes that are already in fq_templates.h don't need to also be in fq[_nmod].h. I'm not really sure why they are in fact in both places. I guess it was done before Mike decided on the templating strategy or something.

**Comment by wbhart** [comment]
I guess these got taken care of in the end. However, it is still true that many of the prototypes in fq[_nmod].h could be templated. I will open a ticket for that.

**Pull request closed without merging**
