### PR TITLE
refactor function to effectively allow the use in fmpq_poly

### PR DESCRIPTION
**Pull request by fieker**

### CODE REVIEW

**Comment by wbhart** [comment]
The underscore functions should take arrays not polys.

**Comment by fieker** [comment]
On Thu, Mar 10, 2016 at 10:03:42AM -0800, wbhart wrote:
> By the way, there is already _fmpz_vec_get_nmod_vec.
Yes, but the point was
 - I did not find it
 - I cannot use it
I need this as part of the Julia interface. If I use the
_fmpz_vec_get_nmod_vec function, then I need the vec_normalize as well -
which I canot call from Julia.
The one I "created" bypasses this problem...

**Comment by wbhart** [comment]
Normalisation is only relevant to polynomials. For that we have _nmod_poly_normalise, which actually acts on an nmod_poly_t. There should be no problem applying that if you need to.

**Comment by fieker** [comment]
On Thu, Mar 10, 2016 at 10:03:42AM -0800, wbhart wrote:
> By the way, there is already _fmpz_vec_get_nmod_vec.
> 
But that ... function does not get a modulus, it gets an nmod_t!!

I finally managed it. Instead of a short c-modification, I need to call
three functions (fit_length, get, normalise), set the length in between
and create a struct to hold the modulus.

**Comment by wbhart** [comment]
Yes, the nmod_t is annoying to handle in Julia since it doesn't support C structs inside other C structs like this very well. It results in hackish code.

I think there might be a C structs Julia library somewhere that we could use. Not sure.

**Pull request closed without merging**
