### PR TITLE
Special-case quadratics in fmpz_poly_factor

### PR DESCRIPTION
**Pull request by fredrik-johansson**
This speeds up factoring quadratic polynomials 50x.

### CODE REVIEW

**Comment by wbhart** [comment]
This is great, but I'll hold off on merging until @tthsqe12 says it's ok to merge. He's working on roots (I think in fmpz_mod_poly and nmod_poly), but I just want to make sure we aren't making anything harder for him (very unlikely).

**Comment by tthsqe12** [comment]
Everything is fine. The roots will be ready soon, and there will be no conflict.
I am not doing roots in characteristic zero by the way.

**Comment by wbhart** [comment]
No worries. Just wanted to check.

**Comment by tthsqe12** [comment]
Lets get this merged.

**Comment by wbhart** [comment]
Thanks, I totally forgot about it.

**Pull request merged**
