### PR TITLE
polish mpoly profiles

### PR DESCRIPTION
**Pull request by tthsqe12**
@wbhart  Could you let me know if the directions at the top of `fmpz_mpoly/profile/p-mul.c` are clear enough? You can run, for example,
```
./build/fmpz_mpoly/profile/p-mul 4 sparse 12 12
./build/fmpz_mpoly/profile/p-mul 4 dense 25 25
```

### CODE REVIEW

**Comment by tthsqe12** [comment]
This also fixes another critical bug.

**Comment by wbhart** [comment]
Relatively clear. But you could say what the 4, 12 and 12 mean.

**Comment by tthsqe12** [comment]
Here are the relative timings for fmpz_mpoly_div on the sparse power 16 benchmark:

current flint:
time(div(f*g, g)) = 3.4% of time(mul(f, g))
time(div(f*g, f)) = 43.7% of time(mul(f, g))

_very_ old flint:
time(div(f*g, g)) = 1.3% of time(mul(f, g))
time(div(f*g, f)) = 72.2% of time(mul(f, g))

Relatively speaking, you can see that the faster div has become a little slower, and the slower div has become a little faster.

**Comment by tthsqe12** [comment]
@wbhart This is ready to go assuming the tests pass. Turns out there was a performance bug in fmpz_mpoly_div. Here are the new relative timings for power 16:

current flint over Z:
```time(div(f*g, g)) =  1.7% of time(mul(f, g))```
```time(div(f*g, f)) = 41.1% of time(mul(f, g))```

current flint over Z/pZ:
```time(div(f*g, g)) =  0.02% of time(mul(f, g))```
```time(div(f*g, f)) = 45.8% of time(mul(f, g))```

The penultimate number is not a typo: The reason it is so slow at 1.7% over Z is that almost all of the time is spent scanning the dividend to find its bit count.

**Comment by wbhart** [comment]
Great!

**Pull request merged**
