### PR TITLE
[RFC&PI] add fmpz_mat_mul_small (to replace fmpz_mat_mul_{1|2a|2b})

### PR DESCRIPTION
**Pull request by tthsqe12**
This finishes my crusade against fmpz_mat_mul_strassen, and the fmpz_mat_mul can, in my view, be tuned now that the basecase algorithms are properly threaded.

### CODE REVIEW

**Comment by fredrik-johansson** [comment]
This looks good, but is it really a complete replacement for fmpz_mat_mul_1 etc.? I fear there is more overhead for really small matrices.

**Comment by tthsqe12** [comment]
The slow down is about 30% for 3x3 matrices, and this is due to the transpose. However, I have to fix some other bugs first.
The parallel creation of fmpz is crashing for me :(

**Comment by tthsqe12** [comment]
So, the 30% slow down was in debug+reentrant mode. In normal mode I didn't see it go above 14%.
Note that I haven't deleted the old code.
If this 14% is unacceptable, I can include the old code in the final tuning.
Also, for the really small mul's (the left most column), I have observed a strassen cutoff of somewhere in the range 1000 to 1500 on one thread. On more threads it will be even higher.
Finally, this pr https://github.com/wbhart/flint2/pull/915 had a bad bug that caused thread to duplicate work.

my p-mul_small output:

with 1 thread:
```
(m, k, n) *** timings for mul_small nanoseconds per m*k*n (mul in parentheses) ***
( 3, 3, 3): min 2.875 ns (2.500)  max 3.625 ns (3.125)  aver 3.200 ns (2.825)  ratio 1.133
( 3, 3, 4): min 2.375 ns (2.125)  max 3.375 ns (2.750)  aver 2.862 ns (2.537)  ratio 1.128
( 3, 3, 5): min 2.125 ns (1.875)  max 3.000 ns (2.625)  aver 2.600 ns (2.312)  ratio 1.124
( 3, 3, 6): min 2.000 ns (1.750)  max 3.000 ns (2.625)  aver 2.425 ns (2.187)  ratio 1.109
( 3, 3, 7): min 1.875 ns (1.750)  max 2.625 ns (2.375)  aver 2.287 ns (2.100)  ratio 1.089
( 3, 3, 8): min 1.750 ns (1.500)  max 2.375 ns (2.375)  aver 2.087 ns (1.950)  ratio 1.071
( 3, 3, 9): min 1.625 ns (1.500)  max 2.375 ns (2.375)  aver 2.062 ns (1.975)  ratio 1.044
( 3, 4, 3): min 2.375 ns (2.125)  max 3.125 ns (2.750)  aver 2.800 ns (2.487)  ratio 1.126
( 3, 4, 4): min 2.125 ns (1.750)  max 2.750 ns (2.500)  aver 2.450 ns (2.187)  ratio 1.120
...
( 9, 9, 3): min 1.000 ns (1.000)  max 1.500 ns (1.375)  aver 1.325 ns (1.287)  ratio 1.029
( 9, 9, 4): min 0.875 ns (0.875)  max 1.375 ns (1.375)  aver 1.137 ns (1.162)  ratio 0.978
( 9, 9, 5): min 0.750 ns (0.875)  max 1.250 ns (1.625)  aver 1.112 ns (1.150)  ratio 0.967
( 9, 9, 6): min 0.750 ns (0.750)  max 1.500 ns (1.500)  aver 1.100 ns (1.125)  ratio 0.978
( 9, 9, 7): min 0.625 ns (0.750)  max 1.125 ns (1.500)  aver 1.000 ns (1.075)  ratio 0.930
( 9, 9, 8): min 0.625 ns (0.625)  max 1.125 ns (1.500)  aver 0.975 ns (1.050)  ratio 0.929
( 9, 9, 9): min 0.625 ns (0.750)  max 1.250 ns (1.375)  aver 1.000 ns (1.012)  ratio 0.988
*** timings for mul_small nanoseconds per dim^3 (mul in parentheses) ***
   5: min 1.200 ns (1.200)  max 2.000 ns (2.200)  aver 1.693 ns (1.600)  ratio 1.058
   8: min 0.600 ns (0.600)  max 1.400 ns (1.400)  aver 0.979 ns (1.057)  ratio 0.926
  12: min 0.400 ns (0.400)  max 1.200 ns (1.200)  aver 0.836 ns (0.857)  ratio 0.975
  17: min 0.400 ns (0.400)  max 1.000 ns (1.200)  aver 0.728 ns (0.736)  ratio 0.990
  23: min 0.400 ns (0.400)  max 1.000 ns (1.200)  aver 0.686 ns (0.707)  ratio 0.970
  30: min 0.199 ns (0.398)  max 0.796 ns (1.195)  aver 0.612 ns (0.711)  ratio 0.860
  39: min 0.397 ns (0.397)  max 0.793 ns (0.992)  aver 0.645 ns (0.666)  ratio 0.968
  50: min 0.195 ns (0.390)  max 0.780 ns (0.976)  aver 0.613 ns (0.620)  ratio 0.989
  64: min 0.381 ns (0.381)  max 0.763 ns (1.144)  aver 0.593 ns (0.695)  ratio 0.853
  82: min 0.363 ns (0.363)  max 0.725 ns (1.088)  aver 0.609 ns (0.641)  ratio 0.949
 104: min 0.356 ns (0.356)  max 0.889 ns (0.889)  aver 0.578 ns (0.635)  ratio 0.910
 132: min 0.290 ns (0.435)  max 0.725 ns (1.015)  aver 0.492 ns (0.652)  ratio 0.754
 167: min 0.322 ns (0.537)  max 0.751 ns (1.074)  aver 0.479 ns (0.717)  ratio 0.668
 210: min 0.324 ns (0.432)  max 0.648 ns (1.296)  aver 0.447 ns (0.787)  ratio 0.569
 264: min 0.272 ns (0.489)  max 0.652 ns (1.141)  aver 0.443 ns (0.745)  ratio 0.594
 332: min 0.301 ns (0.492)  max 0.629 ns (1.230)  aver 0.425 ns (0.781)  ratio 0.544
 417: min 0.276 ns (0.496)  max 0.621 ns (1.724)  aver 0.419 ns (1.060)  ratio 0.395
 523: min 0.273 ns (0.538)  max 0.615 ns (1.692)  aver 0.412 ns (1.120)  ratio 0.368
 655: min 0.270 ns (0.527)  max 0.609 ns (1.626)  aver 0.405 ns (1.070)  ratio 0.378
 820: min 0.267 ns (0.475)  max 0.602 ns (1.458)  aver 0.397 ns (0.967)  ratio 0.411
1027: min 0.267 ns (0.453)  max 0.598 ns (1.375)  aver 0.405 ns (0.914)  ratio 0.443
```

with 8 threads:
```
(m, k, n) *** timings for mul_small nanoseconds per m*k*n (mul in parentheses) ***
( 3, 3, 3): min 2.875 ns (2.500)  max 3.625 ns (3.125)  aver 3.212 ns (2.812)  ratio 1.142
( 3, 3, 4): min 2.375 ns (2.125)  max 3.125 ns (2.875)  aver 2.837 ns (2.537)  ratio 1.118
( 3, 3, 5): min 2.125 ns (2.000)  max 3.000 ns (2.750)  aver 2.600 ns (2.325)  ratio 1.118
( 3, 3, 6): min 2.000 ns (1.875)  max 2.875 ns (2.625)  aver 2.437 ns (2.200)  ratio 1.108
( 3, 3, 7): min 1.875 ns (1.625)  max 2.625 ns (2.500)  aver 2.275 ns (2.100)  ratio 1.083
( 3, 3, 8): min 1.625 ns (1.500)  max 2.375 ns (2.250)  aver 2.087 ns (1.937)  ratio 1.077
( 3, 3, 9): min 1.625 ns (1.500)  max 2.375 ns (2.375)  aver 2.050 ns (2.000)  ratio 1.025
( 3, 4, 3): min 2.500 ns (2.125)  max 3.125 ns (2.750)  aver 2.837 ns (2.487)  ratio 1.141
( 3, 4, 4): min 2.000 ns (1.875)  max 2.750 ns (2.500)  aver 2.475 ns (2.200)  ratio 1.125
...
( 9, 9, 3): min 1.000 ns (1.000)  max 1.500 ns (1.500)  aver 1.312 ns (1.312)  ratio 1.000
( 9, 9, 4): min 0.750 ns (0.875)  max 1.375 ns (1.375)  aver 1.162 ns (1.162)  ratio 1.000
( 9, 9, 5): min 0.750 ns (0.875)  max 1.250 ns (1.625)  aver 1.150 ns (1.162)  ratio 0.989
( 9, 9, 6): min 0.750 ns (0.750)  max 1.375 ns (1.625)  aver 1.087 ns (1.137)  ratio 0.956
( 9, 9, 7): min 0.625 ns (0.750)  max 1.250 ns (1.625)  aver 1.012 ns (1.087)  ratio 0.931
( 9, 9, 8): min 0.625 ns (0.750)  max 1.125 ns (1.625)  aver 0.950 ns (1.112)  ratio 0.854
( 9, 9, 9): min 0.625 ns (0.625)  max 1.250 ns (1.500)  aver 0.975 ns (1.062)  ratio 0.918
*** timings for mul_small nanoseconds per dim^3 (mul in parentheses) ***
   5: min 1.200 ns (1.200)  max 2.000 ns (2.000)  aver 1.671 ns (1.621)  ratio 1.031
   8: min 0.600 ns (0.800)  max 1.400 ns (1.600)  aver 0.986 ns (1.079)  ratio 0.914
  12: min 0.400 ns (0.400)  max 1.000 ns (1.400)  aver 0.814 ns (0.900)  ratio 0.905
  17: min 0.400 ns (0.400)  max 1.000 ns (1.200)  aver 0.700 ns (0.764)  ratio 0.916
  23: min 0.200 ns (0.400)  max 1.000 ns (1.200)  aver 0.607 ns (0.786)  ratio 0.773
  30: min 0.199 ns (0.398)  max 0.996 ns (0.996)  aver 0.612 ns (0.718)  ratio 0.851
  39: min 0.397 ns (0.397)  max 0.992 ns (0.992)  aver 0.630 ns (0.687)  ratio 0.918
  50: min 0.195 ns (0.390)  max 0.780 ns (0.976)  aver 0.592 ns (0.662)  ratio 0.895
  64: min 0.191 ns (0.381)  max 0.572 ns (1.144)  aver 0.375 ns (0.729)  ratio 0.514
  82: min 0.181 ns (0.544)  max 0.363 ns (0.907)  aver 0.317 ns (0.706)  ratio 0.450
 104: min 0.178 ns (0.356)  max 0.356 ns (1.067)  aver 0.267 ns (0.673)  ratio 0.396
 132: min 0.145 ns (0.435)  max 0.290 ns (1.015)  aver 0.202 ns (0.647)  ratio 0.312
 167: min 0.107 ns (0.537)  max 0.215 ns (1.181)  aver 0.150 ns (0.736)  ratio 0.203
 210: min 0.108 ns (0.540)  max 0.324 ns (1.188)  aver 0.123 ns (0.794)  ratio 0.155
 264: min 0.054 ns (0.489)  max 0.109 ns (1.196)  aver 0.089 ns (0.738)  ratio 0.121
 332: min 0.055 ns (0.492)  max 0.109 ns (1.230)  aver 0.078 ns (0.769)  ratio 0.102
 417: min 0.041 ns (0.317)  max 0.097 ns (0.703)  aver 0.073 ns (0.403)  ratio 0.182
 523: min 0.049 ns (0.273)  max 0.091 ns (0.566)  aver 0.070 ns (0.353)  ratio 0.199
 655: min 0.043 ns (0.121)  max 0.089 ns (0.399)  aver 0.064 ns (0.259)  ratio 0.248
 820: min 0.044 ns (0.109)  max 0.089 ns (0.355)  aver 0.062 ns (0.231)  ratio 0.268
1027: min 0.042 ns (0.101)  max 0.086 ns (0.379)  aver 0.061 ns (0.236)  ratio 0.257
```

**Comment by wbhart** [comment]
So what is the verdict @fredrik-johansson ?

**Comment by fredrik-johansson** [comment]
I'm not going to fret over 14%, but maybe it's worth to keep the equivalent of mul_1 for the tiniest of matrices with the tiniest of entries?

Some inefficiency with fmpz_mat_mul_small is that it computes the bit sizes of the matrices; this will be done in fmpz_mat_mul (for algorithm selection); you may want to pass the size as input to fmpz_mat_mul_small so it doesn't have to be done twice.

**Comment by tthsqe12** [comment]
> I'm not going to fret over 14%, but maybe it's worth to keep the equivalent of mul_1 for the tiniest of matrices with the tiniest of entries?

Yup. I will just do that.

> Some inefficiency with fmpz_mat_mul_small is that it computes the bit sizes of the matrices; this will be done in fmpz_mat_mul (for algorithm selection); you may want to pass the size as input to fmpz_mat_mul_small so it doesn't have to be done twice.

That is why mat_mul is going to use all of the underscore functions anyways. The double scan is noticeable at all sizes.

**Comment by fredrik-johansson** [comment]
Agreed. By the way, we can also optimize fmpz_mat_max_bits a bit: _fmpz_vec_max_bits is clever, but fmpz_mat_max_bits needs to call it for each row, which is less clever. We should do a version of _fmpz_vec_max_bits that can be chained, or just do a fast direct implementation of fmpz_mat_max_bits.

Even better for the final tuning of fmpz_mat_mul would be to design a variant of fmpz_mat_max_bits that also gathers some other statistics in the same pass over the entries. We could then check for special, structured input (lower/upper triangular matrices, diagonal matrices, sparse matrices and super-unbalanced matrices) and dispatch those to special methods.

**Comment by tthsqe12** [comment]
I would say this pr is ready to go then.

**Comment by wbhart** [comment]
@tthsqe12 You said above that you were going to retain the equivalent of mat_muL1 for the tiniest of matrices, but I didn't see a further commit. Also, were any changes necessary to deal with @fredrik-johansson 's final comment, or is this to go into a separate ticket/PR?

**Comment by tthsqe12** [comment]
> You said above that you were going to retain the equivalent of mat_muL1 for the tiniest of matrices, but I didn't see a further commit.

No further commit are necessary. I didn't delete the old code in the first place.

> Also, were any changes necessary to deal with @fredrik-johansson 's final comment, or is this to go into a separate ticket/PR?

The "final" tuning is going into a separate pr, which I would like to start soon.

**Comment by fredrik-johansson** [comment]
+1

**Pull request merged**
