### PR TITLE
Attempt to fix when mpf_get_d_2exp uses a 64 bit integer.

### LINKED ISSUE #878: Test failure in fmpz_lll-test-t-lll_mpf on Windows
I am building FLINT 2.7.0 on Windows 10 with MSVC (ICC 2018). Compiler shows following warnings:

```
  flint2-2.7.0\fmpz_poly\evaluate_horner_d_2exp.c(54): warning #167: argument of type "mp_limb_signed_t={__int64} *" is incompatible with parameter of type "signed long *"
  flint2-2.7.0\fmpz_lll\check_babai_heuristic.c(106): warning #167: argument of type "mp_limb_signed_t={__int64} *" is incompatible with parameter of type "signed long *" 
  flint2-2.7.0\fmpz_lll\check_babai_heuristic.c(190): warning #167: argument of type "mp_limb_signed_t={__int64} *" is incompatible with parameter of type "signed long *" 
  flint2-2.7.0\fmpz_lll\check_babai_heuristic.c(322): warning #167: argument of type "mp_limb_signed_t={__int64} *" is incompatible with parameter of type "signed long *" 
  flint2-2.7.0\fmpz_lll\check_babai_heuristic.c(415): warning #167: argument of type "mp_limb_signed_t={__int64} *" is incompatible with parameter of type "signed long *" 
```

Then test 684 (fmpz_lll-test-t-lll_mpf) freezes.

I suspect this issue is related to #265.

### PR DESCRIPTION
**Pull request by wbhart**
Fixes #878

### CODE REVIEW

**Comment by tthsqe12** [comment]
If by `unconditionally` you mean `regardless of what mpir is doing` then it seems to make sense.
The msvc compiler reports fewer warnings now :+1:

**Comment by wbhart** [comment]
Yes, that's essentially what I mean. Previous versions of MPIR do what we do, so it doesn't matter if we use their version or ours (of course ours has the prefix flint_ to prevent duplicate symbols).

**Comment by wbhart** [comment]
So I will merge this when appveyor is done, and will do a 2.7.1.

**Comment by tthsqe12** [comment]
> So I will merge this when appveyor is done, and will do a 2.7.1.

Can you also at least increase the number of factors in the fmpz_mod_poly_factor tests? The initial alloc is zero now, so any alloc bugs should be caught, but this is no guarantee

**Comment by wbhart** [comment]
Yes, if if just means changing some 5's to 6's in the tests, I can have a go at that. I'll do it now.

**Pull request merged**
