### PR TITLE
Remove redundant declarations

### PR DESCRIPTION
**Pull request by videlec**
The headers contain a lot of redundant declarations. We remove them and check in the CI that there is none.

### CODE REVIEW

**Comment by videlec** [comment]
CI complains also for other reason (because of `-Werror`)
```
error: logical not is only applied to the left hand side of this comparison [-Werror,-Wlogical-not-parentheses]

PASS

        if (!fmpz_is_one(roots->poly[i].coeffs + 1) != 0)
```
Am I allowed to add parenthesis?

**Comment by tthsqe12** [comment]
This is going to have conflicts with a large PR that I just finished. It is necessary to have this right away?
I will fix the `if (!fmpz_is_one(roots->poly[i].coeffs + 1) != 0)`

**Comment by videlec** [comment]
No emergency at all. It is just that these redundencies generated a lot of warnings in an other project of mine.

**Comment by wbhart** [comment]
@tthsqe12 Is this ok for @videlec to rebase now?

**Comment by tthsqe12** [comment]
sure. I am glad you did mine first. :)
Do you really want -Wredundant-decls -Werror in the ci?

**Comment by wbhart** [comment]
@tthsqe12 I think we do want -Wredundant-decls

By the way, in current flint/trunk there is a problem with the include of "n_poly.h". Perhaps it needs to be "flint/n_poly.h" or something like that.

**Comment by wbhart** [comment]
@videlec Could you rebase this now. Also, I think we are ok with -Wredundant-decls. But I don't think we are agreed in -Werror for now. Could you remove that. We will tend to pick up the warnings and deal with them over time.

**Comment by videlec** [comment]
doing the rebase now. `-Werror` is very useful to fix them (and also prevent anybody from adding new ones)

**Comment by videlec** [comment]
Who is looking at the warnings in the CI? To my mind it does not make sense to have `-Wredundant-decls` without `-Werror`.

**Comment by tthsqe12** [comment]
I look at the warnings in ci (c.f. https://github.com/wbhart/flint2/pull/827#issuecomment-679153224). But, they largely go ignored unless I fix them myself.

**Comment by videlec** [comment]
Anyway, I am not a maintainer of flint so I will definitely follow what you decide concerning the flags.

**Comment by tthsqe12** [comment]
Yeah, If you turned on -Werror, I think our msvc builds would be completely broken. :)

**Comment by wbhart** [comment]
We see the warnings when we build Flint for ourselves. Or have you only enabled them in CI?

**Comment by videlec** [comment]
The branch uses `CFLAGS="-Wredundant-decls"` in `travis.yml` but does not change anything else.

**Comment by wbhart** [comment]
Oh I see. Yeah that's ok then, so long as it passes now.

**Comment by videlec** [comment]
I don't understand the comment at https://github.com/wbhart/flint2/blob/trunk/fmpz/test/t-out_inp_raw.c#L31. If `fdopen` is available this makes a double declaration and if it is not available the code is broken anyway...

**Comment by tthsqe12** [comment]
We will find out tomorrow if this last commit passes. The tests take a long time to run.

**Comment by wbhart** [comment]
I don't understand either, but presumably it is optionally compiled in stdio.h and doesn't appear if the -ansi flag is used.

**Comment by videlec** [comment]
At least tests pass in CI :-)

**Pull request merged**
