### PR TITLE
`fmpz_mul` speedup

### PR DESCRIPTION
**Pull request by albinahlback**
The changes for `fmpz_mul_[si/ui]` are simple; I just made the `ui`-version as the previous change to the `si` version and then changed `flint_mpz_mul_[si/ui]` to `mpz_mul_[si/ui]`.

For `fmpz_mul`, I was able to obtain the following speedup:
```
5 bits:      min 1.04x,    max 1.03x
10 bits:      min 1.04x,    max 1.04x
15 bits:      min 1.04x,    max 1.04x
20 bits:      min 1.04x,    max 1.04x
25 bits:      min 1.04x,    max 1.04x
30 bits:      min 1.04x,    max 1.03x
35 bits:      min 1.04x,    max 1.04x
40 bits:      min 1.04x,    max 1.04x
45 bits:      min 1.04x,    max 1.04x
50 bits:      min 1.03x,    max 1.04x
55 bits:      min 1.03x,    max 1.03x
60 bits:      min 1.03x,    max 1.03x
65 bits:      min 1.02x,    max 1.01x
70 bits:      min 1.00x,    max 1.00x
75 bits:      min 0.99x,    max 0.98x
80 bits:      min 0.98x,    max 0.98x
85 bits:      min 0.98x,    max 1.01x
90 bits:      min 0.97x,    max 0.97x
95 bits:      min 0.96x,    max 0.96x
100 bits:      min 0.96x,    max 0.96x
105 bits:      min 0.96x,    max 0.96x
110 bits:      min 0.95x,    max 0.96x
115 bits:      min 0.96x,    max 0.96x
120 bits:      min 0.96x,    max 0.97x
125 bits:      min 0.96x,    max 0.95x
130 bits:      min 0.96x,    max 0.95x
135 bits:      min 0.95x,    max 0.94x
140 bits:      min 0.95x,    max 0.95x
145 bits:      min 0.96x,    max 0.95x
150 bits:      min 0.96x,    max 0.96x
```
which can be compared to when I benchmarked the old version:
```
5 bits:      min 0.84x,    max 0.83x
10 bits:      min 0.84x,    max 0.82x
15 bits:      min 0.84x,    max 0.83x
20 bits:      min 0.84x,    max 0.84x
25 bits:      min 0.84x,    max 0.83x
30 bits:      min 0.84x,    max 0.83x
35 bits:      min 0.84x,    max 0.84x
40 bits:      min 0.84x,    max 0.84x
45 bits:      min 0.85x,    max 0.85x
50 bits:      min 0.85x,    max 0.85x
55 bits:      min 0.85x,    max 0.83x
60 bits:      min 0.86x,    max 0.86x
65 bits:      min 0.87x,    max 0.86x
70 bits:      min 0.87x,    max 0.87x
75 bits:      min 0.87x,    max 0.87x
80 bits:      min 0.87x,    max 0.88x
85 bits:      min 0.88x,    max 0.89x
90 bits:      min 0.88x,    max 0.88x
95 bits:      min 0.88x,    max 0.89x
100 bits:      min 0.88x,    max 0.88x
105 bits:      min 0.89x,    max 0.88x
110 bits:      min 0.89x,    max 0.88x
115 bits:      min 0.89x,    max 0.89x
120 bits:      min 0.89x,    max 0.88x
125 bits:      min 0.89x,    max 0.90x
130 bits:      min 0.89x,    max 0.89x
135 bits:      min 0.90x,    max 0.89x
140 bits:      min 0.90x,    max 0.90x
145 bits:      min 0.90x,    max 0.90x
150 bits:      min 0.90x,    max 0.90x
```
Note: Both of these benchmarks was made with this PR's version of `fmpz_mul_si`.

### CODE REVIEW

**Comment by albinahlback** [comment]
Btw, is there a reason why `flint_mpz_mul_si` is defined the way it is?

**Comment by albinahlback** [comment]
I fused `fmpz_zero` and the promotion together as I did in `fmpz_mul` since it is slightly faster.

**Comment by fredrik-johansson** [comment]
The flint_mpz_si/ui functions are necessary, because GMP's mpz_si/ui versions only take 32-bit input on 64-bit Windows.

**Comment by albinahlback** [comment]
Then it seems to be a good idea to redefine the function `flint_mpz_mul_[si/ui]`.

I am thinking of something like
```c
static __inline
flint_fmpz_mul_si(mpz_ptr res, mpz_srcptr a, slong b)
{
#if defined(_WIN64)    <--- I am not sure what to write here in order to cover everything that behaves like 64-bit Windows in this regard
    as defined earlier
#else
    mpz_mul_si(res, a, b);
#endif
}
```

**Comment by albinahlback** [comment]
Or can't one just compare `GMP_LIMB_BITS` and `FLINT_BITS`? Or will weird stuff happen for Nemo and such?

**Comment by fredrik-johansson** [comment]
Actually when WORD_MAX != LONG_MAX.

We don't support FLINT_BITS != GMP_LIMB_BITS at all.

**Comment by albinahlback** [comment]
> Why do you believe flint_mpz_mul_ui is not defined to be mpz_mul_ui when FLINT_BITS == GMP_LIMB_BITS? It should be already. See gmpcompat.h.
> […](#)
> On Sun, 5 Dec 2021 at 23:05, Albin Ahlbäck ***@***.***> wrote: Or can't one just compare GMP_LIMB_BITS and FLINT_BITS? Or will weird stuff happen for Nemo and such?

Sorry for this, I missed the macros; I will fix this.

**Comment by albinahlback** [comment]
Since FF doesn't seem to be this week, I am just going to let you know that this is finished!

**Comment by wbhart** [comment]
Yeah that was the only thing I was going to look at today. It's a pretty important function, so I want to look pretty close at this one. I'll probably not get to it until Monday now. The weekend beckons.

**Comment by albinahlback** [comment]
Haha, have a nice weekend! ;-)

**Pull request merged**
