### PR TITLE
Added function for strassen matrix multiplication for fmpz_mat 

### PR DESCRIPTION
**Pull request by aaditya-thakkar**
I have created a function for fmpz_mat which multiplies 2 matrices using Strassen-Winograd variant. Also I have updated profiler for matrix multiplication and the default multiplication method too for better performance of the matrix multiplication. 

Please review it and suggest if there are any problems or changes that are to be made. Thanks.

### CODE REVIEW

**Comment by wbhart** [comment]
Great. I'm interested to see the timings in the region strassen is being used.

**Comment by aaditya-thakkar** [comment]
@wbhart ,Is there any issue still remaining?

**Comment by wbhart** [comment]
No, but we need to see timings that show strassen is faster over much of the region where it is now being used. If it is always slower than the existing code there would be no reason to merge it.

Note that it can still be slower and still not be "BAD" according to the benchmark. The benchmark only checks that the other routines are not more than 30% faster than strassen, not that strassen is ever actually faster. We'd also need to see how much faster it is. If the improvement is lost in the timing variation then again it's probably not worth merging.

The only way to know is to actually print the timings for all the mul algorithms, in the region where strassen is now being used, and we can have a look.

**Comment by aaditya-thakkar** [comment]
screenshot from 2016-02-02 22-20-03
strassen1
strassen2

**Comment by aaditya-thakkar** [comment]
Here are some regions between 650 bits to 2000 bits and for different dimensions where strassen is being used and is faster than any other routine.

**Comment by wbhart** [comment]
Which columns correspond to which algorithms?

**Comment by aaditya-thakkar** [comment]
1st column is for default mul.c 
2nd is for fmpz_mat_mul_classical()
3rd is for fmpz_mat_mul_classical_inline()
4th is for _fmpz_mat_mul_multi_mod()
5th one is for fmpz_mat_mul_strassen().

**Comment by wbhart** [comment]
Indeed there are some very good speedups in there.

There are just some very small changes I've just noticed. After you fix them I will merge this code.

* Can you put Copyright (C) before your name in mul.c
* Can you remove the #includes for stdlib, stdio and limits.h from the test code and implementation. These are just left over from a time when we needed these
* In mul.c can you replace tabs with four spaces and ensure four spaces are used for indent everywhere
* can you put a space after all "if" and "else" keywords in mul.c and p-mul.c
* there are two blank lines after FLINT_TEST_INIT. Can you remove one of them (these are left over from some cut'n'paste we did a long time ago).

That's all I can see. All very minor.

**Comment by aaditya-thakkar** [comment]
Thanks for your great response. It was great working under your guidance and assistance. I have applied changes to the code regarding indentation, spaces and also the copyright thing. Thanks a lot for your help and guidance.

**Comment by wbhart** [comment]
Thanks. I am still seeing some incorrect indenting in mul.c and you forgot to remove the unnecessary #includes that I mentioned in two files.

**Comment by aaditya-thakkar** [comment]
Sorry I forgot to remove it from strassen_mul.c . But I have just a simple doubt that isn't it necessary for the test file?

**Comment by wbhart** [comment]
Yes I'm sorry, I missed abort and fflush, so you need the first two. However, what is limits.h needed for?

**Comment by wbhart** [comment]
Also, I just noticed that you should have flint_test_multiplier() not 10 in the loops in the test code.

**Comment by aaditya-thakkar** [comment]
No need for limits.h , I checked it. let me remove it and also where did I miss the indentation in mul.c? I am unable to track that out.

**Comment by wbhart** [comment]
The brace on line 75 doesn't line up with the brace on line 73. Take a look at your pull request on GitHub under Files Changed to see what it looks like:

https://github.com/wbhart/flint2/pull/218

**Comment by aaditya-thakkar** [comment]
Corrected it.

**Comment by wbhart** [comment]
There are still tabs in the file instead of spaces. And some of the indenting looks like 3 spaces not 4. Are you editing in a terminal or something with a fixed width font?

**Comment by aaditya-thakkar** [comment]
My bad, Sorry for the silly mistakes. I got confused because when I pushed it in my repo, and preview it , it was still showing 1 space more than that was showing in the edit mode.

**Comment by wbhart** [comment]
It's probably easier to see the misalignments here:

https://github.com/aaditya-thakkar/flint2/blob/trunk/fmpz_mat/mul.c

If you hold your mouse button down and roll over the spaces you will see big jumps where there are tabs. For example before the first "else".

**Comment by wbhart** [comment]
Alternatively you can just run indent as per the instructions in code_conventions.txt, if you have indent on your machine. It should fix the spacing issues automatically for you I believe.

**Comment by aaditya-thakkar** [comment]
I hope this is what is needed.

**Comment by wbhart** [comment]
It looks correct now, thanks. I will merge it.

**Comment by aaditya-thakkar** [comment]
@wbhart Thanks a lot.

**Comment by fredrik-johansson** [comment]
Minor thing: strassen_mul.c should be mul_strassen.c

**Comment by wbhart** [comment]
Oh yes, I missed that. I'll fix it later today, unless aaditya can make a PR to fix it.

**Comment by aaditya-thakkar** [comment]
should I just rename it and make a PR?

**Pull request merged**
