### PR TITLE
Speed up nmod multiplications

### PR DESCRIPTION
**Pull request by fredrik-johansson**
```
OLD nmod_mul:          14.7 c/l
NEW nmod_mul:          10.9 c/l   (1.35x speedup)
NEW _nmod_mul_fullword:  8.4 c/l   (1.75x speedup)

OLD nmod_vec_scalar_mul, bits <= 63, len == 4:   17.6 c/l
NEW nmod_vec_scalar_mul, bits <= 63, len == 4:   13.0 c/l   (1.35x speedup)

OLD nmod_vec_scalar_mul, bits <= 63, len == 128:  5.1 c/l
NEW nmod_vec_scalar_mul, bits <= 63, len == 128:  5.1 c/l   (1.00x speedup)

OLD nmod_vec_scalar_mul, bits == 64, len == 4:   17.6 c/l
NEW nmod_vec_scalar_mul, bits == 64, len == 4:   10.4 c/l   (1.69x speedup)

OLD nmod_vec_scalar_mul, bits == 64, len == 128: 21.6 c/l
NEW nmod_vec_scalar_mul, bits == 64, len == 128:  9.8 c/l   (2.20x speedup)

OLD nmod_vec_scalar_addmul, bits <= 32, len == 4:   19.7 c/l
NEW nmod_vec_scalar_addmul, bits <= 32, len == 4:   14.7 c/l   (1.34x speedup)

OLD nmod_vec_scalar_addmul, bits <= 32, len == 128: 14.4 c/l
NEW nmod_vec_scalar_addmul, bits <= 32, len == 128:  9.0 c/l   (1.60x speedup)

OLD nmod_vec_scalar_addmul, bits <= 63, len == 4:   18.8 c/l
NEW nmod_vec_scalar_addmul, bits <= 63, len == 4:   14.7 c/l   (1.28x speedup)

OLD nmod_vec_scalar_addmul, bits <= 63, len == 128: 21.4 c/l
NEW nmod_vec_scalar_addmul, bits <= 63, len == 128:  9.0 c/l   (2.38x speedup)

OLD nmod_vec_scalar_addmul, bits == 64, len == 4:   18.8 c/l
NEW nmod_vec_scalar_addmul, bits == 64, len == 4:   13.2 c/l    (1.42x speedup)

OLD nmod_vec_scalar_addmul, bits == 64, len == 128: 21.4 c/l
NEW nmod_vec_scalar_addmul, bits == 64, len == 128: 13.4 c/l    (1.60x speedup)
```

Comments:
* This is on an ancient laptop (haswell). Someone should verify the results on a newer machine.
* _nmod_mul_fullword is significantly faster than nmod_mul, but I don't think it's worth a branch in nmod_mul to check for this case. Might be better to use this in specific multiplication-dependent functions.
* I tried half-word modulus versions but saw no speedups. Might require use of vector instructions.
* It remains to fix a lot of n_mulmod2_preinv uses.
* Not sure if nmod_mul should be inline. We might want two versions; one for speed, another for code size.
* Can we do addmul faster (avoiding some conditional in the end)? What about addmul with mul_shoup?
* Can we extend mul_shoup to bits == 64?

### CODE REVIEW

**Comment by fredrik-johansson** [comment]
Small improvement in nmod_mat_lu after increasing the basecase cutoff:

```
b = 2  n = 2      6.11e-08    5.98e-08        (1.02x speedup)
b = 2  n = 4      7.24e-07    2.19e-07   (3.31x speedup)
b = 2  n = 8      2.76e-06    1.14e-06   (2.42x speedup)
b = 2  n = 16      1.03e-05    6.81e-06   (1.51x speedup)
b = 2  n = 32      4.04e-05    3.12e-05   (1.29x speedup)
b = 2  n = 64      0.00018     0.000157   (1.15x speedup)
b = 2  n = 128      0.00073     0.000665   (1.10x speedup)
b = 2  n = 256      0.00375     0.0037   (1.01x speedup)
b = 4  n = 2      7.59e-08    7.4e-08   (1.03x speedup)
b = 4  n = 4      7.14e-07    2.64e-07   (2.70x speedup)
b = 4  n = 8      3.13e-06    1.23e-06   (2.54x speedup)
b = 4  n = 16      1.11e-05    6.84e-06   (1.62x speedup)
b = 4  n = 32      4e-05       3.39e-05   (1.18x speedup)
b = 4  n = 64      0.000167    0.000144   (1.16x speedup)
b = 4  n = 128      0.000779    0.000688   (1.13x speedup)
b = 4  n = 256      0.00392     0.00368   (1.07x speedup)
b = 8  n = 2      1e-07       8.8e-08   (1.14x speedup)
b = 8  n = 4      7.66e-07    2.82e-07   (2.72x speedup)
b = 8  n = 8      3.09e-06    1.37e-06   (2.26x speedup)
b = 8  n = 16      1.08e-05    7.14e-06   (1.51x speedup)
b = 8  n = 32      4.08e-05    3.35e-05   (1.22x speedup)
b = 8  n = 64      0.000174    0.000154   (1.13x speedup)
b = 8  n = 128      0.000813    0.000719   (1.13x speedup)
b = 8  n = 256      0.00431     0.00412   (1.05x speedup)
b = 16  n = 2      1.76e-07    1.59e-07   (1.11x speedup)
b = 16  n = 4      8.39e-07    3.68e-07   (2.28x speedup)
b = 16  n = 8      3.1e-06     1.66e-06   (1.87x speedup)
b = 16  n = 16      1.11e-05    7.35e-06   (1.51x speedup)
b = 16  n = 32      4.39e-05    3.75e-05   (1.17x speedup)
b = 16  n = 64      0.000193    0.000175   (1.10x speedup)
b = 16  n = 128      0.00103     0.000939   (1.10x speedup)
b = 16  n = 256      0.00581     0.00578   (1.01x speedup)
b = 32  n = 2      2.18e-07    2.14e-07   (1.02x speedup)
b = 32  n = 4      1.07e-06    5.79e-07   (1.85x speedup)
b = 32  n = 8      3.76e-06    1.86e-06   (2.02x speedup)
b = 32  n = 16      1.36e-05    1.04e-05   (1.31x speedup)
b = 32  n = 32      5.89e-05    4.53e-05   (1.30x speedup)
b = 32  n = 64      0.000258    0.000218   (1.18x speedup)
b = 32  n = 128      0.00131     0.00123   (1.07x speedup)
b = 32  n = 256      0.00786     0.0077   (1.02x speedup)
b = 60  n = 2      4.16e-07    4.1e-07   (1.01x speedup)
b = 60  n = 4      1.37e-06    8.73e-07   (1.57x speedup)
b = 60  n = 8      4.47e-06    2.43e-06   (1.84x speedup)
b = 60  n = 16      1.51e-05    1.07e-05   (1.41x speedup)
b = 60  n = 32      6.26e-05    5.15e-05   (1.22x speedup)
b = 60  n = 64      0.000313    0.000258   (1.21x speedup)
b = 60  n = 128      0.00156     0.00145   (1.08x speedup)
b = 60  n = 256      0.01        0.00915   (1.09x speedup)
b = 64  n = 2      4.81e-07    4.78e-07   (1.01x speedup)
b = 64  n = 4      1.45e-06    9.08e-07   (1.60x speedup)
b = 64  n = 8      4.59e-06    2.53e-06   (1.81x speedup)
b = 64  n = 16      1.66e-05    1.036e-05   (1.60x speedup)
b = 64  n = 32      6.97e-05    5.2e-05   (1.34x speedup)
b = 64  n = 64      0.00034     0.000278   (1.22x speedup)
b = 64  n = 128      0.002       0.00162   (1.23x speedup)
b = 64  n = 256      0.0108      0.0107   (1.01x speedup)
```

Of course, lu_classical should really be doing delayed reduction, which should give a much bigger speedup.

**Comment by wbhart** [comment]
Looks good. So is the main idea here to use prenormalised values or something, which is made possible by putting the data in the mod struct?

**Comment by fredrik-johansson** [comment]
Yeah, I should document everything, of course.

The old code basically did umul_ppmm followed by NMOD_RED2. The problem with this is that NMOD_RED2 has to do a bunch of shifts by the norm, some of which involve the double-word input. The new nmod_mul just shifts one operand before doing the umul_ppmm. It's the same thing as n_mulmod_preinv.

_nmod_mul_fullword takes out the redundant shifts by 0 completely.

In fact, we should probably also have versions of NMOD_RED2 etc. for moduli of length precisely FLINT_BITS, avoiding the same pointless shifts by 0. It's annoying to add more case distinctions, but looks clearly worth it.

The other big speedup is using Shoup in _nmod_vec_scalar_addmul.

**Comment by fredrik-johansson** [comment]
A further 15% speedup in _nmod_vec_scalar_addmul using branchless additions when bits < FLINT_BITS:

```
NEW nmod_vec_scalar_addmul, bits <= 32, len == 4:   14.1 c/l
NEW nmod_vec_scalar_addmul, bits <= 32, len == 128:  7.8 c/l
NEW nmod_vec_scalar_addmul, bits <= 63, len == 4:   14.1 c/l
NEW nmod_vec_scalar_addmul, bits <= 63, len == 128:  7.8 c/l
```

**Comment by tthsqe12** [comment]
What about an nmod.h and the technically UB in _nmod_add?

**Comment by fredrik-johansson** [comment]
Added nmod_mat_lu_classical with delayed reduction. It gives a good improvement as long as accumulation can be done in one or two limbs, but disappointingly it doesn't save anything with a 63-bit or 64-bit modulus where we need three limbs.

Here is what we have gained for nmod_mat_lu (with random dense input):

    bits   n       flint-2.8   new         speedup
    5      8       2.76e-06    8.27e-07    3.34x
    5      16      1.03e-05    3.45e-06    2.99x
    5      32      4.01e-05    1.68e-05    2.39x
    5      64      0.000166    9.45e-05    1.76x
    5      128     0.000743    0.000512    1.45x
    5      256     0.00379     0.00315     1.20x
    5      512     0.0207      0.0182      1.14x
    5      1024    0.127       0.129       0.98x

    25     8       3.22e-06    1.39e-06    2.32x
    25     16      1.13e-05    4.43e-06    2.55x
    25     32      4.4e-05     1.85e-05    2.38x
    25     64      0.000191    0.000104    1.84x
    25     128     0.000994    0.000567    1.75x
    25     256     0.00574     0.00472     1.22x
    25     512     0.0355      0.033       1.08x
    25     1024    0.242       0.241       1.00x

    60     8       4.23e-06    2.33e-06    1.82x
    60     16      1.5e-05     9.01e-06    1.66x
    60     32      6.15e-05    3.7e-05     1.66x
    60     64      0.000295    0.000207    1.43x
    60     128     0.00155     0.0013      1.19x
    60     256     0.01        0.00845     1.18x
    60     512     0.0602      0.0551      1.09x
    60     1024    0.406       0.397       1.02x

    64     8       4.51e-06    2.43e-06    1.86x
    64     16      1.62e-05    1.004e-05   1.61x
    64     32      6.79e-05    5.06e-05    1.34x
    64     64      0.000328    0.000273    1.20x
    64     128     0.00176     0.00163     1.08x
    64     256     0.0113      0.0101      1.12x
    64     512     0.0693      0.0671      1.03x
    64     1024    0.467       0.467       1.00x


This is just on my machine, with 1 thread and no BLAS.

@tthsqe12 maybe you can check that the various tuning values make sense?

This could also impact tuning for some fmpz_mat functions (modular solving, determinant, etc.).

And yes, I could put things in an nmod.h. Not sure about fixing the UB. Maybe it's only efficient because of that? :-)

**Comment by tthsqe12** [comment]
I can check this tmr on various architectures. UB can always be fixed. FLINT_SIGN_EXT maybe?

**Comment by fredrik-johansson** [comment]
Note: I also tried various combination mpn_add_n or mpn_addmul_1 instead of umul_ppmm+add_ssaaaa/add_sssaaaaaa to batch the row updates and benefit from GMP assembly, but this only ran slower.

This might also mean that the use of mpn_addmul_1 in nmod_poly basecase division is no longer the best approach and that we should use our own loops there. Again, someone should check this on a different machine.

**Comment by tthsqe12** [comment]
Ok, I see the profile codes that have changed here are
```
nmod_vec/profile/p-mul.c
nmod_vec/profile/p-scalar_addmul.c
nmod_vec/profile/p-scalar_mul.c
```
Are these the ones you want me to run? Where are you getting this profile code for nmod_mat_lu?

**Comment by fredrik-johansson** [comment]
Sorry, I was just doing ad hoc tests.

I've added a profiling program now. Feel free to tweak it.

**Comment by fredrik-johansson** [comment]
luspeedup

Speedup vs flint-2.8 for the default algorithm.

**Comment by tthsqe12** [comment]
Well, this is disappointing. The framework in profile.h only works on x86.

**Comment by wbhart** [comment]
There's not a lot of point having profiling code for a bunch of CPUs no one is using in a performance setting. And there's no point having profiling code for a bunch of CPUs we don't tune for. Until the recent Apple M1 nothing was even necessary on ARM.

Adding platform dependent tuning to Flint is a big job. I'm not sure we have the resources for that, as nice as it would be to do.

**Comment by tthsqe12** [comment]
I am not advocating for platform dependent tuning :) I am advocating for platform _in_dependent tuning.

**Comment by wbhart** [comment]
There's no such thing as platform independent tuning. I will merge this PR.

**Pull request merged**
