### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by wbhart** [comment]
Thanks. What about the extern you mentioned?

**Comment by isuruf** [comment]
Looks like `fmpz_poly_factor-test-t-factor` hangs in MSVC 64 bit build

**Comment by wbhart** [comment]
That's a shame. I fixed what I thought would be the most likely cause of that. I haven't a clue why it would be hanging now. I'll have to add in some print statements to see where it is hanging. It's an enormous function.

**Comment by wbhart** [comment]
That's bizarre, the fmpz_poly_factor-test-t-factor still seems to start (and hang) on the commit where you put the SKIP_TEST back in.

**Comment by isuruf** [comment]
Here's the latest run on my fork. https://ci.appveyor.com/project/isuruf/flint2/builds/32322531
I removed the skip test and added a 10 minute timeout

**Comment by wbhart** [comment]
I'm sure I can fix the cmp_ui. That's got to be an easy one.

There don't seem to be any compiler warnings relevant to t-factor. I'll make a branch based on yours, with some prints on that function to see where it is hanging.

**Comment by isuruf** [comment]
There are some warnings suppressed. https://github.com/wbhart/flint2/blob/trunk/appveyor.yml#L50
Maybe we should remove that too.

**Comment by wbhart** [comment]
Probably. However I'm currently tracking down a bizarre memory leak in factor. I have spent ages looking at it and I just don't see what is causing it. Fortunately it is not deep. I'll have to print a pile of pointers to see where one is being overwritten. I live in hope that it is somehow related to the hang, though I doubt it.

**Pull request merged**
