### PR TITLE
n_is_perfect_power and n_primitve_root added

### PR DESCRIPTION
**Pull request by n1tz53**

### CODE REVIEW

**Comment by wbhart** [comment]
Is there any way this could be separated into two pull requests: one for is_perfect_power and one for primitive_root_general?

I am much happier with the primitive_root code than the is_perfect_power code (I need to think long and hard about the algorithm for the latter, or perhaps even try a few different approaches to see which is better in practice). 

The former code is pretty straightforward and can probably be merged without significant issue.

One thing that might be changed is the naming. I think appending _general to function names is a bad idea. We already have a general function I think, namely the one without the _general appended.

We just need a prefactor version. The wrapper of this which first factors and then calls the prefactor version seems superfluous. It can maybe be removed. Or does it provide some other functionality not provided by the other version?

**Comment by n1tz53** [comment]
Yes, I'll create two different pull request. And  the file with  ' _general' was the one i created initially but deleted later, final file is 'n_primitive_root.c'

**Comment by wbhart** [comment]
The primitive_general file still shows up in the pull request. You may have
only rm'd it, not git rm'd it. If so, you can do:

git checkout primitive_root_general.c
git rm primitive_root_general.c
git commit -a
git push

That should get rid of it.

Bill.

**Comment by wbhart** [comment]
Also, the filenames should not have n_ in front of them.

To fix that, do:

git mv n_blah.c blah.c
git commit -a
git push

Bill.

**Pull request closed without merging**
