### PR TITLE
Add CMake build system

### PR DESCRIPTION
**Pull request by xoviat**

### CODE REVIEW

**Comment by wbhart** [comment]
Thanks for picking up the pthread_self issue. But actually the standard says the comparison should be done with pthread_equal. So both of us are wrong.

At the moment CI is failing because the mpir tarball has changed again. I'll have to fix that first.

**Comment by fredrik-johansson** [comment]
A big problem with this is that there are lots of hardcoded files and paths in the build script. Look at the CMake script in Arb -- everything can be detected automatically.

Also some changes are strange, e.g. moving tables into .h files (this shouldn't be necessary, again this was already handled fine in Arb).

**Comment by xoviat** [comment]
I have never personally been able to export data from a DLL using C linkage. The method given here certainly doesn't work, as the tests cannot be built.

> A big problem with this is that there are lots of hardcoded files and paths in the build script. Look at the CMake script in Arb -- everything can be detected automatically.

The CMake arb script is not a model CMake script. Make can do exactly the same thing, but the Makefile doesn't -- why is that?

**Comment by xoviat** [comment]
Also, does anyone know why so many of the tests are failing?

**Comment by wbhart** [comment]
I'm not aware of any failing tests at present. Which ones are you referring
to?

**Comment by isuruf** [comment]
Tests on travis-ci fails because the link http://www.mpfr.org/mpfr-current/mpfr-4.0.0.tar.bz2 is dead.

**Comment by xoviat** [comment]
I'm talking about all of the tests on windows. Previously they weren't even built, but with this PR, they are. However, many of them fail.

**Comment by wbhart** [comment]
I'm confused. We have CI on Windows and it has been passing all tests until
the MPFR tarball went down a few days ago. Perhaps you are using a more
recent version of MSVC than the one supported in trunk?

**Comment by xoviat** [comment]
The CI on windows, as far as I can tell, has not been passing all of the tests. It builds them, but they are not run.

**Comment by xoviat** [comment]
Sorry, it's worse than I thought. Many of them weren't built using the MSBUILD files, but the CI appeared as green.

**Comment by wbhart** [comment]
Many of the tests were not built, for sure. Usually around the time of a
release, someone (Brian Gladman usually), will integrate the tests into the
vcbuild files. Unlike the Flint build system, the MSVC build system
requires intervention every time someone adds a new test or C file.

**Comment by xoviat** [comment]
Yes, well the CMake build system can (and currently does) build and run all of the tests. A significant minority of them currently fail.

**Comment by xoviat** [comment]
CMake can also generate the MSBUILD files automatically, so we could potentially remove the build.vc14 directory.

**Comment by isuruf** [comment]
@xoviat, can you try installing mpir 2.7.2? flint is not yet compatible with mpir 3.0.0

**Comment by wbhart** [comment]
I assume a majority of them are in fmpz_mpoly and mpoly?

These are new modules that have been added recently and they have never
been near MSVC. Someone with skills in porting to MSVC is going to have to
take a look at that code. There are two new modules: nmod_mpoly and
fmpq_mpoly almost ready to go, as well.

Failures outside these modules probably should be brought to our attention.
There is a really significant amount of new code since the last release
(which was years ago), but most of it should be harmless, in theory.

**Comment by wbhart** [comment]
Another big source of failing tests will be people forgetting to put
FLINT_DLL in front of all the relevant prototypes in the .h files.

**Comment by xoviat** [comment]
@isuruf To confirm, can you export a constant from a DLL using C linkage?

**Comment by xoviat** [comment]
@wbhart Do some of the tests require reentrant or gc?

**Comment by wbhart** [comment]
They shouldn't do, but I don't know if the new single memory manager has been tested with MSVC (see the file fmpz/link/fmpz_single.c).

If not, then it might be better to build flint in reentrant mode on MSVC for the time being. Some of the tests are threaded of course.

**Comment by wbhart** [comment]
I should add that single mode requires thread local storage, and I haven't checked it that is available on MSVC.

**Comment by xoviat** [comment]
@wbhart So I think we need some discussion about the scope of this PR. The CMake files as they currently are can build the DLL and tests (although many of them fail), essentially exceeding the capability of the MSBUILD system. The CMake files can also (potentially) generate MinGW Makefies (although the test time limit would be exceeded) and I think gcc Makefiles as well.

I have removed the MSBUILD files in this PR as it currently stands, and have switched the build system over to CMake. Which of these changes are acceptable and which would you like reverted?

**Comment by xoviat** [comment]
Note that CMake can generate MSBUILD files as well, which would cut the release effort from potentially hours to a few minutes (to update the folder list from the Makefile).

**Comment by wbhart** [comment]
I am personally happy if CMake can create the VS files automatically. But
is CMake available in a standard MSVC build environment? It won't be any
use if it requires Windows users to learn about a Linux style environment
just to get the MSVC files.

Perhaps @BrianGladman has some comments on that.

I don't see any real benefits of CMake on MinGW or Linux, so I wouldn't
replace any of that. It could be useful in the future though, if some
problems lead us to having to abandon the Flint build system, or if CMake
becomes some kind of standard that absolutely everyone requires. Of course
it is useful for packaging systems that require CMake (like Hunter, I
believe?)

I had a brief look through the patches, and they looked ok to me. The real
question is about what Windows MSVC users actually want.

**Comment by isuruf** [comment]
> But is CMake available in a standard MSVC build environment?

CMake is bundled with Visual Studio>=2017 and VS 2017 has in-built support for it

**Comment by xoviat** [comment]
Here's [what microsoft has to say](https://docs.microsoft.com/en-us/cpp/ide/cmake-tools-for-visual-cpp) about CMake.

> But is CMake available in a standard MSVC build environment? It won't be any use if it requires Windows users to learn about a Linux style environment just to get the MSVC files.

I think @BrianGladman feels differently than I do, but the two big problems (and I've said this before) with developing native libraries on windows have been:

1. MSVC standards compliance
2. Fragile build systems

MSVC 2015 solved 1) (but for complex numbers) and CMake solved 2). Of [all the open source native libraries](https://github.com/Microsoft/vcpkg/tree/master/ports) on Windows, CMake is used for the vast majority. What that tells you is that previously these libraries required hours of effort to use, which essentially ruled them off-limits for Windows developers.

**Comment by wbhart** [comment]
On 1 March 2018 at 01:15, Isuru Fernando <notifications@github.com> wrote:

> But is CMake available in a standard MSVC build environment?
>
> CMake is bundled with Visual Studio>=2017 and VS 2017 has in-built support
> for it
>
I guess we need to know what proportion of developers are using >= 2017.
But that is great news actually.

**Comment by xoviat** [comment]
Note that older versions of MSVC can still use CMake, they just need to install it separately.

**Comment by BrianGladman** [comment]
Sadly I am not well integrated into the development process for FLINT so I am not surprised that the current Windows build system is failing.  

In order to keep it up-to-date I need those who add new code to FLINT to let me know what they have done so that I can make any changes needed to integrate the new code into the Windows build.  Clearly this hasn't been happening, presumably because no-one has been aware of the need to involve me when such additions are made.

Turning to CMake, I would be very pleased to see CMake added as the cross platform build system for FLINT **provided** that it builds binaries that are fully compliant with the Windows x64 ABI **including** exception handling and stack unwinding.    Maintaining the Windows build system for FLINT is a costly task and no-one would be more pleased than me if this is no longer necessary because we have a cross platform build system. 

Visual Studio has added CMake support in Visual Studio 2017 but it is not yet mature and has been pretty flaky in early releases.  However, It is much improved in recent Visual Studio updates (i.e. 15.5) and certainly looks to offer the prospect of CMake as a fully supported cross platform build system for future use on projects that are pure C and/or C++.   

However, for libraries such as MPIR that involve a lot of assembler code, the choice is less obvious.   MPIR has a complex build system because it is not a pure C/C++ library and has a mass of optimised assembler code that is **Windows specific** and which needs to be analysed and selected depending on the architectures being targeted by the build.    Incorporating what the the existing MPIR Windows build system does into a cross platform CMake build is not an easy task and no-one is volunteering to do this   I have looked at doing this but it requires an in-depth knowledge of CMake that (a) I do not have, and (b) I cannot acquire because the Kitware documentation of CMake is abysmally poor for anything other than simple build requirements.

**Comment by xoviat** [comment]
The build system has nothing to do with the ABI. Since we're still using cl, the ABI hasn't changed (unless there were special flags passed).

**Comment by BrianGladman** [comment]
@xoviat  The build system determines what code is added to a build and what architecture is being targeted.  It was in this sense that I was discussing the Windows ABI.   The issue arises as a result of FLINT's dependence on MPIR.

**Comment by xoviat** [comment]
Typically the user chooses the target. Are you saying there is an issue here though? If so, I do not understand what that might be.

**Comment by BrianGladman** [comment]
I don't think that there is an ABI issue with FLINT but I was simply being careful to state the conditions under which I would support a cross platform CMake build in case it turns out that there is.

**Comment by xoviat** [comment]
@wbhart Does this look okay to merge?

**Comment by wbhart** [comment]
Could you also update the MPFR tarball to 4.0.1 and switch to the Gnu website so that we can see the CI results. I would merge Isuru's patch for this, but I don't want to cause a rebase for you.

**Comment by wbhart** [comment]
Also, the documentation will need to be updated to include instructions on how to use CMake on Linux and Windows. You can just add another section to the docs following the current section on installation.

**Comment by xoviat** [comment]
@wbhart Is that okay?

**Comment by xoviat** [comment]
Actually it's not okay. I need to find the regression.

**Comment by wbhart** [comment]
It's looking good. I'll wait until you sort out the CI before merging. But everything else looks good.

**Comment by xoviat** [comment]
@wbhart Let's put this in.

**Comment by wbhart** [comment]
We used to test on 32 bit mingw. I'm not sure we should drop that, since there's quite a lot of 32 bit specific code. We'll have to restart the Appveyor tests anyway since they didn't complete. Presumably the build servers are under heavy load.

**Comment by wbhart** [comment]
It looks like the 64 bit gcc mingw tests are still looking for the wrong MPFR tarball.

Also, there's a lot of failures that I'm not expecting, e.g. in ulong_extras. They are surely amongst the tests that were passing before.

**Comment by xoviat** [comment]
Obviously there is an issue with the gcc tests. However, you cannot say anything about the cl.exe tests because they weren't run before.

**Comment by wbhart** [comment]
I realise there were some tests that were not run before, but is it really true that none of the cl tests were run before? ulong_extras has been in Flint for many years. I would expect some failures in fmpz_mpoly, which is new, but not in ulong_extras.

**Comment by xoviat** [comment]
It really is correct that none of the cl tests were run before. At some point the tests were *compiled*, but now that's not even correct.

**Comment by isuruf** [comment]
Yeah. None of the tests were run in MSVC. There was an issue with appveyor hanging when running the tests scripts.
Tests were run on MinGW though

**Comment by wbhart** [comment]
Ok, thanks. I wasn't aware of that, or had forgotten. It looks like the tests still hang on MSVC. So let's ignore those. We do need to get the 64 bit MinGW tests working again though. But that is just about the MFPR tarball, I think.

**Comment by xoviat** [comment]
Yes; I'm working on a solution for that.

**Comment by wbhart** [comment]
Thanks!

**Comment by wbhart** [comment]
By the way, the sort of errors that appear in the cl tests look like they would be caused by a bug in longlong.h. Brian had a special version of that file for MSVC I believe.

**Comment by wbhart** [comment]
Why does the ticket keep getting opened and closed. I'm getting hundreds of notifications!

**Comment by xoviat** [comment]
It's to cancel the additional appveyor builds..

**Comment by xoviat** [comment]
@wbhart I have updated the MinGW build system such that it is significantly more robust (the maintenance should be minimal). I have also confirmed that it works [here](https://ci.appveyor.com/project/xoviat/flint2/build/0.2.19.22).

**Comment by wbhart** [comment]
It's looking better. I wonder why some of the threaded tests are failing. They didn't use to fail.

I guess its possible we screwed something up recently.

I will take a final look through the diff and then merge this. Thanks for your hard work.

**Pull request merged**
