### PR TITLE
Changed n_is_pocklington to make it compatible with FLINT32

### PR DESCRIPTION
**Pull request by kush789**

### CODE REVIEW

**Comment by kush789** [comment]
Hi,

I am checking never for flint64 using #if, and accordingly changing the upper limit on limit. This should take care of overflow.

Kushagra

**Comment by kush789** [comment]
I'm sorry it should be "checking for " and not "checking never for ".

**Comment by wbhart** [comment]
Thanks, I have merged this now.

I made a couple of hopefully cosmetic changes. The tests seem to still
pass, but you should check I didn't screw something up.

I agree with Fredrik that it would be nice to implement n_root and
n_rootrem functions which start with a double precision result from pow and
return floor of the nth root (with remainder in the case of rootrem). We
could then use it in this code.

Of course we'd have to consider the case that pow returns a value that is
too high. This is also possible, though it doesn't affect the Pocklington
code.

**Comment by kush789** [comment]
Hi

I have been working on the rootrem function as you had suggested earlier, although i have been getting some issues related to its speed. The newton iteration method seems to be a lot slower than the method implemented in gmp. On further inspection I noticed that gmp does'nt use newton iteration, but a different algorithm. Hopefully I'll manage to get it faster and push it in a few days for a code review.

Kushagra

**Comment by fredrik-johansson** [comment]
It would probably be fastest to use an approximate double precision Newton iteration and fix up the result exactly as a last step. Newton iteration can be very sensitive to the choice of initial value. I think it might work best to start with a value that is within a factor two of the correct result and slightly too large  (something like x^(1/n) ~= 2^ceil(bitlength(x)/n)) and possibly also doing 1-2 initial refinements with binary search.

**Comment by wbhart** [comment]
Just out of interest, how many iterations is your Newton iteration taking
for various sized inputs? That could be a clue to efficiency.

It hadn't occurred to me that GMP would be hard to beat. I assumed the
bignum overhead would be substantial. But of course it will if it has a
highly optimised implementation for a single word.

If at the end of it all we find that doing an fmpz_set_si, fmpz_rootrem and
fmpz_get_ui is the fastest, then that is maybe what we have to do.

We could also directly call the mpn code in GMP, but it's not part of the
standard interface and we'd have to special case it for all the different
interfaces GMP and MPIR have had in the versions we support, I'm not even
sure it always was mpn code in those versions.

Anyway, it's a hard challenge, but there are other ways to handle it if we
don't find a really fast implementation ourselves.

We could also use old GMP code directly in flint, GMP 4.2.1 and prior, if I
recall correctly. The license was compatible back then. I don't think the
code was all that fast back then though. This is probably my least
preferred option.

**Pull request merged**
