### PR TITLE
4walt

### PR DESCRIPTION
**Pull request by walt343**

### CODE REVIEW

**Comment by wbhart** [comment]
Hi Dan,

this looks interesting. However a couple of binary files fmpz_sparse/test/t-add and t-sub seem to have been committed.

I guess we will need to go through and rename everything to fmpz_laurent_poly_sparse or fmpz_laurent_spoly or something like that, though I can totally see why you didn't want to develop it with a long name like that.

We obviously also have to do a little bit of work on the documentation, which isn't in the same format as the other modules in Flint yet.

I guess the first natural question is: why Laurent polynomials before polynomials?

**Comment by wbhart** [comment]
Actually I guess we can just call the module fmpz_spoly since it is just ordinary polynomials that happen to allow negative powers. If people want to use it as sparse polynomials rather than sparse Laurent polynomials, nothing will stop them I think.

**Comment by walt343** [comment]
Hello Dr. Hart,

I actually am not Dan. I am Whitman and I am working with Dan on our own
Flint module. I accidentally made a pull request when trying to pull a
branch myself. I apologize for the inconvenience!

**Comment by wbhart** [comment]
Ah I understand. Of course if you do want to do a pull request at some point, please do!

**Comment by walt343** [comment]
We look forward to it!

**Pull request closed without merging**
