### PR TITLE
Improved n_randint implementation in ulong_extras module to get uniformly distributed random values

### PR DESCRIPTION
**Pull request by apoorv-mishra**
Hi,

I made this pull request in order to improve the n_randint implementation which was required for ulong_extras module. Discussion thread is [here](https://groups.google.com/forum/#!topic/flint-devel/27LVpC2wlBM)

Thanks,
Apoorv

### CODE REVIEW

**Comment by wbhart** [comment]
Thanks Apoorv. We aren't sure yet whether we want to replace the current n_randint or have a new function specially for uniformly random values.

I think your editor might be set to use tabs instead of four spaces. When I look at the code in GitHub there are some really large indents. Perhaps you can change how your editor is set up and use four spaces everywhere there is currently a tab.

Also, you are currently doing rand_max / limit, whereas your original algorithm called for (rand_max + 1)/limit. So I think that is a bug.

I think you should also write test code for this function to try and test some cases to ensure that it is really giving uniformly random values, as this would test that your algorithm is correct. Of course you will have to think very carefully about how to write such tests. You can probably only make the test code work in the case where limit is very small, otherwise it will take too long to generate sufficient data to be statistically significant.

Also, in Flint we put spaces after keywords like "while". We usually don't put spaces before and after *and /, and instead only put spaces before and after + and -. This groups factors together, but separates terms. It's just a convention that we use, it's not really important. And some C programmers will do this quite differently to us.

The documentation will also need updating when we decide whether to have a separate function, or just change the existing function. And you should put your copyright at the top of the files you nontrivially change.

**Comment by apoorv-mishra** [comment]
Hi @wbhart, I made minor changes that you mentioned. Though, there are a couple of issues regarding the implementation which I would like to address -

1. The `is_strong_probabprime2_preinv` test fails with this implementation. I investigated it and the reason was that the value of `count` in `t-is_strong_probabprime2_preinv.c` exceeds the benchmark value of `220 * flint_test_multiplier()`(It comes out to be 2255). The test basically passed more composites(as probable primes) than intended. I don't know the reason for this though. Is it because of "better" randomness produced by new implementation?

2. The above test passes when I decrease the `rand_max` value to `WORD_MAX`. Again, I don't know the reason for this. But that would naturally fail other tests since the value of `limit` can be at most `UWORD_MAX`.

Also, as you mentioned,

> Also, you are currently doing rand_max / limit, whereas your original algorithm called for (rand_max + 1)/limit. So I think that is a bug.

I don't think, that's a problem since the value of `limit` can be atmost `UWORD_MAX`, which is asking for a random number in range [0, UWORD_MAX - 1]. The maximum size of the range can therefore be `UWORD_MAX` which is what `rand_max` is set to. Please correct me if I'm wrong.

Thanks,
Apoorv

**Comment by wbhart** [comment]
On 11 August 2017 at 16:31, Apoorv Mishra <notifications@github.com> wrote:

> Hi @wbhart <https://github.com/wbhart>, I made minor changes that you
> mentioned. Though, there are a couple of issues regarding the
> implementation which I would like to address -
>
>    1.
>
>    The is_strong_probabprime2_preinv test fails with this implementation.
>    I investigated it and the reason was that the value of count in
>    t-is_strong_probabprime2_preinv.c exceeds the benchmark value of 220 *
>    flint_test_multiplier()(It comes out to be 2255). The test basically
>    passed more composites(as probable primes) than intended. I don't know the
>    reason for this though. Is it because of "better" randomness produced by
>    new implementation?
>
>
I suspect that is all it is. Probably the 220 needs to be increased a
little, e.g. to 250, when you have truly uniformly random values.

>
>    1.
>    2.
>
>    The above test passes when I decrease the rand_max value to WORD_MAX.
>    Again, I don't know the reason for this. But that would naturally fail
>    other tests since the value of limit can be at most UWORD_MAX.
>
> Also, as you mentioned,
>
> Also, you are currently doing rand_max / limit, whereas your original
> algorithm called for (rand_max + 1)/limit. So I think that is a bug.
>
> I don't think, that's a problem since the value of limit can be atmost
> UWORD_MAX, which is asking for a random number in range [0, UWORD_MAX -
> 1]. The maximum size of the range can therefore be UWORD_MAX which is
> what rand_max is set to. Please correct me if I'm wrong.
>

Sure, consider the case where limit = 2. It's the difference between
rand_max / 2 and (rand_max + 1)/2. Only one of these is correct. One will
give uniformly random values, the other will not.

**Comment by apoorv-mishra** [comment]
> Sure, consider the case where limit = 2. It's the difference between
> rand_max / 2 and (rand_max + 1)/2. Only one of these is correct. One will
> give uniformly random values, the other will not.

Yeah, I missed that. Thanks for pointing out. I guess we would run into problems when `limit` equals some power of 2. But, `rand_max + 1` would overflow. What's the fix according to you?

**Comment by wbhart** [comment]
You have to check for the case rand_max + 1 = 0 (which means there was an
overflow), and deal specially with it.

**Comment by apoorv-mishra** [comment]
`rand_max + 1` will always overflow since `rand_max` equals `UWORD_MAX`. What if I use fmpz module for carrying out the arithmetic to deal with the overflow problems? Would it be that efficient? Please give your thoughts on this approach.

**Comment by wbhart** [comment]
Oh yes, you are right. Well, you can just do some bit twiddling hacks to do the division correctly. You definitely don't need to use multiprecision integers for this.

**Comment by apoorv-mishra** [comment]
Well, it's not just about the division here. The value of `(rand_max + 1)/limit` which is stored in `x` might also overflow(when limit = 1). So, I guess we might have to fall back to fmpz module. I'm not fully sure though.

**Comment by wbhart** [comment]
You just deal with that corner case separately.

**Comment by apoorv-mishra** [comment]
Hi, @wbhart , I implemented long division method "partially"(just the first iteration) to circumvent the overflow problem. Please suggest required changes if any.

Thanks,
Apoorv

**Comment by fredrik-johansson** [comment]
Note that in the special case when limit & (limit - 1) == 0, you can just return n_randlimb(state) & (limit - 1). This also subsumes the separate cases for limit == 0 and limit == 1.

I haven't checked the division code.

**Comment by apoorv-mishra** [comment]
> Note that in the special case when limit & (limit - 1) == 0, you can just return 
n_randlimb(state) & (limit - 1). 

Hi @fredrik-johansson , this is basically `n_randlimb(state) % limit`. This approach doesn't sound good to generate uniformly distributed random numbers as far as I know. I guess this was the reason why @wbhart  suggested to change the implementation. Also, this isn't consistent with the other case(`limit & (limit - 1) != 0`) which doesn't employ the "taking modulo" method. May you kindly elaborate, how is this change going to affect the accuracy/efficiency of `n_randlimb`?

**Comment by fredrik-johansson** [comment]
limit & (limit - 1) is checking if limit is a power of two. Since the source of randomness (n_randlimb) is uniformly distributed modulo a power of two (2^64 or 2^32), the low n bits will be uniformly distributed modulo 2^n as well. This is a special case.

**Comment by apoorv-mishra** [comment]
Alright, thanks. I'll make the required changes.

**Comment by wbhart** [comment]
You don't need to do division in the case where limit is a power of 2, just mask off the required number of bits.

Since 1 is a power of 2, you don't need to deal specially with that case.

Since you already dealt with limit = 1 as a power of 2, the division can't overflow now. So you don't need to deal specially with overflow.

Finally, you don't need to do long division to divide UWORD_MAX + 1 by limit. Simply subtract limit and increase the quotient by 1.

**Comment by apoorv-mishra** [comment]
Hi @wbhart , thanks for suggesting improvements.

**Comment by apoorv-mishra** [comment]
Hi @wbhart ,

Please suggest any other improvements and if not, what needs to be done next. Do I need to write a test function? If yes, how would I test that the output produced is statistically uniform?

Apoorv

**Comment by wbhart** [comment]
This looks good now.

We've decided that we want this to be a new function, rather than a replacement for the old. It should be called n_urandom_int.

The test function should test the function for a range of small positive values of limit (say up to limit = 1000). For each value of limit, we could compute the deviation in the numbers of outputs of the function with each given value in [0, limit). This deviation should be relatively constant no matter how many times we call the function. It's probably good enough to check that the deviations for limit outputs, 2*limit outputs, 3*limit outputs, ..., and limit^2 outputs are all within a factor of 2 of the largest of those deviations. This means computing limit^2 values for each value of limit. 

Also, don't forget to add a prototype to ulong_extras.h and documentation in ulong_extras/doc/

**Comment by fredrik-johansson** [comment]
It's only feasible to detect deviations for really large limits.

For example, I tried 10^6 values of the current n_randint with limit = 1000 and got  499731 values smaller than limit/2, 500269 values larger or equal to limit/2.

But with limit = UWORD_MAX / 3 * 2, I got 665979 values smaller than limit/2, and 334021 values larger. This would be reliably measurable with just 1000 samples.

The test code needs to invoke arbitrary limits anyway... if not to test the statistical properties (which it should) then at least just to make sure the code doesn't divide by zero or anything!

By the way, when this is available we should use it in fmpz_randm and perhaps some other places.

**Comment by wbhart** [comment]
I wasn't recommending detecting deviation in the outputs of the function, but deviations in the number of outputs (for a given limit) of each value up to limit.

Admittedly I didn't try this out myself, and I'm certainly happy to use a much larger number of trials for each limit (than limit^2), but I think you really want to try to detect the case where some output value is hit way more often than it should be.

**Comment by wbhart** [comment]
Yeah I see what you mean. Unless limit is very large, you aren't going to be able to see any problem because the random noise will swamp the extra one or two times a certain value gets hit.

In fact, I think it is hard to detect for either small or large limits. If limit is small, you can't detect the excess, for a large limit, you have too many values to count.

So what we need to do is break the range [0, limit) (for a large limit) down into a smaller number of "subranges", i.e. not limit subranges, but 2 subranges as you did, or some small number of subranges, for which it is easy to count the number of values in each subrange, for a large number of trials.

**Comment by wbhart** [comment]
Actually, this isn't the right way to look at it. We should certainly check that for a small limit, one of the possible values doesn't get hit much more often than the others. Although the original function didn't have this problem, perhaps we've replaced it with one that does.

So we should do a test for both small and large values of limit.

**Comment by apoorv-mishra** [comment]
Hi @wbhart ,

Apologies for late reply.

I ran the new n_urandint function 10^6 times with limit = 1000 and got 498576 values smaller than limit/2, 501424 values larger or equal to limit/2. Also, for limit = UWORD_MAX / 3 * 2, I got 498804 values smaller than limit/2 and 501196 values greater than or equal to limit/2. I think that's a good sign.

I haven't completely tested the function though as mentioned by you. I have got a couple of doubts regarding one of your previous comments.

> For each value of limit, we could compute the deviation in the numbers of outputs of the function with each given value in [0, limit). This deviation should be relatively constant no matter how many times we call the function. It's probably good enough to check that the deviations for limit outputs, 2xlimit outputs, 3xlimit outputs, ..., and limit^2 outputs are all within a factor of 2 of the largest of those deviations. This means computing limit^2 values for each value of limit.

Are you implying that we compute the occurrences of each of the values in range [0, limit) for each of limit, 2xlimit, 3xlimit, ..., and limit^2 iterations of n_urandint? If that's the case, how should we compute the deviations(mathematically)? Say, for limit = 1000, we have occ[i] occurrences of i, then are you saying that the deviation would just be the difference of each occ[j](j != i) with occ[i]? Or do we need to choose some central value(like mean or median) in order to calculate the deviation? For the latter case, I guess mean would be a good choice. Please give your suggestions.

Regards,
Apoorv

**Comment by wbhart** [comment]
I'm not suggesting we do that any more. See the subsequent discussion with
Fredrik.

Instead we should break into a small number of subranges. Fredrik's
suggestion is equivalent to breaking into two subranges. But I'd prefer if
we use slightly more than two. Of course then we need to compute his many
we expect in each subrange, since you can't always evenly break the whole
range evenly into a given number of subranges.

**Comment by apoorv-mishra** [comment]
So, we detect randomness only for large limits?

**Comment by apoorv-mishra** [comment]
Ah, I see. So, you mean to say that we break limit into multiple(small) subranges and then count the numbers which lie in those subranges. For example, we break limit into [0, limit/3), [limit/3, 2*limit/3) and [2*limit/3, limit) and then count occurrences of numbers(in range [0, limit) in those subranges. Am I right?

**Comment by wbhart** [comment]
That's correct, yes.

**Comment by apoorv-mishra** [comment]
You approved it for larger values of limit. What about smaller values?

**Comment by wbhart** [comment]
It should be fine in both cases. Of course some subranges will be length
zero when limit is very small.

**Comment by apoorv-mishra** [comment]
Hi @wbhart,

I added the n_urandint function and its test function as well. I compared it against n_randint and found that the deviation was significantly more for n_randint when testing against larger limit values. I think this seems consistent with what we anticipated. I tested the function for 10^4 calls of n_urandint for each of 10^3 values of limit(small and large values separately). Please have a look and suggest any changes if required.

Thanks,
Apoorv

**Comment by wbhart** [comment]
This looks quite good. Thanks for this. I'm currently away, but will be
back soon and will look at this thoroughly in the next couple of days.

**Comment by wbhart** [comment]
The first issue I see is in the test code. You check all the way up to 100 * flint_test_multiplier() but you only allow space for 1000 values in the array you allocate. You should use flint_malloc and flint_free (they work just like malloc and free) to allocate the arrays.

**Comment by wbhart** [comment]
I also wouldn't multiply by flint_test_multiplier in both the outer and inner loops. I would only use it in the inner loop, otherwise increasing flint_test_multiplier by a factor of 10 won't make the tests run 10 times longer, but 100 times.

**Comment by wbhart** [comment]
Also, you will need to take flint_test_multiplier into account when setting the deviation bounds, which should be relatively generous.

**Comment by wbhart** [comment]
I would also set the inner loop bound to a much higher value in the first test, since you are effectively using subranges of length 1, which will make it very hard to detect variations from the expectation.

**Comment by wbhart** [comment]
I think deviation in the second test needs to take flint_test_multiplier into account, as do the bounds. You should try changing flint_test_multiplier to 100 and 1000 temporarily to ensure it passes with a variety of values. You can find it in test_helpers.c. Please set it back to 10 before committing.

**Comment by apoorv-mishra** [comment]
> I would also set the inner loop bound to a much higher value in the first test, since you are effectively using subranges of length 1, which will make it very hard to detect variations from the expectation.

Do you mean to say we increase the bound from `1000 * flint_test_multiplier()` to, say `100000 * flint_test_multiplier()`? Well, in that case the test function as a whole would run slow due to net increase in the number of iterations. Please correct me if I misinterpreted your comment.

**Comment by wbhart** [comment]
Yes, that is what I meant. If this takes too long, you may have to break
the range up into a larger number of subranges instead. Currently you are
using subranges of length 1, but I think this makes it difficult, at least
when limit is not really small, to detect large variations reliably.

**Comment by wbhart** [comment]
What happens if you just increase the number of iterations by a factor of
10? How long does it take then? Does it finish in under 3s? If so, then
that is probably sufficient, rather than going to all the trouble to
implement larger subranges.

**Comment by apoorv-mishra** [comment]
> What happens if you just increase the number of iterations by a factor of
> 10? How long does it take then? Does it finish in under 3s?

It takes 3-4s, almost ~3s.

**Comment by fredrik-johansson** [comment]
3-4 seconds would be longer than most tests in the ulong_extras module. I would aim for a running time of say 0.1 seconds, and design it such that increasing flint_test_multiplier() increases the test strength further.

**Comment by wbhart** [comment]
Yeah, I forgot about that Fredrik. So, what you are advocating is a small
inner loop that can be made bigger with flint_test_multiplier(). Let's do
that then Apoorv.

**Comment by apoorv-mishra** [comment]
So, you want me to reduce `1000 * flint_test_multiplier()` to, say `10 * flint_test_multiplier()` and then, for individual testing purposes, we can make `flint_test_multiplier()` return larger. Am I correct?

**Comment by apoorv-mishra** [comment]
So, the whole purpose of `flint_test_multiplier()` is to make testing easy and flexible depending upon the individual's need. We capped the value at `10` for the main branch. We design test functions in such a way that the individual only needs to change this value according to his needs and consequently, all the test functions would work correctly(slowly though, if he/she increases the value). Is this the point you are making by suggesting to lower the inner loop bound?

Also, I guess then we would not need to change the subrange size of 1 for the first scenario. Right?

**Comment by wbhart** [comment]
Yes, I guess that is what we have to do.

**Comment by wbhart** [comment]
On 21 August 2017 at 19:18, Apoorv Mishra <notifications@github.com> wrote:

> So, the whole purpose of flint_test_multiplier() is to make testing easy
> and flexible depending upon the individual's need. We capped the value at
> 10 for the main branch. We design test functions in such a way that the
> individual only needs to change this value according to his needs and
> consequently, all the test functions would work correctly(slowly though, if
> he/she increases the value). Is this the point you are making by suggesting
> to lower the inner loop bound?
>

Correct.


> Also, I guess then we would not need to change the subrange size of 1 for
> the first scenario. Right?
>

No, I guess not.

**Comment by apoorv-mishra** [comment]
But setting inner loop bound to `1000 * flint_test_multiplier()` still takes around 1s. Would it be fine? Although, Fredrik pointed out that it should take around 0.1s.

**Comment by wbhart** [comment]
Do you mean 10*flint_test_mutiplier()? If so, then we really can't go any
lower. We'll have to come up with another way.

**Comment by wbhart** [comment]
Actually, we really can't go that low. If you have limit = 1000, you are going to need at least 10 hits for each of the subranges, which means you can't really go lower than 1000 * flint_test_multiplier().

I think the only way to make this work is to increase the size of the subranges.

Why don't you split the entire range [0, limit) into FLINT_MAX(10, limit/10) subranges of roughly equal size (you will have to adjust for the fact that they are not exactly the same size).

Another way that might be easier is to only test every 10th value for limit. That would cut the time by a factor of 10.

**Comment by apoorv-mishra** [comment]
Testing every 10th value of limit reduces time to around 0.8s. I'm not sure whether increasing the subrange size would improve the running time that much since we are calling `n_urandint()` `1000 * flint_test_multiplier()` times for each of the 1000 values of limit regardless of subrange size.

**Comment by wbhart** [comment]
How much time was it taking with every value of limit? Is the second test
taking all the time?

**Comment by wbhart** [comment]
The advantage with fewer subranges is you don't need the inner loop to be
as large since you can detect a broken random function much easier.

**Comment by apoorv-mishra** [comment]
> How much time was it taking with every value of limit?

It takes around 1s for every value of limit(1000 values in all for each type of test).

> Is the second test taking all the time?

No, I guess.

**Comment by wbhart** [comment]
Why does the time not go down by a factor of 10 when you only time every tenth one? Can you just give the times for the first test with the second one commented out?

**Comment by apoorv-mishra** [comment]
When I comment out the second test. I get following timings

`real	0m0.674s`
`user	0m0.588s`
`sys	0m0.064s`

**Comment by apoorv-mishra** [comment]
The above timing is when I consider every 10th limit value for the first test and second being commented out.

**Comment by wbhart** [comment]
And what are the timings with every value instead of every tenth value?

**Comment by apoorv-mishra** [comment]
Second case commented out and first case considering every value of limit(first five iterations) -

real	0m1.033s
user 0m0.940s
sys	0m0.072s

real	0m0.946s
user	0m0.860s
sys	0m0.064s

real	0m0.950s
user	0m0.868s
sys	0m0.064s

real	0m0.940s
user	0m0.840s
sys	0m0.084s

real	0m0.970s
user	0m0.900s
sys	0m0.056s

**Comment by wbhart** [comment]
I don't understand why it doesn't go down by a factor of 10. Can you post the test code to a gist with the second test commented out and only every tenth value.

**Comment by apoorv-mishra** [comment]
It doesn't matter whether I comment out the first or second case. The timings are same for both subcases-considering every tenth value or every value of limit

**Comment by apoorv-mishra** [comment]
Sure. https://gist.github.com/apoorv-mishra/59b426fa513c8ae41ce07f09f4003a9f

**Comment by wbhart** [comment]
One minor speedup would be to change this line:

int count[1000] = {0};

This has to set 1000 values to 0, no matter how large limit is. You could replace it with a loop that sets only the first limit values of count to 0, and have the definition of the count array earlier in the function.

But this doesn't explain the timing issue at all.

**Comment by apoorv-mishra** [comment]
I have replaced that line with `count = flint_calloc(limit, sizeof(int));`. You may check the gist.

**Comment by wbhart** [comment]
I see you are using calloc now. You could do a flint_malloc once outside the loop and just zero the relevant entries in a for loop at the start of each iteration. The flint_calloc function calls calloc, which is very expensive. So perhaps this is what is making it so slow.

Currently I'm a bit mystified about the timings.

**Comment by apoorv-mishra** [comment]
Here the timings for https://gist.github.com/apoorv-mishra/e0c2b19e6c9166917bd69f587b12dd37 -

real	0m1.137s
user	0m0.752s
sys	0m0.096s

real	0m0.675s
user	0m0.584s
sys	0m0.072s

real	0m0.692s
user	0m0.604s
sys	0m0.072s

real	0m0.650s
user	0m0.572s
sys	0m0.064s

It's without flint_calloc.

**Comment by wbhart** [comment]
That is bizarre. I can't explain it.

What is the time if both tests are commented out (but not the malloc and free)?

**Comment by apoorv-mishra** [comment]
When both tests are commented out -

real	0m0.955s
user	0m0.572s
sys	0m0.068s

real	0m0.593s
user	0m0.508s
sys	0m0.068s

real	0m0.616s
user	0m0.556s
sys	0m0.040s

Not a significant difference I guess.

**Comment by wbhart** [comment]
Are you timing the actual test, or make check?

To time the actual test, you need to export LD_LIBRARY_PATH=/path/to/flint and then run the file build/ulong_extras/test/t-urandom.c in the Flint source tree.

**Comment by apoorv-mishra** [comment]
I am timing make check.

**Comment by wbhart** [comment]
Yeah that's the problem. We need to look at the timings of the actual test itself.

**Comment by apoorv-mishra** [comment]
Yeah, apologies for that. I'll look for the actual timings.

**Comment by apoorv-mishra** [comment]
Timings together for both test scenarios, considering each value of limit -

real	0m0.866s
user	0m0.864s
sys	0m0.000s

Timings together for both test scenarios, considering every 10th value of limit for the first test scenario -

real	0m0.559s
user	0m0.556s
sys	0m0.000s

Timings together for both test scenarios, considering every 10th value of limit for both test scenarios -

real	0m0.135s
user	0m0.132s
sys	0m0.000s

**Comment by wbhart** [comment]
That looks better. I think we will go with every 10th value for both test scenarios. If you can commit the code, I will merge it, if you have dealt with all of the other points I mentioned previously.

**Comment by apoorv-mishra** [comment]
Sure, thanks for your participation and help.

**Comment by wbhart** [comment]
This looks good now. The only changes that need to be made that I can see are on lines 49 and 104, which are now longer than 80 characters. If you can insert a line break and some indenting after the || in each case, that would be appreciated. Then I will merge this.

**Comment by wbhart** [comment]
Thanks for this contribution!

**Pull request merged**
