### PR TITLE
parallel version of heap multiplication

### PR DESCRIPTION
**Pull request by tthsqe12**
This adds the function "mul_heap_threaded" which is a threaded version of "mul_johnson".

### CODE REVIEW

**Comment by wbhart** [comment]
This is great Daniel!

Can you do another fetch and rebase (on fmpz_mpoly). In this instance, you will have to do git push -f instead of git push when you push it out to your GitHub.

Once that is done, I will merge this.

**Comment by tthsqe12** [comment]
since I though this is a dangerous sequence of commands, I am going to run
them by you before I execute them

git checkout fmpz_mpoly
git fetch bill
git merge bill/fmpz_mpoly
git push -f

In my notes I never have a push when I am on the fmpz_mpoly branch.

assuming that the above works, I would then do

git checkout parallel
git rebase fmpz_mpoly
and then what? git push -f ?


What I did to make the PR was the usual:
gitcheckout -b parallel_mul_heap
make change
commit
git fetch bill
git rebase bill/fmpz_mpoly
git push origin parallel_mul_heap
make PR

Is there a reason this didn't work in this case?

**Comment by wbhart** [comment]
This looks right. Of course you want to checkout parallel_mul_heap in the second lot of commands not parallel. But otherwise it's ok. Yes, you finish it off with git push -f.

The commands you used before were fine, I just updated the branch in the mean time.

**Comment by tthsqe12** [comment]
So I'm getting a "Automatic merge failed; fix conflicts and then commit the
result." in fmpz.h. I'm going to edit the file and make sure it matches
your fmpz_mpoly branch. It looks like then I have to do a "git add fmpz.h"
and then a "commit -m "blah"" and then finally a "push -f".

**Comment by tthsqe12** [comment]
This doesn't work either. The "git push -f" is now failing. I will just
wait until tomorrow and check with you that I am not hosing the repo.

**Comment by wbhart** [comment]
I think you have to do git rebase continue or something like that. But we'll look tomorrow. It's just the standard rebase conflict procedure. Nothing to worry about. It will apply each of your patches in turn over my version of the repository, and you have to resolve each conflict in turn (there may be more than one). Probably you made changes to fmpz.h which you don't want to lose, so you probably shouldn't just make it the same as my version.

You can do git rebase abort if you want to go back to how it was before the rebase, and try again.

**Pull request merged**
