### PR TITLE
start fmpq_mpoly

### PR DESCRIPTION
**Pull request by tthsqe12**
fmpq_div and fmpq_divrem_ideal are still missing.

### CODE REVIEW

**Comment by wbhart** [comment]
Great. I'll take a look and merge it if it looks ok.

**Comment by wbhart** [comment]
One thing I can see already is a lot of functions are ending up combined in the same file. For example the degree function and possibly some of the geobucket functions.

The rule in Flint is that every function should be in a separate file (test functions can however be combined if it isn't practical to test them individually). The exception to this is for helper functions that are only used by a function in that file (and aren't intended to be user facing).

**Comment by wbhart** [comment]
The following is still in set_term:

/*printf("doesnt exist\n");*/

**Comment by wbhart** [comment]
A very minor thing:

I happened to notice that the copyright notice in pow_fmpz, set_str_pretty and quasidiv_heap all have 2017 instead of 2018. Is that intentional?

**Comment by wbhart** [comment]
Otherwise, I see no problems to merge this.

How confident are you that the geobuckets code is correct? Is it really exercised heavily? I didn't spot test code for it. That's ok if it is not practical to test. But are there likely to be corner cases missed if we do this?

**Comment by tthsqe12** [comment]
Alright, I will fix these things asap. The geobucket code is tested in parsing. Parsing a printed polynomial should yield the original polynomial.

**Comment by wbhart** [comment]
Thanks. By the way, I'm really impressed with the sheer quantity of code here. And it's not just that. This is high quality code. I can't see any other issues, and will merge this into fmpz_mpoly when you've done with the changes I mentioned.

**Comment by tthsqe12** [comment]
This last commit should be the last commit.

**Pull request merged**
