### PR TITLE
use blas for nmod_mat_mul

### PR DESCRIPTION
**Pull request by tthsqe12**
This is still a work in progress, and I am just looking for comments/suggestions at this point.

### CODE REVIEW

**Comment by thofma** [comment]
Do you have some timings?

**Comment by fredrik-johansson** [comment]
Things I'm sure you've thought about already:

* Handle larger moduli using two or three dgemms
* Use sgemm for smaller moduli
* Use BLAS for the addmul variants too
* Do Strassen directly on top of BLAS (the additions are surprisingly costly)
* Use BLAS-friendly moduli in fmpz_mat_mul_multi_mod with HAVE_BLAS
* Do fmpz_mat_mul_multi_mod directly on top of double matrices to avoid converting twice
* Do something better for rectangular matrices (also in the non-BLAS code)

**Comment by tthsqe12** [comment]
Ok. I don't feel comfortable adding so many if have_blas everywhere while the pr is unresolved.
@thofma a 2048x2048 by 2048x2048 multiplication takes 80ms with 30 of those milliseconds spend converting the inputs and output, so about half of the time is spend converting. Of course the default c flags -O2 -funroll-loops are not helping with the conversion.

**Comment by tthsqe12** [comment]
@fredrik-johansson could you explain how you would do all nmod_mat_mul with at most three dgemms?
In the worst case k = 2^31-1 and N=mod.n = 2^64-1, my crt math gives roughly 156/12=13 dgemms.
For k = 2^12 and N = 2^64-1 the formula is
`log(floor(2*sqrt(2^53/k)))/log(k*Floor(N/2)^2)` = 6.418 = 7 dgemms

**Comment by fredrik-johansson** [comment]
Yes, I was off by a factor two (unless there's a trick here that neither of us sees 🙂).

**Comment by tthsqe12** [comment]
timings. About half of the time is spend doing the slow O(n^2) conversion and the other half is blas doing its O(n^3) operations.
```
nxn time nxn matrix product

 modulus |   1024    |    2048   |   4096      |
         | old   new |  old  new |   old   new |
bits 8:  | 138    18 |  957   82 |  6718   514 |
bits 12: | 138    17 |  974   82 |  7012   515 |
bits 16: | 246    17 | 1729   84 | 12189   516 |
bits 20: | 245    17 | 1729   81 | 12265   518 |
bits 24: | 246    73 | 1724  335 | 12276  1898 |
bits 28: | 244    72 | 1727  440 | 12241  2497 |
bits 32: | 352    92 | 2453  442 | 17475  2557 |
bits 36: | 412    93 | 2891  445 | 20446  2548 |
bits 40: | 414   124 | 2888  594 | 20389  3351 |
bits 44: | 414   131 | 2888  610 | 20383  3405 |
bits 48: | 413   131 | 2895  610 | 20348  4124 |
bits 52: | 413   160 | 2881  739 | 20430  4242 |
bits 56: | 412   160 | 2892  740 | 20375  4242 |
bits 60: | 413   161 | 2892  740 | 20373  4998 |
bits 64: | 471   188 | 3303  868 | 23250  4981 |

**Comment by tthsqe12** [comment]
@wbhart I am happy with this.

**Comment by fredrik-johansson** [comment]
Because of slow conversions?

Anyhow, well done!

**Comment by tthsqe12** [comment]
The main problem is moduli with more than 20 bits. Calling dgemm 7 times and then crt'ing the answers takes time. It still beats the old threaded code though.
```
old8: old flint with num_thread = 8, which uses mul_classical_threaded
new8: new with num_threads = 8

        | 1024     |    2048   |   4096    |
modulus  old8 new8 | old8 new8 | old8 new8 |
bits 8:    39    9 |  193   60 | 2357  521 |
bits 12:   42   15 |  392   61 | 4675  518 |
bits 16:   42   15 |  395   61 | 4670  521 |
bits 20:   42   17 |  392   61 | 4744  522 |
bits 24:   41   81 |  394  198 | 4800 1688 |
bits 28:   62   40 |  527  253 | 5318 2168 |
bits 32:   62   59 |  527  255 | 5319 2214 |
bits 36:   71   54 |  593  258 | 5840 2208 |
bits 40:   71   71 |  616  335 | 5836 2807 |
bits 44:   70   74 |  598  337 | 5844 2824 |
bits 48:   70   80 |  598  363 | 5844 3497 |
bits 52:   71   90 |  598  419 | 5853 3532 |
bits 56:   70   89 |  600  413 | 5854 3519 |
bits 60:   79   89 |  690  438 | 6533 4088 |
bits 64:   79  102 |  690  490 | 6540 4090 |

**Comment by wbhart** [comment]
Well, dimension 1024 is pretty huge, and it looks to me like the old code was winning for smaller dimensions. Do we have a heuristic for making sure we are not just slowing things down? The common case is small dimension with large moduli.

**Comment by tthsqe12** [comment]
So, I will try to tune this. It is just a five dimensional space:
-flint num threads
-blas num threads,
-n
-m
-k
-bits(mod.n)

**Comment by wbhart** [comment]
Sounds like you'll be done in time for lunch!

**Comment by tthsqe12** [comment]
One of the things that makes the classical_threaded faster is the cache blocking. Could you make sure this is well-tuned first?

**Comment by wbhart** [comment]
Did I even implement cache blocking?

**Comment by wbhart** [comment]
If I did, it's tuned for my machine.

**Comment by tthsqe12** [comment]
@wbhart I am satisfied with this. The only possible issue is that I am calling
openblas_get_num_threads
cblas_sgemm
cblas_dgemm
and these might not be the names of the correct functions on your particular installation.

**Comment by wbhart** [comment]
The one that concerns me is openblas_get_num_threads. This seems to restrict us to using OpenBLAS, which I don't think should be the intention. Is there a way to call something more general? Or can we detect whether it is OpenBLAS at compile time using some flag they define and then only call this function in that case?

**Comment by wbhart** [comment]
Flint doesn't define FLINT_USES_BLAS. There is HAVE_BLAS (which is probably nowadays FLINT_HAVE_BLAS; I haven't updated my flint-config.h in a while). Is there any reason to use FLINT_USES_BLAS instead?

**Comment by tthsqe12** [comment]
I think the 3rd testing machine got struck by lightning. Most of the HAVE_x's got renamed to FLINT_USES_x, or at least this the way my configure works. I have decided never to call blas_set_num_threads, and the only reason to call blas_get_num_threads is because flint is usually the way to go if the flint threads out number the blas threads. It could be removed, but 1 blas thread in mul_blas will usually be slower than, say, 8 flint threads doing classical.

**Comment by wbhart** [comment]
There's still failures on the third test machine.

**Comment by tthsqe12** [comment]
@wbhart would you like me to add a dummy commit here so we can see it green?

**Comment by wbhart** [comment]
I restarted the build and it still fails. I don't think a dummy commit will change anything. You can also close and reopen the PR if you want to trigger a rebuild, but I think the result will be the same.

**Pull request merged**
