### PR TITLE
implement Hermite polynomials He_n(x)

### PR DESCRIPTION
**Pull request by rwst**

### CODE REVIEW

**Comment by rwst** [comment]
```
Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/main/t/texinfo/texinfo_4.13a.dfsg.1-8ubuntu2_amd64.deb  Unable to connect to us.archive.ubuntu.com:http: [IP: 91.189.91.14 80]
```
My pings get through, however. Restart?

**Comment by wbhart** [comment]
Again fmpz_divexact_si by -2 can be replaced by a neg and a div_2exp.

Also the underscore function should be documented. This is also the case for the first Hermite function as well, actually. I realise it will say almost the same thing except for the interface. But it is important that the user can look up what n are supported for example.

**Comment by fredrik-johansson** [comment]
In both Hermite variants, I think you could combine the two muls and divs for each coefficient by using fmpz_mul2_uiui and fmpz_divexact2_uiui (see _fmpz_poly_chebyshev_t for example).

**Comment by rwst** [comment]
There are only rounding div_2exp and from them I get funny results, so what exactly do you recommend to divexact a fmpz by 2exp?

**Comment by fredrik-johansson** [comment]
Something must be wrong with your code. All division functions are equivalent for doing exact divisions.

**Comment by fredrik-johansson** [comment]
LGTM.

**Pull request merged**
