### PR TITLE
Change abort() to flint_abort()

### PR DESCRIPTION
**Pull request by albinahlback**

### CODE REVIEW

**Comment by wbhart** [comment]
Thank you very much for this! I'll take a quick look through before merging just to make sure no rare species have been endangered.

**Comment by albinahlback** [comment]
Yes, I'll try to do the rest right now.

**Comment by albinahlback** [comment]
Done.

**Comment by albinahlback** [comment]
First I simply did something along the lines with `find . -type f -name "*.c" -o -name "*.h" | xargs sed -E -i "s/ abort\(\)/flint_abort\(\)/g"`. This has not affected `exceptions.c` at least.

Then I did something like `sed -E -i "s/(\s*)flint_abort\(\);/\1fflush\(stdout\);\n\1flint_abort\(\);/g" */test/*` to only change the test files, since we do not want to bloat the actual methods. I believe flushing was never made before, and thus no duplication should have been made.

**Pull request merged**
