### PR TITLE
julia wrapper for nmod_poly & doc bugfix

### PR DESCRIPTION
**Pull request by thofma**

### CODE REVIEW

**Comment by wbhart** [comment]
Thanks Tommy.

The inlines shouldn't have names beginning with an underscore.

Also these three should be in nmod_poly.h, not inlines.c

slong nmod_poly_length(const nmod_poly_t poly)

slong nmod_poly_degree(const nmod_poly_t poly)

ulong nmod_poly_get_coeff_ui(const nmod_poly_t poly, slong j)

If there are already macros with these names, you can turn them into inline functions.

**Comment by wbhart** [comment]
Also, for better or for worse, we tend to rely pretty heavily on the internals of our data types in flint. So we'd typically modify the relevant coefficients directly in nmod_poly_add/sub_ui (at least after we've copied the polynomial anyway).

No need to change this as you are using the inline functions to do the modifications, which is probably what we should be doing everywhere (with gcc that's as fast as using macros). But I thought I'd mention this in case you have more sophisticated changes in future and you need to work more directly with the representation.

**Comment by thofma** [comment]
Regarding the inlines. I didn't notice you added them. I wrote the wrapper before your changes. I have changed it now.

**Comment by wbhart** [comment]
You still have an underscore on _nmod_poly_factor_get_nmod_poly which isn't needed.

**Comment by thofma** [comment]
Sorry, my mistake. Removed it.

**Comment by wbhart** [comment]
Thanks. I've merged this.

**Pull request merged**
