### PR TITLE
Second zassenhaus

### PR DESCRIPTION
**Pull request by tthsqe12**
I don't know if Fredrick would like to try this out to tune some more values.
It seems that the old fmpz_poly_factor_zassenhaus_recombination was unfortunately part of the official interface, so I had to make a new fmpz_poly_factor_zassenhaus_recombination_with_prune that is intended to never be part of any official interface.
Also, the subset enumerator is readable now and has test code!

### CODE REVIEW

**Comment by fredrik-johansson** [comment]
Did you mean to keep calling Zassenhaus with ..., 8, 1); in fmpz_poly_factor() while fmpz_poly_factor_zassenhaus() uses ..., WORD_MAX, 0); ?

**Comment by tthsqe12** [comment]
I think the function currently called _fzmpz_poly_factor_zassenhaus is misnamed, since it does both methods

**Comment by wbhart** [comment]
@fredrik-johansson 
@tthsqe12 
Let me know when this is ready to go.

I personally don't see any problem with changing the interface for fmpz_poly_factor_zassenhaus. It is almost certainly not being used directly by anyone (with the possible exception of Fredrik). Sure we'd have to announce it and change the soname of the library, but this is not a huge big deal. So long as the main function for factorisation doesn't change, everything is cool as far as I am concerned.

Let me know if you want to change the interface and I can announce it on the list (or so long as we are all happy with proposed changes, you can announce it yourself).

**Comment by fredrik-johansson** [comment]
No, there's no reason for fmpz_poly_factor_zassenhaus to work the old way anymore.

I don't plan to do any in-depth profiling presently. On one qqbar benchmark I was running recently, the time drops from 29 to 26 seconds with this patch. Elsewhere I'm not seeing any difference. So it's probably fine to merge.

**Comment by tthsqe12** [comment]
@wbhart are you saying that fmpz_poly_factor_zassenhaus_recombination can go in the dust bin? If so, that is cool. If not, I could a reduce code by having it make a full phoney pruner and just call the recobination with pruning.
@fredrik I did not expect huge gains here. However, in combination with a few more soon-to-be-added hacks, there can be huge gains on certain inputs where these hacks apply.

**Comment by tthsqe12** [comment]
Let us not include this tricky code in the upcoming bug fix release. The previous zassenhaus seems to work correctly, and I would hate to bugger up another release (on the final commit!)

**Comment by tthsqe12** [comment]
I guess since this has nothing to do with any release, my worries were imaginary, and this is fine for merge.
(I have thoroughly testing it also)

**Pull request merged**
