### PR TITLE
Thread limit cleanup

### PR DESCRIPTION
**Pull request by tthsqe12**

### CODE REVIEW

**Comment by wbhart** [comment]
We seem to have lost travis and appveyor.

**Comment by wbhart** [comment]
Apparently I should have waited to merge this:

```
LINK: command "C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\link.exe /nologo CMakeFiles\fmpz_mpoly-test-t-mpolyuu_divides_threaded.dir\fmpz_mpoly\test\t-mpolyuu_divides_threaded.c.obj /out:bin\fmpz_mpoly-test-t-mpolyuu_divides_threaded.exe /implib:lib\fmpz_mpoly-test-t-mpolyuu_divides_threaded.lib /pdb:bin\fmpz_mpoly-test-t-mpolyuu_divides_threaded.pdb /version:0.0 /machine:x64 /INCREMENTAL:NO /subsystem:console test_helpers.lib lib\flint.lib C:\Miniconda36-x64\Library\lib\mpfr.lib C:\Miniconda36-x64\Library\lib\gmp.lib C:\Miniconda36-x64\Library\lib\pthreads.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:bin\fmpz_mpoly-test-t-mpolyuu_divides_threaded.exe.manifest" failed (exit code 1120) with the following output:
t-mpolyuu_divides_threaded.c.obj : error LNK2019: unresolved external symbol __imp_flint_request_threads referenced in function bivar_divides_check
t-mpolyuu_divides_threaded.c.obj : error LNK2019: unresolved external symbol __imp_flint_give_back_threads referenced in function bivar_divides_check
bin\fmpz_mpoly-test-t-mpolyuu_divides_threaded.exe : fatal error LNK1120: 2 unresolved externals
[5231/7140] Linking C executable bin\fmpq_poly-test-t-get_set_coeff_mpz.exe
ninja: build stopped: subcommand failed.
Command exited with code 1
```

**Comment by wbhart** [comment]
I've reverted it for now.

**Comment by tthsqe12** [comment]
I was wondering what happened to the checks.

**Comment by wbhart** [comment]
I think GitHub has had some issues and so they didn't show up, much less run, for many hours after the PR was made. They did eventually run though, which is why I removed the PR. Could you open it again and we can look at the CMake output and figure out what is missing.

**Comment by tthsqe12** [comment]
@wbhart  Do you have any idea why it can't find those imports? There are FLINT_DLL's in thread_support.h

**Comment by wbhart** [comment]
Nope. Is there an extern C missing?

**Comment by wbhart** [comment]
It did pass on Travis, which makes it more weird.

**Comment by wbhart** [comment]
If you want, I think you can uncomment the last lines of the appveyor file and log in using a remote desktop connection. But you might have to enable appveyor for your GitHub for that. You can try logging in with the info that gets displayed at the end of the build on the PR. Maybe it will work.

**Comment by tthsqe12** [comment]
I don't know what is going on.
I accidentally pushed some bad changes to tthsqe12:thread_limit_cleanup.
The branch tthsqe12:thread_limit_cleanup_try_2 has just the stuff that I think should work.

**Comment by wbhart** [comment]
Can you make a PR based on it.

**Comment by wbhart** [comment]
Probably you merged from me, which would have reverted all your changes. Just take a look in your git log at how many commits you need to go back, then do:

git reset --hard HEAD~n

where n is the number of commits you want to remove. That should take you back to where you were. Unfortunately GitHub doesn't allow you to remove commits. You have to revert them, which just applies reverse commits in addition to the original ones.

**Comment by wbhart** [comment]
Alternatively, fetch from me. Update your trunk branch. Open a new branch. Then cherry-pick the three commits that you made above (looking at the GitHub PR page).

**Pull request merged**
