### PR TITLE
Windows fixes

### PR DESCRIPTION
**Pull request by isuruf**
I've also skipped the tests mentioned in https://github.com/wbhart/flint2/issues/517#issuecomment-465005690

### CODE REVIEW

**Comment by isuruf** [comment]
Here's an appveyor build, https://ci.appveyor.com/project/isuruf/flint2

**Comment by isuruf** [comment]
This PR also adds support for MPIR 3.0.0 on windows.

**Comment by tthsqe12** [comment]
Why is fmpz_mpoly_divides_array a known failure?

**Comment by isuruf** [comment]
I don't know why that test fails. I've reported the failures at https://github.com/wbhart/flint2/issues/517#issuecomment-465005690. It's better to have CI working somehow instead of nothing at all.

**Pull request merged**
