### PR TITLE
Added code for perfect power testing in fmpz_factor.

### PR DESCRIPTION
**Pull request by kush789**
Hi,
I have added the code for perfect power testing, as mentioned in the todo.txt under fmpz_factor. This function tests whether an integer can be represented in form of a^b. I've updated the documentation accordingly too.

There wasn't a lot mentioned in the todo regarding this function. Please do let me know what all has to be changed and added.
Thanks,
Kushagra

### CODE REVIEW

**Comment by wbhart** [comment]
Hi Kushagra,

I see you've implemented a binary search algorithm, which given a base b
looks for an exponent n such that the input d is b^n.

This is probably not what we mean by a perfect power test. Basically what
we need is a function which tries to find if d is b^n for *any* base b,
i.e.the user will not specify a base.

This might sound like it would take forever, since the base could be
anything. But actually, it can be done efficiently if you have an efficient
n-th root function (GMP has one, called mpz_rootrem).

Basically, you take your input d and you try taking the n-th root for
various _prime_ values of n (you can special case n = 2). If the remainder
is zero, then it must be a perfect n-th power, which gives you some
information.

Of course such a function will always try to find the largest exponent
possible. So if something is a 6th power, it will not return exponent 2 or
3, but 6.

It would be useful for such a function to return the base too, not just the
exponent that it found.

I think there are even better algorithms. I seem to remember a paper
somewhere on detecting perfect powers in essentially linear time. Oh yes,
here it is:

http://cr.yp.to/papers/powers-ams.pdf

This is probably more work to implement, so the strategy I suggest above is
probably best to start with, and if you are feeling motivated, you could
look at the algorithm in that paper.

The first step either way is to implement an fmpz_rootrem function. This
will require implementing n_rootrem for a single word, which is already
quite tricky. Taking roots efficiently is quite a bit of work. Probably the
best way is using newton iteration of the polynomial x^n - d:

http://en.wikipedia.org/wiki/Nth_root_algorithm

though I could imagine Fredrik chiming in with some better ideas on this
than me.

Bill.

**Comment by kush789** [comment]
Hey,

As of now the code checks whether n can be expressed as a^b for all possible bases, not just a given base. The base parameter passed is set to the value of the base, if found while checking. Otherwise it is set as -1. The function is not asking for any base from the user. Similarly with the passed argument "exponent". But yes, what you are suggesting is much more efficient. I'll try implementing that and get back to you.

Thanks,
Kushagra

**Comment by wbhart** [comment]
Oh, I missed where you set an upper limit on b and then loop over possible
values of b.

But I don't understand this limit. Couldn't b be as large as sqrt(n), e.g.
if n = b^2?

I don't understand why you use log(n). I'm probably still misunderstanding
something.

Bill.

**Comment by kush789** [comment]
Hey,

I guess my choice of variable name gave the intuition that b is the base. The function checks whether n can be expressed as a^b. "b" is the exponent not the base. "a" is the base.

Since "a" has to be greater than or equal to 2, the max value of "b" can be log2(n). Hence the upper bound of log2(n) + 1.

Kushagra

**Comment by wbhart** [comment]
Oooh, yes, that had me confused. Now I see. You do in fact loop over all
possible powers, checking to see if n is a b-th power. That check is made
by a binary search. I hope I understand it now.

One thing that is contributing to the confusion a little is just how far to
the right the comments are. Most of them are off the right side of my
editor. Perhaps you could bring them further in. We try to keep all lines
of length at most 80 characters in flint, so they can be easily viewed in a
terminal (and on github).

It'll be interesting to compare and see how much faster some of these other
methods are.

**Comment by kush789** [comment]
Yep, its looping over all possible bases for a given b, and sets the *exponent* parameter as the maximum power if multiple ways to express n are there.

I also read somewhere that the process can be faster if we check only for prime bases, but the function call is_prime() when used is making it slower. It enhances performance only if we have a precomputed list of primes. 

Also I agree with you that a function like mpz_rootrem might be more efficient than this. I am onto that presently. 

Kushagra

**Comment by kush789** [comment]
I'm sorry, it should be, "It's looping over all possible exponents, and for each exponent, there is a binary search for the base"

Kushagra

**Comment by wbhart** [comment]
You probably want to use the prime iterator, not is_prime. The former will
be much more efficient, especially for small exponents.

**Comment by kush789** [comment]
Hey,

I have added two root_rem functions.

- fmpz_rootrem_newton_iteration : this uses the newton iteration method which you suggested over here, http://en.wikipedia.org/wiki/Nth_root_algorithm

- fmpz_rootrem_bsearch : this uses a binary search method to find the remainder. I found this method over here. http://en.wikipedia.org/wiki/Talk:Nth_root_algorithm

- In both cases, four parameters are passed, remainder, base, the number and the root. Base gets set to a value such that base^root <= n and the remainder is set as n - base^root.

- On comparing the two, the fmpz_rootrem_bsearch seems to be much faster, almost three to four times. And as of now, the constraints on n and root are such that both have to be >= 2.


Please have a look and let me know what all to change. If it seems right, I'll proceed with the perfect power check function.

Kushagra

**Comment by kush789** [comment]
Hello sir,

- I added the perfect power testing code in the fmpz_factor module. As of now there are two functions, fmpz_is_perfect_power and n_is_perfect_power. The latter one uses the fmpz_rootrem_bsearch function, which was turning out to be faster than the newton iteration method to calculate remainders. The present implementation of the perfect power is much faster than the initial one I had implemented, almost two times quicker on an aggregate.

- Can you please have a look so that I can remove the fmpz_is_perfect_power which I had coded initially, as it is redundant now ( n_is_perfect_power is faster). Also, should I remove fmpz_rootrem_newton_iteration, since fmpz_rootrem_bsearch is giving faster results?

Thanks
Kushagra Singh

**Comment by wbhart** [comment]
Hi Kushagra,

sorry I didn't get to look at this thoroughly yet. Working on too many
things. I hope my comments below are correct. I didn't look as closely as I
should.

The newton iteration looks odd to me. The fmpz_t type takes a big integer,
which could be any size. But you seem to be using doubles to perform the
newton iteration. But a double can only hold 53 bits. It looks to me like
this implementation will only work for very small fmpz_t's.

Besides that, there is no need to implement a bignum rootrem because you
can use the mpz_rootrem function from GMP.

If you look at some of our other fmpz functions in flint you will find some
examples where we do something for small values using ulongs and then for
large values we just call the mpz function from GMP.

Basically our fmpz_t type is a pointer to either a signed long (what we
call an slong in flint for portability reasons, or an fmpz actually) or a
(in our case, mangled) pointer to an mpz_struct (which is basically what an
mpz_t is). We have macros for determining which case you are in.

So what I recommend is first implementing an n_rootrem function in the
ulong_extras module (that's the module which just works with machine words,
i.e. what we call ulong -- essentially an unsigned long on most machines,
though not all), and calling it if the input to the fmpz_rootrem function
is small. Otherwise, call the GMP mpz_rootrem function.

The n_rootrem function can use newton iteration. The fun part is working
out the most efficient way of bootstrapping the newton iteration. You could
use lookup tables for small exponents, for example. Just an n_rootrem
function would already be a very useful contribution to flint! It's not
trivial at all!

You also need some test functions. They should randomly generate perfect
powers and non-perfect powers of various sizes and check that the function
returns the right results in each case.

If you take a look at some of our other fmpz test functions in fmpz/test
you will see what we usually do. Most of the test functions have a similar
format. Similarly for the ulong_extras module.

Also, try to keep the prototype for the fmpz_rootrem function as similar to
the GMP prototype for mpz_rootrem, except for the use of fmpz_t's instead
of mpz_t's of course.

**Comment by kush789** [comment]
Hello sir, 

I removed the cbrt function in pocklington as you mentioned. I've also removed the root_rem and perfect power files I had added earlier to my fork. They are no longer there in this pull request.

I realize this thread has become quite messy, I apologize for that.
Kushagra

**Comment by wbhart** [comment]
I think I am the one who has posted in the wrong thread. Sorry about that.

I'll merge the changes you made to the is_prime_pocklington. Thanks.

**Pull request merged**
