### PR TITLE
start mpoly factor

### PR DESCRIPTION
**Pull request by tthsqe12**

### CODE REVIEW

**Comment by tthsqe12** [comment]
I should be satisfied with this for the time being.

**Comment by fredrik-johansson** [comment]
🥳

**Comment by wbhart** [comment]
I can merge it if you want. Just let me know.

**Comment by tthsqe12** [comment]
Yes. I can't maintain it separately anymore.

**Comment by wbhart** [comment]
One thing, could you go through all the files and change http to https in the URL in the license header of each file. This has been done elsewhere in Flint, but probably not in your new files.

**Comment by tthsqe12** [comment]
If you looked at any of the headers, you would see that I already did that.

**Comment by wbhart** [comment]
Great!

**Pull request merged**
