### PR TITLE
fix remaining leaks in test code

### PR DESCRIPTION
**Pull request by tthsqe12**
It all good now!

### CODE REVIEW

**Comment by wbhart** [comment]
Didn't you mention something about fmpq_mat?

**Comment by tthsqe12** [comment]
fmpz_mat/t-scalar_smod had an invalid read on a empty matrix, but it doesn't any more.
The following three makefile configurations all pass testing against gmp62 on my linux box. Will try windows+gmp62 later
```
LDFLAGS=-fsanitize=address
CFLAGS=-pedantic -Wall -fsanitize=address -fno-omit-frame-pointer -g -mpopcnt 
========================================================
CFLAGS=-ansi -pedantic -Wall -O2 -funroll-loops -g -mpopcnt 
========================================================
CFLAGS=-ansi -pedantic -Wall -O3 -march=native
```

**Comment by wbhart** [comment]
I meant in the meeting today. I thought you said fmpq_mat. I can see it was that because I can see I typed that into my console to check that I hadn't missed something there.

**Comment by wbhart** [comment]
Maybe I misheard and you said fq_mat?

**Comment by tthsqe12** [comment]
Oh, at that point in time the sanitized test run was on fmpq_mat. The were several problems after that, so I had to start the test run over.

**Comment by wbhart** [comment]
Oh ok. Then we are all good. I will merge this when green and I think I'll issue alpha2. I had been thinking of a beta, but probably better we get the docs and everything else that needs to be in the repo finished before that.

**Pull request merged**
