### PR TITLE
Newton series

### PR DESCRIPTION
**Pull request by videlec**
Two implementations of Newton series for monic integer polynomials.

### CODE REVIEW

**Comment by videlec** [comment]
Right now, newton_series only calls the naive method... I am not sure how to make a wise choice.

**Comment by videlec** [comment]
I think there is a problem with `fmpz_poly_div_series`. The timing I got are more than unexpected

    degree=30      28       29       30       31       32       58       59       60       61       62       90       120       150       
    naive    :  0.01431  0.01447  0.01559  0.01675  0.01803  0.05890  0.06080  0.06283  0.06507  0.06740  0.13577  0.22855  0.33902  
    schoenage  :  0.01380  0.01436  0.01539  0.01652  0.08762  0.38114  0.39339  0.40319  0.41566  0.42356  0.98787  1.86583  2.98919

**Comment by videlec** [comment]
I did a bit more of investigation. 

1. The naive algorithm is doing O(n d) addition/multiplication. While, according to Bostan-Flajolet-Salvy-Schost the complexity for Schönage is O(n/d M(d)) where M(d) stands for the complexity of multiplication of polynomial of degree(d). It is not clear to me why Schönage would be theoretically better.

2. On the graphics deg 5 and deg 20 one can see that there is something weird with large degree.

**Comment by wbhart** [comment]
Nice work. There's still a couple of cases in the documentation and newton_series.c where some tabs have gotten through instead of 4 spaces.

**Comment by wbhart** [comment]
You have spelled schoenhage as schoenage. Unless it's not the same guy, some documentation and function names need changing.

**Comment by wbhart** [comment]
If the slowdown is due to div_series, there must be a problem in inv_series_newton or mullow. The former was rewritten by Fredrik a while back and the latter by Sebastian a long time ago. It's hard to imagine why either should be really slow, but my guess would be coefficient explosion.

The complexity you cite gives the complexity in terms of the length only, but not the size of the coefficients. When this happens, usually the best solution is to use some kind of multimodular approach, since presumably you know how big the final result is and you then don't care about intermediate coefficient swell.

Either that or there really is a bug. I can only recommend putting some traces in somewhere in the div_series algorithm at various points to see whether the coefficients are growing very large somewhere.

**Comment by fredrik-johansson** [comment]
fmpz_poly_div_series uses a basecase recurrence for n < 32 and inverse + multiplication for larger n. What you're seeing might be caused by coefficient blowup in the inverse. That's just a guess.

**Comment by videlec** [comment]
I also need to go from the Newton series to the initial polynomial. Is the name "reverse_newton_series" fine? The corresponding commit is  7c86807.

**Comment by videlec** [comment]
@wbhart you were right. In the benchmark I had to set the argument "bits" of "fmpz_poly_randtest". And I arbitrarily set it to 40. Now that it is down to 10, things are very much different (even though the naive method remains very competitive for degrees < 50). What I still don't understand is that the same blowup should be there for the naive method (triangular system of Newton identities)...

**Comment by wbhart** [comment]
The name reverse_newton_series sounds like it gives you the Newton series
in reverse. Would newton_series_to_poly be better?

As for coefficient blowup, unless the naive algorithm does an inverse
series operation I wouldn't expect it to behave the same way. I assume it
doesn't do a series division anywhere?

The problem is likely an exponential blowup of coefficient sizes
internally. This is common for algorithms over Z and the only way around it
is to modify the algorithm, often by using a multimodular or p-adic method
say.

Bill.

**Comment by videlec** [comment]
In order to implement the "fmpz_poly_newton_series_to_poly_pan_schoenhage" I need to integrate a polynomial with integer coefficients. I just remarked that there is a global denominator for fmpq_poly... which means that the integral of "1 + x + x^2 + ... + x^d" would actually store "factorial(d)" as denominator with coefficients almost as big. In other words, this is not usable for my purpose. This is clearly documented. Is there a plan to make an alternative data structure available for polynomials over the rationals (i.e. array of rationals)?

Actually what I need to do is exp(integral(1/x (poly - constant_coeff(poly)))) whose result is a polynomial with integral coefficient. There might be a shortcut in this situation but that would be a lot of work for a very specific algorithm.

For the time being I propose to make a branch only with the direct implementations only. I will see later on for implementing the Schoenhage and Pan-Schoenhage efficiently. What do you think?

**Comment by fredrik-johansson** [comment]
Such a data structure is not necessarily going to be faster, because you still have to blow the coefficients up by a factor d! when computing exp(). It sounds rather likely that a multimodular algorithm is the way to go here.

**Comment by fredrik-johansson** [comment]
Incidentally, I just sped up nmod_poly_exp_series.

**Comment by wbhart** [comment]
I'd be happy with a naive implementation for now. Probably the Schoenhage algorithm can be made faster with more work. But having something that works reasonably well is certainly better than nothing at all.

**Comment by videlec** [comment]
@wbhart with the last two commits, my branch is ready. If you prefer, I can fold all the commits into one.

@fredrik-johansson any pointers for multimodular implementation would be welcome. What it a good example to follow in flint library?

**Comment by wbhart** [comment]
On 2 February 2016 at 13:08, videlec <notifications@github.com> wrote:

> @wbhart <https://github.com/wbhart> with the last two commits, my branch
> is ready. If you prefer, I can fold all the commits into one.
>

It's not necessary to have one commit, but it is always worthwhile
squashing any commits that aren't relevant to the final PR, e.g. deleting
files or code that shouldn't have been there in the first place, reverts
and so on.

> @fredrik-johansson <https://github.com/fredrik-johansson> any pointers
> for multimodular implementation would be welcome. What it a good example to
> follow in flint library?
>

The routines that use a multimodular implementation should all have
_modular at the end of their names. There's a few there to have a look at,
but nothing pops into my head as a particularly good polynomial example.
Perhaps Fredrik has a good example that he can think of.

**Comment by videlec** [comment]
I rebased my commits. Tell me if I missed anything

**Comment by fredrik-johansson** [comment]
I think taylor_shift_multi_mod is a good reference. Note that there's a lot of code because it supports multithreading, which is probably overkill here (I wonder if we could abstract out that code and use it elsewhere?).

The basic steps are:

* Determine a bound for the output coefficients.

* Generate a list of primes with n_nextprime.

* For each prime p, allocate an array of mp_limb_t coefficients to hold the polynomial mod p.

* Create an fmpz_comb_t and fmpz_comb_t for the list of primes, and do the modular reductions with fmpz_multi_mod_ui.

* Compute the result mod each prime p.

* Reconstruct each coefficient in the output with fmpz_multi_CRT_ui.

* Clean up.

Another good example is arith/euler_number_vec.c. There is a small complication in this code: it optimises the CRT lifting for the triangular shape of the output, using only a subset of primes where the output is small. This is probably not important here.

**Comment by wbhart** [comment]
Is it worth including the schoenhage implementation at this point? It's still in the PR I notice.

Also the continuous integration says "undefined reference to `fmpz_poly_newton_series_to_poly_naive'"

So something must be missing at present. Maybe a name got changed somewhere and not updated elsewhere?

**Comment by wbhart** [comment]
Actually I see that you probably want the schoenhage implementation for the test code, otherwise you are only testing degree 3 polynomials or something.

I wonder if we can come up with another more general test that would make sense so we can remove the schoenhage implementation for now until it can be sped up.

I must admit I can't think of anything really useful just at the moment.

**Comment by videlec** [comment]
We can still test the fact that we get the identity by composing newton_series_to_poly with newton_series. I will remove the schoenhage formula. Note that we might still use it in the test as it is just three lines of fmpz_poly calls.

(I forgot to add a file in my cleaned commits)

**Comment by wbhart** [comment]
The original power sum function that Kiran requested could be tested by multiplying two polynomials together and checking that the individual power sum sequences sum together to give the power sum sequence of the product polynomial.

Actually, I'm unsure if this is what you are computing. I wonder if you could add a mathematical description of the definition you are using for newton series to the documentation since as I was just discussing this with someone they were unsure the precise definition you are using.

**Comment by videlec** [comment]
It is exactly the series of the power sums of the root. If the name "Newton series" is not standard I can change. If it makes more sense to return a vector instead I can also provide the corresponding function. I followed the terminology from Bostan-Flajolet-Salvy-Schost. Many operations on polynomials are much faster if we do them at the level of Newton series.

Good idea for the product in the tests!

**Comment by wbhart** [comment]
I believe power sums is standard terminology. I think there is something else called newton series. We probably should leave that name free for that.

On the other hand I haven't checked whether the other newton series is actually the same thing and I'm just confused. Also very possible.

Anyway, power sums should not be confusing.

I don't have any problem with returning a polynomial. The underscore function currently effectively returns a vector anyway, so that's fine.

**Comment by videlec** [comment]
According to wikipedia, "Newton series" is used for the formula to reconstruct a polynomial from its divided differences. I will hence avoid the name.

**Comment by wbhart** [comment]
This all looks very good to me, and all the tests pass, so I plan to merge it. If @fredrik-johansson has no issues with it I think it's done.

Thanks for the contribution!

**Comment by fredrik-johansson** [comment]
Minor improvements to the code: you just do

    fmpz_mul_ui(res + k, poly + len - 1 - k, k);

instead of

    fmpz_set(res + k, poly + len - 1 - k);
    fmpz_mul_ui(res + k, res + k, k);

and fmpz_zero(res + k) instead of fmpz_set_ui(res + k, 0), and fmpz_one(res + d) instead of fmpz_set_ui(res + d, 1);

Also, fmpz_poly_one can be used in fmpz_poly_power_sums_to_poly.

We conventionally write k++ instead of ++k except in the very rare case where the latter is useful.

I wouldn't put _fmpz_poly_power_sums_to_poly_naive in its own C file without a corresponding non-underscore method. Might be better to call this _fmpz_poly_power_sums_to_poly until there is a second implementation.

Everything else looks good.

**Comment by wbhart** [comment]
This looks great now, but there is one very small change we missed. The title printed by the test code should be power_sums, not Power sums. Once that's fixed this is ready to merge.

**Comment by videlec** [comment]
Once this is merged I will provide another pull request for non monic polynomials (that would return a fmpq_poly_t).

**Comment by wbhart** [comment]
Great. I've merged this now. Thanks again for contributing.

**Pull request merged**
