### PR TITLE
Expand and clean up Continuous Integration, fix Clang

### LINKED ISSUE #27: Test for broken compilers
See title.

### PR DESCRIPTION
**Pull request by albinahlback**
As title says.

This exposes some problems for Clang and for Cygwin, which should be uncorrelated to this PR.

This should resolve #27, unless @fredrik-johansson thinks otherwise.

### CODE REVIEW

**Comment by isuruf** [comment]
appveyor tests MSVC and MinGW-w64 and this tests only Cygwin. Could you add MSVC and MinGW-w64 tests here?

**Comment by albinahlback** [comment]
Yes, I will try. Will wait for another day, though.

**Comment by albinahlback** [comment]
Yeah, if you go into Actions, you see that those tests couldn't run because something in the code was wrong. I started writing a patch for this during last night, but I couldn't test it as GitHub was down.

I will also bring back Appveyor as I don't know how to test MSVC.

**Comment by albinahlback** [comment]
Ping @wbhart @fredrik-johansson

Sorry if you got notifications when I pushed commits today. Probably should have tested this towards my own fork in a separate branch.

As of the current state of this PR, I think it is OK. However, this exposes some problems for Clang and for Cygwin, which should be uncorrelated to this PR.

I did not remove Appveyor as I yet have to migrate that into Github Workflow.

As I spammed with commits today, you probably have to cancel all the Appveyor tests, as they accumulate tests. They should pass, though, as I have not changed anything there.

Let me know what you think.

**Comment by wbhart** [comment]
I did get all the commits, but Google combines them into a single item in GMail, so I didn't even notice until you mentioned it.

I am currently dealing with some complex logistical problems and am unavailable for some days (at least) or even possibly weeks, hence my lack of responsiveness for the time being.

**Comment by albinahlback** [comment]
@wbhart That's fine, I hope everything works out for you!

I managed to implement checking for MinGW (64-bit version), and so I removed MinGW-checking in Appveyor completely.

**Comment by albinahlback** [comment]
@isuruf Do you know how to implement checks for MSVC with Clang? I know that Github Workflows with Windows have Clang built for MSVC (can be seen by running `clang --version`) and I manage to set up Conda with MPIR and MPFR, but I am having problems with actually running CMake with Clang. The problem seems to be with `lld-link`, as seen [here](https://github.com/albinahlback/flint2/runs/5791742722?check_suite_focus=true).

**Comment by albinahlback** [comment]
Well, I think I will deal with MSVC some other time.

I am fine with the current state of this PR, and I would gladly accept some inputs if there are any. Otherwise it would be nice to have this merged. Will now focus on fixing the errors for Cygwin and Clang.

**Comment by albinahlback** [comment]
I added checking with Nemo as well, which confirms that it fails. Don't know how to backtrack this to `aors_ui.c`, but at least it can be seen from the workflow that it fails.

**Comment by albinahlback** [comment]
I don't know why Cygwin failed. Could be some linking that I did wrong since it came with gap-actions' Cygwin. I wasn't able to determine if it actually was this, as MPFR is building incredibly slow on Cygwin. As they advise users to use MinGW instead (see `INSTALL` in MPFR), I think we should drop support for Cygwin as we (at the moment) cannot validate that FLINT works on Cygwin.

**Comment by albinahlback** [comment]
I think I fixed the issues with Clang. I'm surprised that the test template `fq_poly_templates/test/t-sqrt.c` worked for GCC...

**Comment by albinahlback** [comment]
The problem with Nemo.jl will be solved when Antic_jll gets updated (see #1088).

**Comment by wbhart** [comment]
Thanks. This looks better than what we had!

**Pull request merged**
