### PR TITLE
More better cfrac

### PR DESCRIPTION
**Pull request by tthsqe12**
I still would like to investigate this a bit more. I am open to comments in the meantime.
Funnily enough, gmp seems to refer to the operation `a*b+c*d ` as `addaddmul`, which makes absolutely no sense to me. Therefore, I followed `fmpz_fmms` and used `flint_mpn_fmms1`.

### CODE REVIEW

**Comment by wbhart** [comment]
Be aware that the mpn interfaces of GMP and MPIR may differ. In some cases you have to add functionality to the Flint GMP compatibility layer. But be careful of license issues. You can't just take GMP code and put it in Flint.

**Comment by tthsqe12** [comment]
The only code I took from gmp is in the three macros `FLINT_MPN_EXTRACT_NUMB, FLINT_MPZ_REALLOC, FLINT_MPZ_PTR_SWAP` at the top of gmpcompat.h.
Could you give an example of the differing mpn interfaces of GMP and MPIR? The only possible inconsistency I have found is in `mpn_mul`, which may return either a `mp_size_t` or a `mp_limb_t`. It seems to be latter in recent version of gmp and in mpir, but I will change the flint code so that it ignores the return of `mpn_mul`.

**Comment by wbhart** [comment]
The official mpn interfaces should be the same. It's internal mpn functions such as mpn_sumdiff which will be different.

Could you do what you can to rewrite the macros in your own style, rather than copy the lines of code exactly. This is a particularly important issue, as I've probably mentioned before.

**Comment by tthsqe12** [comment]
Ok. I only use the official mpn functions, so I will keep using the return of mpn_mul.
I had another look at gmpcompat.h and I don't fully understand what it is doing when `(defined(__MINGW64__) || defined(__mips64)) && !defined(__MPIR_VERSION)` is true.
For example, here https://github.com/wbhart/flint2/blob/trunk/fmpz/and.c#L42 the `flint_mpz_init_set_si` is going to use `flint_malloc` to allocate the limbs of `tmp` but then on line 45 of the same file `mpz_clear` is used to destroy tmp. How has`mpz_clear` been instructed to use `flint_free` here?

**Comment by wbhart** [comment]
Currently GMP and Flint have to use the same memory manager. So long as Flint doesn't call malloc, calloc or free directly, everything is fine.

I haven't checked for a while if GMP has added any new mpn functions. I think some of our test code uses MPIR though, so we'll know soon enough if there are any problems.

I don't recall all the decisions that led to

```
if (defined(__MINGW64__) || defined(__mips64)) && !defined(__MPIR_VERSION)
```

They have come from various phases of porting, including for Mingw, which we use to build Flint and GMP binaries for Windows in Oscar, MIPS which probably came from porting started (but not finished) by Andreas Enge and supporting GMP vs MPIR (Flint used to only support MPIR, but once it became clear more people would eventually use GMP, we decided to fully support it).

**Comment by tthsqe12** [comment]
This code is unfortunately complicated, but I have hit it with as many corner cases as I could, and it is has not broken. It also contains some copy-paste-with-slight-modifications of other cfrac code. I won't be able to patch things up in time for the release to avoid the near code duplication. It can be cleaned up though, and it does upgrade the rational reconstruction from _worst possible_ to at least _quasi-linear_.

**Comment by wbhart** [comment]
I'll re-run the tests and merge if it passes. I think we would like to have this.

**Pull request merged**
